//! The Rust camera model must reproduce the validated Python reference on a
//! real capture. `fixtures/L16_04366_geometry.json` holds module states and
//! reference outputs generated by that implementation (`clamp` intrinsics);
//! `L16_04366_headers.lri` is the capture's metadata blocks without RAW
//! payloads, and the two overlay files come from the same device.

use std::{collections::HashMap, fs};

use chiaro_fusion::calibration::{CalibrationDatabase, IntrinsicsMode, LriMessages, ModuleState};
use chiaro_fusion::geometry::{CameraRefinement, ResolvedCamera};
use serde_json::Value;

fn fixture_dir() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn vec2(v: &Value) -> [f64; 2] {
    [v[0].as_f64().unwrap(), v[1].as_f64().unwrap()]
}

fn vec3(v: &Value) -> [f64; 3] {
    [
        v[0].as_f64().unwrap(),
        v[1].as_f64().unwrap(),
        v[2].as_f64().unwrap(),
    ]
}

fn load() -> (CalibrationDatabase, Vec<ModuleState>, Value) {
    let fixture: Value =
        serde_json::from_slice(&fs::read(fixture_dir().join("L16_04366_geometry.json")).unwrap())
            .unwrap();
    let capture =
        LriMessages::parse(&fs::read(fixture_dir().join("L16_04366_headers.lri")).unwrap())
            .unwrap();
    let overlays = ["zoom_calib_v0.lri", "calibration.lri"]
        .iter()
        .map(|name| LriMessages::parse(&fs::read(fixture_dir().join(name)).unwrap()).unwrap())
        .collect::<Vec<_>>();
    let db = CalibrationDatabase::from_capture_and_overlays(&capture, &overlays);
    let states = fixture["modules"]
        .as_array()
        .unwrap()
        .iter()
        .map(|m| ModuleState {
            name: m["camera"].as_str().unwrap().to_owned(),
            lens_hall: m["lens_position"].as_f64().unwrap(),
            mirror_hall: m["mirror_position"].as_f64().unwrap(),
            width: m["width"].as_u64().unwrap() as usize,
            height: m["height"].as_u64().unwrap() as usize,
            gain: 1.0,
            exposure_ns: 0,
        })
        .collect();
    (db, states, fixture)
}

fn cameras(db: &CalibrationDatabase, states: &[ModuleState]) -> HashMap<String, ResolvedCamera> {
    states
        .iter()
        .map(|state| {
            let camera = ResolvedCamera::new(
                db.camera(&state.name).unwrap(),
                state,
                IntrinsicsMode::Clamp,
                &CameraRefinement::default(),
            )
            .unwrap();
            (state.name.clone(), camera)
        })
        .collect()
}

#[test]
fn calibration_database_resolves_every_module_of_the_device() {
    let (db, _, _) = load();
    assert_eq!(db.cameras.len(), 16, "{:?}", db.cameras.keys());
    let a1 = db.camera("A1").unwrap();
    assert!(a1.canonical_pose.is_some() && a1.mirror.is_none() && a1.distortion.is_some());
    assert!(a1.intrinsics.len() >= 2);
    let b2 = db.camera("B2").unwrap();
    assert!(b2.canonical_pose.is_none() && b2.mirror.is_some());
    assert_eq!(
        b2.mirror.as_ref().unwrap().actuator.selected_branch(),
        Some(1)
    );
    assert!(db.camera("C5").unwrap().canonical_pose.is_some());
}

#[test]
fn calibration_overlays_are_rejected_across_physical_devices() {
    let capture =
        LriMessages::parse(&fs::read(fixture_dir().join("L16_04366_headers.lri")).unwrap())
            .unwrap();
    let embedded = CalibrationDatabase::from_capture_and_overlays(&capture, &[]);
    let mut overlay =
        LriMessages::parse(&fs::read(fixture_dir().join("calibration.lri")).unwrap()).unwrap();
    let id = capture.device_id().unwrap();
    assert_eq!(overlay.device_id(), Some(id));
    for header in &mut overlay.headers {
        if let Some(low) = header.device_unique_id_low.as_mut() {
            *low ^= 1;
        }
    }
    let rejected = CalibrationDatabase::from_capture_and_overlays(&capture, &[overlay]);
    assert_eq!(rejected.cameras.len(), embedded.cameras.len());
}

#[test]
fn intrinsics_rays_and_projections_match_the_python_reference() {
    let (db, states, fixture) = load();
    let cameras = cameras(&db, &states);
    let reference_pixels = fixture["a1_reference_pixels"].as_array().unwrap();
    let a1 = &cameras["A1"];
    let mut worst_ray = 0.0f64;
    let mut worst_projection = 0.0f64;
    for (name, expected) in fixture["cameras"].as_object().unwrap() {
        let camera = &cameras[name];
        // K
        for r in 0..3 {
            for c in 0..3 {
                let want = expected["k"][r][c].as_f64().unwrap();
                assert!((camera.k[r][c] - want).abs() < 1e-6, "{name} K[{r}][{c}]");
            }
        }
        if let Some(angle) = expected.get("mirror_angle_deg").and_then(Value::as_f64) {
            let mirror = db.camera(name).unwrap().mirror.as_ref().unwrap();
            let state = states.iter().find(|s| &s.name == name).unwrap();
            let got = mirror.actuator.angle_for_hall(state.mirror_hall).unwrap();
            assert!(
                (got - angle).abs() < 1e-9,
                "{name} mirror angle {got} vs {angle}"
            );
        }
        // pixel -> ray, and round trip
        for (i, pixel) in expected["pixels"].as_array().unwrap().iter().enumerate() {
            let ray = camera.pixel_to_ray(vec2(pixel));
            let origin = vec3(&expected["ray_origins"][i]);
            let direction = vec3(&expected["ray_directions"][i]);
            for k in 0..3 {
                assert!((ray.origin[k] - origin[k]).abs() < 1e-6, "{name} origin");
                worst_ray = worst_ray.max((ray.direction[k] - direction[k]).abs());
            }
            let point = [
                ray.origin[0] + 5000.0 * ray.direction[0],
                ray.origin[1] + 5000.0 * ray.direction[1],
                ray.origin[2] + 5000.0 * ray.direction[2],
            ];
            let back = camera.project_unbounded(point).unwrap();
            let want = vec2(&expected["roundtrip"][i]);
            worst_projection =
                worst_projection.max((back[0] - want[0]).abs().max((back[1] - want[1]).abs()));
        }
        // A1 pixels projected into this camera at far and near depth
        for (i, pixel) in reference_pixels.iter().enumerate() {
            let ray = a1.pixel_to_ray(vec2(pixel));
            for (depth, key) in [(1e7, "a1_far_projection"), (8000.0, "a1_near_projection")] {
                let point = [
                    ray.origin[0] + depth * ray.direction[0],
                    ray.origin[1] + depth * ray.direction[1],
                    ray.origin[2] + depth * ray.direction[2],
                ];
                let got = camera.project_unbounded(point).unwrap();
                let want = vec2(&expected[key][i]);
                let error = (got[0] - want[0]).abs().max((got[1] - want[1]).abs());
                worst_projection = worst_projection.max(error);
                assert!(error < 0.05, "{name} {key}[{i}]: {got:?} vs {want:?}");
            }
        }
    }
    println!(
        "worst ray direction error {worst_ray:e}, worst projection error {worst_projection:e} px"
    );
    assert!(worst_ray < 1e-7);
}
