// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `camera_id.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:ltpb.CameraID)
pub enum CameraID {
    // @@protoc_insertion_point(enum_value:ltpb.CameraID.A1)
    A1 = 0,
    // @@protoc_insertion_point(enum_value:ltpb.CameraID.A2)
    A2 = 1,
    // @@protoc_insertion_point(enum_value:ltpb.CameraID.A3)
    A3 = 2,
    // @@protoc_insertion_point(enum_value:ltpb.CameraID.A4)
    A4 = 3,
    // @@protoc_insertion_point(enum_value:ltpb.CameraID.A5)
    A5 = 4,
    // @@protoc_insertion_point(enum_value:ltpb.CameraID.B1)
    B1 = 5,
    // @@protoc_insertion_point(enum_value:ltpb.CameraID.B2)
    B2 = 6,
    // @@protoc_insertion_point(enum_value:ltpb.CameraID.B3)
    B3 = 7,
    // @@protoc_insertion_point(enum_value:ltpb.CameraID.B4)
    B4 = 8,
    // @@protoc_insertion_point(enum_value:ltpb.CameraID.B5)
    B5 = 9,
    // @@protoc_insertion_point(enum_value:ltpb.CameraID.C1)
    C1 = 10,
    // @@protoc_insertion_point(enum_value:ltpb.CameraID.C2)
    C2 = 11,
    // @@protoc_insertion_point(enum_value:ltpb.CameraID.C3)
    C3 = 12,
    // @@protoc_insertion_point(enum_value:ltpb.CameraID.C4)
    C4 = 13,
    // @@protoc_insertion_point(enum_value:ltpb.CameraID.C5)
    C5 = 14,
    // @@protoc_insertion_point(enum_value:ltpb.CameraID.C6)
    C6 = 15,
}

impl ::protobuf::Enum for CameraID {
    const NAME: &'static str = "CameraID";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<CameraID> {
        match value {
            0 => ::std::option::Option::Some(CameraID::A1),
            1 => ::std::option::Option::Some(CameraID::A2),
            2 => ::std::option::Option::Some(CameraID::A3),
            3 => ::std::option::Option::Some(CameraID::A4),
            4 => ::std::option::Option::Some(CameraID::A5),
            5 => ::std::option::Option::Some(CameraID::B1),
            6 => ::std::option::Option::Some(CameraID::B2),
            7 => ::std::option::Option::Some(CameraID::B3),
            8 => ::std::option::Option::Some(CameraID::B4),
            9 => ::std::option::Option::Some(CameraID::B5),
            10 => ::std::option::Option::Some(CameraID::C1),
            11 => ::std::option::Option::Some(CameraID::C2),
            12 => ::std::option::Option::Some(CameraID::C3),
            13 => ::std::option::Option::Some(CameraID::C4),
            14 => ::std::option::Option::Some(CameraID::C5),
            15 => ::std::option::Option::Some(CameraID::C6),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<CameraID> {
        match str {
            "A1" => ::std::option::Option::Some(CameraID::A1),
            "A2" => ::std::option::Option::Some(CameraID::A2),
            "A3" => ::std::option::Option::Some(CameraID::A3),
            "A4" => ::std::option::Option::Some(CameraID::A4),
            "A5" => ::std::option::Option::Some(CameraID::A5),
            "B1" => ::std::option::Option::Some(CameraID::B1),
            "B2" => ::std::option::Option::Some(CameraID::B2),
            "B3" => ::std::option::Option::Some(CameraID::B3),
            "B4" => ::std::option::Option::Some(CameraID::B4),
            "B5" => ::std::option::Option::Some(CameraID::B5),
            "C1" => ::std::option::Option::Some(CameraID::C1),
            "C2" => ::std::option::Option::Some(CameraID::C2),
            "C3" => ::std::option::Option::Some(CameraID::C3),
            "C4" => ::std::option::Option::Some(CameraID::C4),
            "C5" => ::std::option::Option::Some(CameraID::C5),
            "C6" => ::std::option::Option::Some(CameraID::C6),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [CameraID] = &[
        CameraID::A1,
        CameraID::A2,
        CameraID::A3,
        CameraID::A4,
        CameraID::A5,
        CameraID::B1,
        CameraID::B2,
        CameraID::B3,
        CameraID::B4,
        CameraID::B5,
        CameraID::C1,
        CameraID::C2,
        CameraID::C3,
        CameraID::C4,
        CameraID::C5,
        CameraID::C6,
    ];
}

impl ::std::default::Default for CameraID {
    fn default() -> Self {
        CameraID::A1
    }
}

