// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `camera_module.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

// @@protoc_insertion_point(message:ltpb.CameraModule)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CameraModule {
    // message fields
    // @@protoc_insertion_point(field:ltpb.CameraModule.af_info)
    pub af_info: ::protobuf::MessageField<camera_module::AFInfo>,
    // @@protoc_insertion_point(field:ltpb.CameraModule.id)
    pub id: ::std::option::Option<::protobuf::EnumOrUnknown<super::camera_id::CameraID>>,
    // @@protoc_insertion_point(field:ltpb.CameraModule.is_enabled)
    pub is_enabled: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:ltpb.CameraModule.mirror_position)
    pub mirror_position: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:ltpb.CameraModule.lens_position)
    pub lens_position: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:ltpb.CameraModule.sensor_analog_gain)
    pub sensor_analog_gain: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.CameraModule.sensor_exposure)
    pub sensor_exposure: ::std::option::Option<u64>,
    // @@protoc_insertion_point(field:ltpb.CameraModule.sensor_data_surface)
    pub sensor_data_surface: ::protobuf::MessageField<camera_module::Surface>,
    // @@protoc_insertion_point(field:ltpb.CameraModule.sensor_temparature)
    pub sensor_temparature: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:ltpb.CameraModule.sensor_is_horizontal_flip)
    pub sensor_is_horizontal_flip: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:ltpb.CameraModule.sensor_is_vertical_flip)
    pub sensor_is_vertical_flip: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:ltpb.CameraModule.sensor_bayer_red_override)
    pub sensor_bayer_red_override: ::protobuf::MessageField<super::point2i::Point2I>,
    // @@protoc_insertion_point(field:ltpb.CameraModule.sensor_digital_gain)
    pub sensor_digital_gain: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.CameraModule.frame_index)
    pub frame_index: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:ltpb.CameraModule.sensor_dpc_on)
    pub sensor_dpc_on: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:ltpb.CameraModule.sensor_exp_start_offset)
    pub sensor_exp_start_offset: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:ltpb.CameraModule.sensor_scan_speed)
    pub sensor_scan_speed: ::std::option::Option<f32>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.CameraModule.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CameraModule {
    fn default() -> &'a CameraModule {
        <CameraModule as ::protobuf::Message>::default_instance()
    }
}

impl CameraModule {
    pub fn new() -> CameraModule {
        ::std::default::Default::default()
    }

    // optional .ltpb.CameraID id = 2;

    pub fn id(&self) -> super::camera_id::CameraID {
        match self.id {
            Some(e) => e.enum_value_or(super::camera_id::CameraID::A1),
            None => super::camera_id::CameraID::A1,
        }
    }

    pub fn clear_id(&mut self) {
        self.id = ::std::option::Option::None;
    }

    pub fn has_id(&self) -> bool {
        self.id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_id(&mut self, v: super::camera_id::CameraID) {
        self.id = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional bool is_enabled = 3;

    pub fn is_enabled(&self) -> bool {
        self.is_enabled.unwrap_or(true)
    }

    pub fn clear_is_enabled(&mut self) {
        self.is_enabled = ::std::option::Option::None;
    }

    pub fn has_is_enabled(&self) -> bool {
        self.is_enabled.is_some()
    }

    // Param is passed by value, moved
    pub fn set_is_enabled(&mut self, v: bool) {
        self.is_enabled = ::std::option::Option::Some(v);
    }

    // optional int32 mirror_position = 4;

    pub fn mirror_position(&self) -> i32 {
        self.mirror_position.unwrap_or(0i32)
    }

    pub fn clear_mirror_position(&mut self) {
        self.mirror_position = ::std::option::Option::None;
    }

    pub fn has_mirror_position(&self) -> bool {
        self.mirror_position.is_some()
    }

    // Param is passed by value, moved
    pub fn set_mirror_position(&mut self, v: i32) {
        self.mirror_position = ::std::option::Option::Some(v);
    }

    // optional int32 lens_position = 5;

    pub fn lens_position(&self) -> i32 {
        self.lens_position.unwrap_or(0)
    }

    pub fn clear_lens_position(&mut self) {
        self.lens_position = ::std::option::Option::None;
    }

    pub fn has_lens_position(&self) -> bool {
        self.lens_position.is_some()
    }

    // Param is passed by value, moved
    pub fn set_lens_position(&mut self, v: i32) {
        self.lens_position = ::std::option::Option::Some(v);
    }

    // optional float sensor_analog_gain = 7;

    pub fn sensor_analog_gain(&self) -> f32 {
        self.sensor_analog_gain.unwrap_or(0.)
    }

    pub fn clear_sensor_analog_gain(&mut self) {
        self.sensor_analog_gain = ::std::option::Option::None;
    }

    pub fn has_sensor_analog_gain(&self) -> bool {
        self.sensor_analog_gain.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_analog_gain(&mut self, v: f32) {
        self.sensor_analog_gain = ::std::option::Option::Some(v);
    }

    // optional uint64 sensor_exposure = 8;

    pub fn sensor_exposure(&self) -> u64 {
        self.sensor_exposure.unwrap_or(0)
    }

    pub fn clear_sensor_exposure(&mut self) {
        self.sensor_exposure = ::std::option::Option::None;
    }

    pub fn has_sensor_exposure(&self) -> bool {
        self.sensor_exposure.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_exposure(&mut self, v: u64) {
        self.sensor_exposure = ::std::option::Option::Some(v);
    }

    // optional sint32 sensor_temparature = 10;

    pub fn sensor_temparature(&self) -> i32 {
        self.sensor_temparature.unwrap_or(0)
    }

    pub fn clear_sensor_temparature(&mut self) {
        self.sensor_temparature = ::std::option::Option::None;
    }

    pub fn has_sensor_temparature(&self) -> bool {
        self.sensor_temparature.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_temparature(&mut self, v: i32) {
        self.sensor_temparature = ::std::option::Option::Some(v);
    }

    // optional bool sensor_is_horizontal_flip = 11;

    pub fn sensor_is_horizontal_flip(&self) -> bool {
        self.sensor_is_horizontal_flip.unwrap_or(false)
    }

    pub fn clear_sensor_is_horizontal_flip(&mut self) {
        self.sensor_is_horizontal_flip = ::std::option::Option::None;
    }

    pub fn has_sensor_is_horizontal_flip(&self) -> bool {
        self.sensor_is_horizontal_flip.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_is_horizontal_flip(&mut self, v: bool) {
        self.sensor_is_horizontal_flip = ::std::option::Option::Some(v);
    }

    // optional bool sensor_is_vertical_flip = 12;

    pub fn sensor_is_vertical_flip(&self) -> bool {
        self.sensor_is_vertical_flip.unwrap_or(false)
    }

    pub fn clear_sensor_is_vertical_flip(&mut self) {
        self.sensor_is_vertical_flip = ::std::option::Option::None;
    }

    pub fn has_sensor_is_vertical_flip(&self) -> bool {
        self.sensor_is_vertical_flip.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_is_vertical_flip(&mut self, v: bool) {
        self.sensor_is_vertical_flip = ::std::option::Option::Some(v);
    }

    // optional float sensor_digital_gain = 14;

    pub fn sensor_digital_gain(&self) -> f32 {
        self.sensor_digital_gain.unwrap_or(0.)
    }

    pub fn clear_sensor_digital_gain(&mut self) {
        self.sensor_digital_gain = ::std::option::Option::None;
    }

    pub fn has_sensor_digital_gain(&self) -> bool {
        self.sensor_digital_gain.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_digital_gain(&mut self, v: f32) {
        self.sensor_digital_gain = ::std::option::Option::Some(v);
    }

    // optional uint32 frame_index = 15;

    pub fn frame_index(&self) -> u32 {
        self.frame_index.unwrap_or(0)
    }

    pub fn clear_frame_index(&mut self) {
        self.frame_index = ::std::option::Option::None;
    }

    pub fn has_frame_index(&self) -> bool {
        self.frame_index.is_some()
    }

    // Param is passed by value, moved
    pub fn set_frame_index(&mut self, v: u32) {
        self.frame_index = ::std::option::Option::Some(v);
    }

    // optional bool sensor_dpc_on = 16;

    pub fn sensor_dpc_on(&self) -> bool {
        self.sensor_dpc_on.unwrap_or(true)
    }

    pub fn clear_sensor_dpc_on(&mut self) {
        self.sensor_dpc_on = ::std::option::Option::None;
    }

    pub fn has_sensor_dpc_on(&self) -> bool {
        self.sensor_dpc_on.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_dpc_on(&mut self, v: bool) {
        self.sensor_dpc_on = ::std::option::Option::Some(v);
    }

    // optional sint32 sensor_exp_start_offset = 17;

    pub fn sensor_exp_start_offset(&self) -> i32 {
        self.sensor_exp_start_offset.unwrap_or(0)
    }

    pub fn clear_sensor_exp_start_offset(&mut self) {
        self.sensor_exp_start_offset = ::std::option::Option::None;
    }

    pub fn has_sensor_exp_start_offset(&self) -> bool {
        self.sensor_exp_start_offset.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_exp_start_offset(&mut self, v: i32) {
        self.sensor_exp_start_offset = ::std::option::Option::Some(v);
    }

    // optional float sensor_scan_speed = 18;

    pub fn sensor_scan_speed(&self) -> f32 {
        self.sensor_scan_speed.unwrap_or(0.)
    }

    pub fn clear_sensor_scan_speed(&mut self) {
        self.sensor_scan_speed = ::std::option::Option::None;
    }

    pub fn has_sensor_scan_speed(&self) -> bool {
        self.sensor_scan_speed.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_scan_speed(&mut self, v: f32) {
        self.sensor_scan_speed = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for CameraModule {
    const NAME: &'static str = "CameraModule";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.af_info)?;
                },
                16 => {
                    self.id = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                24 => {
                    self.is_enabled = ::std::option::Option::Some(is.read_bool()?);
                },
                32 => {
                    self.mirror_position = ::std::option::Option::Some(is.read_int32()?);
                },
                40 => {
                    self.lens_position = ::std::option::Option::Some(is.read_int32()?);
                },
                61 => {
                    self.sensor_analog_gain = ::std::option::Option::Some(is.read_float()?);
                },
                64 => {
                    self.sensor_exposure = ::std::option::Option::Some(is.read_uint64()?);
                },
                74 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.sensor_data_surface)?;
                },
                80 => {
                    self.sensor_temparature = ::std::option::Option::Some(is.read_sint32()?);
                },
                88 => {
                    self.sensor_is_horizontal_flip = ::std::option::Option::Some(is.read_bool()?);
                },
                96 => {
                    self.sensor_is_vertical_flip = ::std::option::Option::Some(is.read_bool()?);
                },
                106 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.sensor_bayer_red_override)?;
                },
                117 => {
                    self.sensor_digital_gain = ::std::option::Option::Some(is.read_float()?);
                },
                120 => {
                    self.frame_index = ::std::option::Option::Some(is.read_uint32()?);
                },
                128 => {
                    self.sensor_dpc_on = ::std::option::Option::Some(is.read_bool()?);
                },
                136 => {
                    self.sensor_exp_start_offset = ::std::option::Option::Some(is.read_sint32()?);
                },
                149 => {
                    self.sensor_scan_speed = ::std::option::Option::Some(is.read_float()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.af_info.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.id {
            my_size += ::protobuf::rt::int32_size(2, v.value());
        }
        if let Some(v) = self.is_enabled {
            my_size += 1 + 1;
        }
        if let Some(v) = self.mirror_position {
            my_size += ::protobuf::rt::int32_size(4, v);
        }
        if let Some(v) = self.lens_position {
            my_size += ::protobuf::rt::int32_size(5, v);
        }
        if let Some(v) = self.sensor_analog_gain {
            my_size += 1 + 4;
        }
        if let Some(v) = self.sensor_exposure {
            my_size += ::protobuf::rt::uint64_size(8, v);
        }
        if let Some(v) = self.sensor_data_surface.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.sensor_temparature {
            my_size += ::protobuf::rt::sint32_size(10, v);
        }
        if let Some(v) = self.sensor_is_horizontal_flip {
            my_size += 1 + 1;
        }
        if let Some(v) = self.sensor_is_vertical_flip {
            my_size += 1 + 1;
        }
        if let Some(v) = self.sensor_bayer_red_override.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.sensor_digital_gain {
            my_size += 1 + 4;
        }
        if let Some(v) = self.frame_index {
            my_size += ::protobuf::rt::uint32_size(15, v);
        }
        if let Some(v) = self.sensor_dpc_on {
            my_size += 2 + 1;
        }
        if let Some(v) = self.sensor_exp_start_offset {
            my_size += ::protobuf::rt::sint32_size(17, v);
        }
        if let Some(v) = self.sensor_scan_speed {
            my_size += 2 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.af_info.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.id {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.is_enabled {
            os.write_bool(3, v)?;
        }
        if let Some(v) = self.mirror_position {
            os.write_int32(4, v)?;
        }
        if let Some(v) = self.lens_position {
            os.write_int32(5, v)?;
        }
        if let Some(v) = self.sensor_analog_gain {
            os.write_float(7, v)?;
        }
        if let Some(v) = self.sensor_exposure {
            os.write_uint64(8, v)?;
        }
        if let Some(v) = self.sensor_data_surface.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(9, v, os)?;
        }
        if let Some(v) = self.sensor_temparature {
            os.write_sint32(10, v)?;
        }
        if let Some(v) = self.sensor_is_horizontal_flip {
            os.write_bool(11, v)?;
        }
        if let Some(v) = self.sensor_is_vertical_flip {
            os.write_bool(12, v)?;
        }
        if let Some(v) = self.sensor_bayer_red_override.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(13, v, os)?;
        }
        if let Some(v) = self.sensor_digital_gain {
            os.write_float(14, v)?;
        }
        if let Some(v) = self.frame_index {
            os.write_uint32(15, v)?;
        }
        if let Some(v) = self.sensor_dpc_on {
            os.write_bool(16, v)?;
        }
        if let Some(v) = self.sensor_exp_start_offset {
            os.write_sint32(17, v)?;
        }
        if let Some(v) = self.sensor_scan_speed {
            os.write_float(18, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CameraModule {
        CameraModule::new()
    }

    fn clear(&mut self) {
        self.af_info.clear();
        self.id = ::std::option::Option::None;
        self.is_enabled = ::std::option::Option::None;
        self.mirror_position = ::std::option::Option::None;
        self.lens_position = ::std::option::Option::None;
        self.sensor_analog_gain = ::std::option::Option::None;
        self.sensor_exposure = ::std::option::Option::None;
        self.sensor_data_surface.clear();
        self.sensor_temparature = ::std::option::Option::None;
        self.sensor_is_horizontal_flip = ::std::option::Option::None;
        self.sensor_is_vertical_flip = ::std::option::Option::None;
        self.sensor_bayer_red_override.clear();
        self.sensor_digital_gain = ::std::option::Option::None;
        self.frame_index = ::std::option::Option::None;
        self.sensor_dpc_on = ::std::option::Option::None;
        self.sensor_exp_start_offset = ::std::option::Option::None;
        self.sensor_scan_speed = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CameraModule {
        static instance: CameraModule = CameraModule {
            af_info: ::protobuf::MessageField::none(),
            id: ::std::option::Option::None,
            is_enabled: ::std::option::Option::None,
            mirror_position: ::std::option::Option::None,
            lens_position: ::std::option::Option::None,
            sensor_analog_gain: ::std::option::Option::None,
            sensor_exposure: ::std::option::Option::None,
            sensor_data_surface: ::protobuf::MessageField::none(),
            sensor_temparature: ::std::option::Option::None,
            sensor_is_horizontal_flip: ::std::option::Option::None,
            sensor_is_vertical_flip: ::std::option::Option::None,
            sensor_bayer_red_override: ::protobuf::MessageField::none(),
            sensor_digital_gain: ::std::option::Option::None,
            frame_index: ::std::option::Option::None,
            sensor_dpc_on: ::std::option::Option::None,
            sensor_exp_start_offset: ::std::option::Option::None,
            sensor_scan_speed: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

/// Nested message and enums of message `CameraModule`
pub mod camera_module {
    // @@protoc_insertion_point(message:ltpb.CameraModule.AFInfo)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct AFInfo {
        // message fields
        // @@protoc_insertion_point(field:ltpb.CameraModule.AFInfo.mode)
        pub mode: ::std::option::Option<::protobuf::EnumOrUnknown<afinfo::AFMode>>,
        // @@protoc_insertion_point(field:ltpb.CameraModule.AFInfo.roi_center)
        pub roi_center: ::protobuf::MessageField<super::super::point2f::Point2F>,
        // @@protoc_insertion_point(field:ltpb.CameraModule.AFInfo.disparity_focus_distance)
        pub disparity_focus_distance: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.CameraModule.AFInfo.contrast_focus_distance)
        pub contrast_focus_distance: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.CameraModule.AFInfo.lens_timeout)
        pub lens_timeout: ::std::option::Option<bool>,
        // @@protoc_insertion_point(field:ltpb.CameraModule.AFInfo.mirror_timeout)
        pub mirror_timeout: ::std::option::Option<bool>,
        // @@protoc_insertion_point(field:ltpb.CameraModule.AFInfo.mirror_position)
        pub mirror_position: ::std::option::Option<i32>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.CameraModule.AFInfo.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a AFInfo {
        fn default() -> &'a AFInfo {
            <AFInfo as ::protobuf::Message>::default_instance()
        }
    }

    impl AFInfo {
        pub fn new() -> AFInfo {
            ::std::default::Default::default()
        }

        // optional .ltpb.CameraModule.AFInfo.AFMode mode = 1;

        pub fn mode(&self) -> afinfo::AFMode {
            match self.mode {
                Some(e) => e.enum_value_or(afinfo::AFMode::AUTO),
                None => afinfo::AFMode::AUTO,
            }
        }

        pub fn clear_mode(&mut self) {
            self.mode = ::std::option::Option::None;
        }

        pub fn has_mode(&self) -> bool {
            self.mode.is_some()
        }

        // Param is passed by value, moved
        pub fn set_mode(&mut self, v: afinfo::AFMode) {
            self.mode = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
        }

        // optional float disparity_focus_distance = 3;

        pub fn disparity_focus_distance(&self) -> f32 {
            self.disparity_focus_distance.unwrap_or(0.)
        }

        pub fn clear_disparity_focus_distance(&mut self) {
            self.disparity_focus_distance = ::std::option::Option::None;
        }

        pub fn has_disparity_focus_distance(&self) -> bool {
            self.disparity_focus_distance.is_some()
        }

        // Param is passed by value, moved
        pub fn set_disparity_focus_distance(&mut self, v: f32) {
            self.disparity_focus_distance = ::std::option::Option::Some(v);
        }

        // optional float contrast_focus_distance = 4;

        pub fn contrast_focus_distance(&self) -> f32 {
            self.contrast_focus_distance.unwrap_or(0.)
        }

        pub fn clear_contrast_focus_distance(&mut self) {
            self.contrast_focus_distance = ::std::option::Option::None;
        }

        pub fn has_contrast_focus_distance(&self) -> bool {
            self.contrast_focus_distance.is_some()
        }

        // Param is passed by value, moved
        pub fn set_contrast_focus_distance(&mut self, v: f32) {
            self.contrast_focus_distance = ::std::option::Option::Some(v);
        }

        // optional bool lens_timeout = 5;

        pub fn lens_timeout(&self) -> bool {
            self.lens_timeout.unwrap_or(false)
        }

        pub fn clear_lens_timeout(&mut self) {
            self.lens_timeout = ::std::option::Option::None;
        }

        pub fn has_lens_timeout(&self) -> bool {
            self.lens_timeout.is_some()
        }

        // Param is passed by value, moved
        pub fn set_lens_timeout(&mut self, v: bool) {
            self.lens_timeout = ::std::option::Option::Some(v);
        }

        // optional bool mirror_timeout = 6;

        pub fn mirror_timeout(&self) -> bool {
            self.mirror_timeout.unwrap_or(false)
        }

        pub fn clear_mirror_timeout(&mut self) {
            self.mirror_timeout = ::std::option::Option::None;
        }

        pub fn has_mirror_timeout(&self) -> bool {
            self.mirror_timeout.is_some()
        }

        // Param is passed by value, moved
        pub fn set_mirror_timeout(&mut self, v: bool) {
            self.mirror_timeout = ::std::option::Option::Some(v);
        }

        // optional int32 mirror_position = 7;

        pub fn mirror_position(&self) -> i32 {
            self.mirror_position.unwrap_or(0)
        }

        pub fn clear_mirror_position(&mut self) {
            self.mirror_position = ::std::option::Option::None;
        }

        pub fn has_mirror_position(&self) -> bool {
            self.mirror_position.is_some()
        }

        // Param is passed by value, moved
        pub fn set_mirror_position(&mut self, v: i32) {
            self.mirror_position = ::std::option::Option::Some(v);
        }
    }

    impl ::protobuf::Message for AFInfo {
        const NAME: &'static str = "AFInfo";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    8 => {
                        self.mode = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                    },
                    18 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.roi_center)?;
                    },
                    29 => {
                        self.disparity_focus_distance = ::std::option::Option::Some(is.read_float()?);
                    },
                    37 => {
                        self.contrast_focus_distance = ::std::option::Option::Some(is.read_float()?);
                    },
                    40 => {
                        self.lens_timeout = ::std::option::Option::Some(is.read_bool()?);
                    },
                    48 => {
                        self.mirror_timeout = ::std::option::Option::Some(is.read_bool()?);
                    },
                    56 => {
                        self.mirror_position = ::std::option::Option::Some(is.read_int32()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.mode {
                my_size += ::protobuf::rt::int32_size(1, v.value());
            }
            if let Some(v) = self.roi_center.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.disparity_focus_distance {
                my_size += 1 + 4;
            }
            if let Some(v) = self.contrast_focus_distance {
                my_size += 1 + 4;
            }
            if let Some(v) = self.lens_timeout {
                my_size += 1 + 1;
            }
            if let Some(v) = self.mirror_timeout {
                my_size += 1 + 1;
            }
            if let Some(v) = self.mirror_position {
                my_size += ::protobuf::rt::int32_size(7, v);
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.mode {
                os.write_enum(1, ::protobuf::EnumOrUnknown::value(&v))?;
            }
            if let Some(v) = self.roi_center.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            }
            if let Some(v) = self.disparity_focus_distance {
                os.write_float(3, v)?;
            }
            if let Some(v) = self.contrast_focus_distance {
                os.write_float(4, v)?;
            }
            if let Some(v) = self.lens_timeout {
                os.write_bool(5, v)?;
            }
            if let Some(v) = self.mirror_timeout {
                os.write_bool(6, v)?;
            }
            if let Some(v) = self.mirror_position {
                os.write_int32(7, v)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> AFInfo {
            AFInfo::new()
        }

        fn clear(&mut self) {
            self.mode = ::std::option::Option::None;
            self.roi_center.clear();
            self.disparity_focus_distance = ::std::option::Option::None;
            self.contrast_focus_distance = ::std::option::Option::None;
            self.lens_timeout = ::std::option::Option::None;
            self.mirror_timeout = ::std::option::Option::None;
            self.mirror_position = ::std::option::Option::None;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static AFInfo {
            static instance: AFInfo = AFInfo {
                mode: ::std::option::Option::None,
                roi_center: ::protobuf::MessageField::none(),
                disparity_focus_distance: ::std::option::Option::None,
                contrast_focus_distance: ::std::option::Option::None,
                lens_timeout: ::std::option::Option::None,
                mirror_timeout: ::std::option::Option::None,
                mirror_position: ::std::option::Option::None,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    /// Nested message and enums of message `AFInfo`
    pub mod afinfo {
        #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
        // @@protoc_insertion_point(enum:ltpb.CameraModule.AFInfo.AFMode)
        pub enum AFMode {
            // @@protoc_insertion_point(enum_value:ltpb.CameraModule.AFInfo.AFMode.AUTO)
            AUTO = 0,
        }

        impl ::protobuf::Enum for AFMode {
            const NAME: &'static str = "AFMode";

            fn value(&self) -> i32 {
                *self as i32
            }

            fn from_i32(value: i32) -> ::std::option::Option<AFMode> {
                match value {
                    0 => ::std::option::Option::Some(AFMode::AUTO),
                    _ => ::std::option::Option::None
                }
            }

            fn from_str(str: &str) -> ::std::option::Option<AFMode> {
                match str {
                    "AUTO" => ::std::option::Option::Some(AFMode::AUTO),
                    _ => ::std::option::Option::None
                }
            }

            const VALUES: &'static [AFMode] = &[
                AFMode::AUTO,
            ];
        }

        impl ::std::default::Default for AFMode {
            fn default() -> Self {
                AFMode::AUTO
            }
        }

    }

    // @@protoc_insertion_point(message:ltpb.CameraModule.Surface)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct Surface {
        // message fields
        // @@protoc_insertion_point(field:ltpb.CameraModule.Surface.start)
        pub start: ::protobuf::MessageField<super::super::point2i::Point2I>,
        // @@protoc_insertion_point(field:ltpb.CameraModule.Surface.size)
        pub size: ::protobuf::MessageField<super::super::point2i::Point2I>,
        // @@protoc_insertion_point(field:ltpb.CameraModule.Surface.format)
        pub format: ::std::option::Option<::protobuf::EnumOrUnknown<surface::FormatType>>,
        // @@protoc_insertion_point(field:ltpb.CameraModule.Surface.row_stride)
        pub row_stride: ::std::option::Option<u32>,
        // @@protoc_insertion_point(field:ltpb.CameraModule.Surface.data_offset)
        pub data_offset: ::std::option::Option<u64>,
        // @@protoc_insertion_point(field:ltpb.CameraModule.Surface.data_scale)
        pub data_scale: ::protobuf::MessageField<super::super::point2f::Point2F>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.CameraModule.Surface.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Surface {
        fn default() -> &'a Surface {
            <Surface as ::protobuf::Message>::default_instance()
        }
    }

    impl Surface {
        pub fn new() -> Surface {
            ::std::default::Default::default()
        }

        // optional .ltpb.CameraModule.Surface.FormatType format = 3;

        pub fn format(&self) -> surface::FormatType {
            match self.format {
                Some(e) => e.enum_value_or(surface::FormatType::RAW_BAYER_JPEG),
                None => surface::FormatType::RAW_BAYER_JPEG,
            }
        }

        pub fn clear_format(&mut self) {
            self.format = ::std::option::Option::None;
        }

        pub fn has_format(&self) -> bool {
            self.format.is_some()
        }

        // Param is passed by value, moved
        pub fn set_format(&mut self, v: surface::FormatType) {
            self.format = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
        }

        // optional uint32 row_stride = 4;

        pub fn row_stride(&self) -> u32 {
            self.row_stride.unwrap_or(0)
        }

        pub fn clear_row_stride(&mut self) {
            self.row_stride = ::std::option::Option::None;
        }

        pub fn has_row_stride(&self) -> bool {
            self.row_stride.is_some()
        }

        // Param is passed by value, moved
        pub fn set_row_stride(&mut self, v: u32) {
            self.row_stride = ::std::option::Option::Some(v);
        }

        // optional uint64 data_offset = 5;

        pub fn data_offset(&self) -> u64 {
            self.data_offset.unwrap_or(0)
        }

        pub fn clear_data_offset(&mut self) {
            self.data_offset = ::std::option::Option::None;
        }

        pub fn has_data_offset(&self) -> bool {
            self.data_offset.is_some()
        }

        // Param is passed by value, moved
        pub fn set_data_offset(&mut self, v: u64) {
            self.data_offset = ::std::option::Option::Some(v);
        }
    }

    impl ::protobuf::Message for Surface {
        const NAME: &'static str = "Surface";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.start)?;
                    },
                    18 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.size)?;
                    },
                    24 => {
                        self.format = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                    },
                    32 => {
                        self.row_stride = ::std::option::Option::Some(is.read_uint32()?);
                    },
                    40 => {
                        self.data_offset = ::std::option::Option::Some(is.read_uint64()?);
                    },
                    50 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.data_scale)?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.start.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.size.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.format {
                my_size += ::protobuf::rt::int32_size(3, v.value());
            }
            if let Some(v) = self.row_stride {
                my_size += ::protobuf::rt::uint32_size(4, v);
            }
            if let Some(v) = self.data_offset {
                my_size += ::protobuf::rt::uint64_size(5, v);
            }
            if let Some(v) = self.data_scale.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.start.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
            }
            if let Some(v) = self.size.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            }
            if let Some(v) = self.format {
                os.write_enum(3, ::protobuf::EnumOrUnknown::value(&v))?;
            }
            if let Some(v) = self.row_stride {
                os.write_uint32(4, v)?;
            }
            if let Some(v) = self.data_offset {
                os.write_uint64(5, v)?;
            }
            if let Some(v) = self.data_scale.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Surface {
            Surface::new()
        }

        fn clear(&mut self) {
            self.start.clear();
            self.size.clear();
            self.format = ::std::option::Option::None;
            self.row_stride = ::std::option::Option::None;
            self.data_offset = ::std::option::Option::None;
            self.data_scale.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Surface {
            static instance: Surface = Surface {
                start: ::protobuf::MessageField::none(),
                size: ::protobuf::MessageField::none(),
                format: ::std::option::Option::None,
                row_stride: ::std::option::Option::None,
                data_offset: ::std::option::Option::None,
                data_scale: ::protobuf::MessageField::none(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    /// Nested message and enums of message `Surface`
    pub mod surface {
        #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
        // @@protoc_insertion_point(enum:ltpb.CameraModule.Surface.FormatType)
        pub enum FormatType {
            // @@protoc_insertion_point(enum_value:ltpb.CameraModule.Surface.FormatType.RAW_BAYER_JPEG)
            RAW_BAYER_JPEG = 0,
            // @@protoc_insertion_point(enum_value:ltpb.CameraModule.Surface.FormatType.RAW_RESERVED_0)
            RAW_RESERVED_0 = 1,
            // @@protoc_insertion_point(enum_value:ltpb.CameraModule.Surface.FormatType.RAW_RESERVED_1)
            RAW_RESERVED_1 = 2,
            // @@protoc_insertion_point(enum_value:ltpb.CameraModule.Surface.FormatType.RAW_RESERVED_2)
            RAW_RESERVED_2 = 3,
            // @@protoc_insertion_point(enum_value:ltpb.CameraModule.Surface.FormatType.RAW_RESERVED_3)
            RAW_RESERVED_3 = 4,
            // @@protoc_insertion_point(enum_value:ltpb.CameraModule.Surface.FormatType.RAW_RESERVED_4)
            RAW_RESERVED_4 = 5,
            // @@protoc_insertion_point(enum_value:ltpb.CameraModule.Surface.FormatType.RAW_RESERVED_5)
            RAW_RESERVED_5 = 6,
            // @@protoc_insertion_point(enum_value:ltpb.CameraModule.Surface.FormatType.RAW_PACKED_10BPP)
            RAW_PACKED_10BPP = 7,
            // @@protoc_insertion_point(enum_value:ltpb.CameraModule.Surface.FormatType.RAW_PACKED_12BPP)
            RAW_PACKED_12BPP = 8,
            // @@protoc_insertion_point(enum_value:ltpb.CameraModule.Surface.FormatType.RAW_PACKED_14BPP)
            RAW_PACKED_14BPP = 9,
        }

        impl ::protobuf::Enum for FormatType {
            const NAME: &'static str = "FormatType";

            fn value(&self) -> i32 {
                *self as i32
            }

            fn from_i32(value: i32) -> ::std::option::Option<FormatType> {
                match value {
                    0 => ::std::option::Option::Some(FormatType::RAW_BAYER_JPEG),
                    1 => ::std::option::Option::Some(FormatType::RAW_RESERVED_0),
                    2 => ::std::option::Option::Some(FormatType::RAW_RESERVED_1),
                    3 => ::std::option::Option::Some(FormatType::RAW_RESERVED_2),
                    4 => ::std::option::Option::Some(FormatType::RAW_RESERVED_3),
                    5 => ::std::option::Option::Some(FormatType::RAW_RESERVED_4),
                    6 => ::std::option::Option::Some(FormatType::RAW_RESERVED_5),
                    7 => ::std::option::Option::Some(FormatType::RAW_PACKED_10BPP),
                    8 => ::std::option::Option::Some(FormatType::RAW_PACKED_12BPP),
                    9 => ::std::option::Option::Some(FormatType::RAW_PACKED_14BPP),
                    _ => ::std::option::Option::None
                }
            }

            fn from_str(str: &str) -> ::std::option::Option<FormatType> {
                match str {
                    "RAW_BAYER_JPEG" => ::std::option::Option::Some(FormatType::RAW_BAYER_JPEG),
                    "RAW_RESERVED_0" => ::std::option::Option::Some(FormatType::RAW_RESERVED_0),
                    "RAW_RESERVED_1" => ::std::option::Option::Some(FormatType::RAW_RESERVED_1),
                    "RAW_RESERVED_2" => ::std::option::Option::Some(FormatType::RAW_RESERVED_2),
                    "RAW_RESERVED_3" => ::std::option::Option::Some(FormatType::RAW_RESERVED_3),
                    "RAW_RESERVED_4" => ::std::option::Option::Some(FormatType::RAW_RESERVED_4),
                    "RAW_RESERVED_5" => ::std::option::Option::Some(FormatType::RAW_RESERVED_5),
                    "RAW_PACKED_10BPP" => ::std::option::Option::Some(FormatType::RAW_PACKED_10BPP),
                    "RAW_PACKED_12BPP" => ::std::option::Option::Some(FormatType::RAW_PACKED_12BPP),
                    "RAW_PACKED_14BPP" => ::std::option::Option::Some(FormatType::RAW_PACKED_14BPP),
                    _ => ::std::option::Option::None
                }
            }

            const VALUES: &'static [FormatType] = &[
                FormatType::RAW_BAYER_JPEG,
                FormatType::RAW_RESERVED_0,
                FormatType::RAW_RESERVED_1,
                FormatType::RAW_RESERVED_2,
                FormatType::RAW_RESERVED_3,
                FormatType::RAW_RESERVED_4,
                FormatType::RAW_RESERVED_5,
                FormatType::RAW_PACKED_10BPP,
                FormatType::RAW_PACKED_12BPP,
                FormatType::RAW_PACKED_14BPP,
            ];
        }

        impl ::std::default::Default for FormatType {
            fn default() -> Self {
                FormatType::RAW_BAYER_JPEG
            }
        }

    }
}
