// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `color_calibration.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

// @@protoc_insertion_point(message:ltpb.ColorCalibration)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ColorCalibration {
    // message fields
    // @@protoc_insertion_point(field:ltpb.ColorCalibration.type)
    pub type_: ::std::option::Option<::protobuf::EnumOrUnknown<color_calibration::IlluminantType>>,
    // @@protoc_insertion_point(field:ltpb.ColorCalibration.forward_matrix)
    pub forward_matrix: ::protobuf::MessageField<super::matrix3x3f::Matrix3x3F>,
    // @@protoc_insertion_point(field:ltpb.ColorCalibration.color_matrix)
    pub color_matrix: ::protobuf::MessageField<super::matrix3x3f::Matrix3x3F>,
    // @@protoc_insertion_point(field:ltpb.ColorCalibration.rg_ratio)
    pub rg_ratio: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.ColorCalibration.bg_ratio)
    pub bg_ratio: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.ColorCalibration.macbeth_data)
    pub macbeth_data: ::std::vec::Vec<super::point3f::Point3F>,
    // @@protoc_insertion_point(field:ltpb.ColorCalibration.illuminant_spd)
    pub illuminant_spd: ::std::vec::Vec<super::point2f::Point2F>,
    // @@protoc_insertion_point(field:ltpb.ColorCalibration.spectral_data)
    pub spectral_data: ::protobuf::MessageField<color_calibration::SpectralData>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.ColorCalibration.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ColorCalibration {
    fn default() -> &'a ColorCalibration {
        <ColorCalibration as ::protobuf::Message>::default_instance()
    }
}

impl ColorCalibration {
    pub fn new() -> ColorCalibration {
        ::std::default::Default::default()
    }

    // optional .ltpb.ColorCalibration.IlluminantType type = 1;

    pub fn type_(&self) -> color_calibration::IlluminantType {
        match self.type_ {
            Some(e) => e.enum_value_or(color_calibration::IlluminantType::A),
            None => color_calibration::IlluminantType::A,
        }
    }

    pub fn clear_type_(&mut self) {
        self.type_ = ::std::option::Option::None;
    }

    pub fn has_type(&self) -> bool {
        self.type_.is_some()
    }

    // Param is passed by value, moved
    pub fn set_type(&mut self, v: color_calibration::IlluminantType) {
        self.type_ = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional float rg_ratio = 4;

    pub fn rg_ratio(&self) -> f32 {
        self.rg_ratio.unwrap_or(0.)
    }

    pub fn clear_rg_ratio(&mut self) {
        self.rg_ratio = ::std::option::Option::None;
    }

    pub fn has_rg_ratio(&self) -> bool {
        self.rg_ratio.is_some()
    }

    // Param is passed by value, moved
    pub fn set_rg_ratio(&mut self, v: f32) {
        self.rg_ratio = ::std::option::Option::Some(v);
    }

    // optional float bg_ratio = 5;

    pub fn bg_ratio(&self) -> f32 {
        self.bg_ratio.unwrap_or(0.)
    }

    pub fn clear_bg_ratio(&mut self) {
        self.bg_ratio = ::std::option::Option::None;
    }

    pub fn has_bg_ratio(&self) -> bool {
        self.bg_ratio.is_some()
    }

    // Param is passed by value, moved
    pub fn set_bg_ratio(&mut self, v: f32) {
        self.bg_ratio = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for ColorCalibration {
    const NAME: &'static str = "ColorCalibration";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.type_ = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.forward_matrix)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.color_matrix)?;
                },
                37 => {
                    self.rg_ratio = ::std::option::Option::Some(is.read_float()?);
                },
                45 => {
                    self.bg_ratio = ::std::option::Option::Some(is.read_float()?);
                },
                50 => {
                    self.macbeth_data.push(is.read_message()?);
                },
                58 => {
                    self.illuminant_spd.push(is.read_message()?);
                },
                66 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.spectral_data)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.type_ {
            my_size += ::protobuf::rt::int32_size(1, v.value());
        }
        if let Some(v) = self.forward_matrix.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.color_matrix.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.rg_ratio {
            my_size += 1 + 4;
        }
        if let Some(v) = self.bg_ratio {
            my_size += 1 + 4;
        }
        for value in &self.macbeth_data {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.illuminant_spd {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.spectral_data.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.type_ {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.forward_matrix.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.color_matrix.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if let Some(v) = self.rg_ratio {
            os.write_float(4, v)?;
        }
        if let Some(v) = self.bg_ratio {
            os.write_float(5, v)?;
        }
        for v in &self.macbeth_data {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        };
        for v in &self.illuminant_spd {
            ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
        };
        if let Some(v) = self.spectral_data.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ColorCalibration {
        ColorCalibration::new()
    }

    fn clear(&mut self) {
        self.type_ = ::std::option::Option::None;
        self.forward_matrix.clear();
        self.color_matrix.clear();
        self.rg_ratio = ::std::option::Option::None;
        self.bg_ratio = ::std::option::Option::None;
        self.macbeth_data.clear();
        self.illuminant_spd.clear();
        self.spectral_data.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ColorCalibration {
        static instance: ColorCalibration = ColorCalibration {
            type_: ::std::option::Option::None,
            forward_matrix: ::protobuf::MessageField::none(),
            color_matrix: ::protobuf::MessageField::none(),
            rg_ratio: ::std::option::Option::None,
            bg_ratio: ::std::option::Option::None,
            macbeth_data: ::std::vec::Vec::new(),
            illuminant_spd: ::std::vec::Vec::new(),
            spectral_data: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

/// Nested message and enums of message `ColorCalibration`
pub mod color_calibration {
    // @@protoc_insertion_point(message:ltpb.ColorCalibration.SpectralData)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct SpectralData {
        // message fields
        // @@protoc_insertion_point(field:ltpb.ColorCalibration.SpectralData.format)
        pub format: ::std::option::Option<::protobuf::EnumOrUnknown<spectral_data::ChannelFormat>>,
        // @@protoc_insertion_point(field:ltpb.ColorCalibration.SpectralData.channel_data)
        pub channel_data: ::std::vec::Vec<SpectralSensitivity>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.ColorCalibration.SpectralData.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a SpectralData {
        fn default() -> &'a SpectralData {
            <SpectralData as ::protobuf::Message>::default_instance()
        }
    }

    impl SpectralData {
        pub fn new() -> SpectralData {
            ::std::default::Default::default()
        }

        // optional .ltpb.ColorCalibration.SpectralData.ChannelFormat format = 1;

        pub fn format(&self) -> spectral_data::ChannelFormat {
            match self.format {
                Some(e) => e.enum_value_or(spectral_data::ChannelFormat::MONO),
                None => spectral_data::ChannelFormat::MONO,
            }
        }

        pub fn clear_format(&mut self) {
            self.format = ::std::option::Option::None;
        }

        pub fn has_format(&self) -> bool {
            self.format.is_some()
        }

        // Param is passed by value, moved
        pub fn set_format(&mut self, v: spectral_data::ChannelFormat) {
            self.format = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
        }
    }

    impl ::protobuf::Message for SpectralData {
        const NAME: &'static str = "SpectralData";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    8 => {
                        self.format = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                    },
                    18 => {
                        self.channel_data.push(is.read_message()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.format {
                my_size += ::protobuf::rt::int32_size(1, v.value());
            }
            for value in &self.channel_data {
                let len = value.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            };
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.format {
                os.write_enum(1, ::protobuf::EnumOrUnknown::value(&v))?;
            }
            for v in &self.channel_data {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            };
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> SpectralData {
            SpectralData::new()
        }

        fn clear(&mut self) {
            self.format = ::std::option::Option::None;
            self.channel_data.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static SpectralData {
            static instance: SpectralData = SpectralData {
                format: ::std::option::Option::None,
                channel_data: ::std::vec::Vec::new(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    /// Nested message and enums of message `SpectralData`
    pub mod spectral_data {
        #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
        // @@protoc_insertion_point(enum:ltpb.ColorCalibration.SpectralData.ChannelFormat)
        pub enum ChannelFormat {
            // @@protoc_insertion_point(enum_value:ltpb.ColorCalibration.SpectralData.ChannelFormat.MONO)
            MONO = 0,
            // @@protoc_insertion_point(enum_value:ltpb.ColorCalibration.SpectralData.ChannelFormat.RGB)
            RGB = 1,
            // @@protoc_insertion_point(enum_value:ltpb.ColorCalibration.SpectralData.ChannelFormat.BAYER_RGGB)
            BAYER_RGGB = 2,
        }

        impl ::protobuf::Enum for ChannelFormat {
            const NAME: &'static str = "ChannelFormat";

            fn value(&self) -> i32 {
                *self as i32
            }

            fn from_i32(value: i32) -> ::std::option::Option<ChannelFormat> {
                match value {
                    0 => ::std::option::Option::Some(ChannelFormat::MONO),
                    1 => ::std::option::Option::Some(ChannelFormat::RGB),
                    2 => ::std::option::Option::Some(ChannelFormat::BAYER_RGGB),
                    _ => ::std::option::Option::None
                }
            }

            fn from_str(str: &str) -> ::std::option::Option<ChannelFormat> {
                match str {
                    "MONO" => ::std::option::Option::Some(ChannelFormat::MONO),
                    "RGB" => ::std::option::Option::Some(ChannelFormat::RGB),
                    "BAYER_RGGB" => ::std::option::Option::Some(ChannelFormat::BAYER_RGGB),
                    _ => ::std::option::Option::None
                }
            }

            const VALUES: &'static [ChannelFormat] = &[
                ChannelFormat::MONO,
                ChannelFormat::RGB,
                ChannelFormat::BAYER_RGGB,
            ];
        }

        impl ::std::default::Default for ChannelFormat {
            fn default() -> Self {
                ChannelFormat::MONO
            }
        }

    }

    // @@protoc_insertion_point(message:ltpb.ColorCalibration.SpectralSensitivity)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct SpectralSensitivity {
        // message fields
        // @@protoc_insertion_point(field:ltpb.ColorCalibration.SpectralSensitivity.start)
        pub start: ::std::option::Option<u32>,
        // @@protoc_insertion_point(field:ltpb.ColorCalibration.SpectralSensitivity.end)
        pub end: ::std::option::Option<u32>,
        // @@protoc_insertion_point(field:ltpb.ColorCalibration.SpectralSensitivity.data)
        pub data: ::std::vec::Vec<f32>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.ColorCalibration.SpectralSensitivity.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a SpectralSensitivity {
        fn default() -> &'a SpectralSensitivity {
            <SpectralSensitivity as ::protobuf::Message>::default_instance()
        }
    }

    impl SpectralSensitivity {
        pub fn new() -> SpectralSensitivity {
            ::std::default::Default::default()
        }

        // optional uint32 start = 1;

        pub fn start(&self) -> u32 {
            self.start.unwrap_or(0)
        }

        pub fn clear_start(&mut self) {
            self.start = ::std::option::Option::None;
        }

        pub fn has_start(&self) -> bool {
            self.start.is_some()
        }

        // Param is passed by value, moved
        pub fn set_start(&mut self, v: u32) {
            self.start = ::std::option::Option::Some(v);
        }

        // optional uint32 end = 2;

        pub fn end(&self) -> u32 {
            self.end.unwrap_or(0)
        }

        pub fn clear_end(&mut self) {
            self.end = ::std::option::Option::None;
        }

        pub fn has_end(&self) -> bool {
            self.end.is_some()
        }

        // Param is passed by value, moved
        pub fn set_end(&mut self, v: u32) {
            self.end = ::std::option::Option::Some(v);
        }
    }

    impl ::protobuf::Message for SpectralSensitivity {
        const NAME: &'static str = "SpectralSensitivity";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    8 => {
                        self.start = ::std::option::Option::Some(is.read_uint32()?);
                    },
                    16 => {
                        self.end = ::std::option::Option::Some(is.read_uint32()?);
                    },
                    26 => {
                        is.read_repeated_packed_float_into(&mut self.data)?;
                    },
                    29 => {
                        self.data.push(is.read_float()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.start {
                my_size += ::protobuf::rt::uint32_size(1, v);
            }
            if let Some(v) = self.end {
                my_size += ::protobuf::rt::uint32_size(2, v);
            }
            my_size += ::protobuf::rt::vec_packed_float_size(3, &self.data);
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.start {
                os.write_uint32(1, v)?;
            }
            if let Some(v) = self.end {
                os.write_uint32(2, v)?;
            }
            os.write_repeated_packed_float(3, &self.data)?;
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> SpectralSensitivity {
            SpectralSensitivity::new()
        }

        fn clear(&mut self) {
            self.start = ::std::option::Option::None;
            self.end = ::std::option::Option::None;
            self.data.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static SpectralSensitivity {
            static instance: SpectralSensitivity = SpectralSensitivity {
                start: ::std::option::Option::None,
                end: ::std::option::Option::None,
                data: ::std::vec::Vec::new(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.ColorCalibration.IlluminantType)
    pub enum IlluminantType {
        // @@protoc_insertion_point(enum_value:ltpb.ColorCalibration.IlluminantType.A)
        A = 0,
        // @@protoc_insertion_point(enum_value:ltpb.ColorCalibration.IlluminantType.D50)
        D50 = 1,
        // @@protoc_insertion_point(enum_value:ltpb.ColorCalibration.IlluminantType.D65)
        D65 = 2,
        // @@protoc_insertion_point(enum_value:ltpb.ColorCalibration.IlluminantType.D75)
        D75 = 3,
        // @@protoc_insertion_point(enum_value:ltpb.ColorCalibration.IlluminantType.F2)
        F2 = 4,
        // @@protoc_insertion_point(enum_value:ltpb.ColorCalibration.IlluminantType.F7)
        F7 = 5,
        // @@protoc_insertion_point(enum_value:ltpb.ColorCalibration.IlluminantType.F11)
        F11 = 6,
        // @@protoc_insertion_point(enum_value:ltpb.ColorCalibration.IlluminantType.TL84)
        TL84 = 7,
        // @@protoc_insertion_point(enum_value:ltpb.ColorCalibration.IlluminantType.UNKNOWN)
        UNKNOWN = 99,
    }

    impl ::protobuf::Enum for IlluminantType {
        const NAME: &'static str = "IlluminantType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<IlluminantType> {
            match value {
                0 => ::std::option::Option::Some(IlluminantType::A),
                1 => ::std::option::Option::Some(IlluminantType::D50),
                2 => ::std::option::Option::Some(IlluminantType::D65),
                3 => ::std::option::Option::Some(IlluminantType::D75),
                4 => ::std::option::Option::Some(IlluminantType::F2),
                5 => ::std::option::Option::Some(IlluminantType::F7),
                6 => ::std::option::Option::Some(IlluminantType::F11),
                7 => ::std::option::Option::Some(IlluminantType::TL84),
                99 => ::std::option::Option::Some(IlluminantType::UNKNOWN),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<IlluminantType> {
            match str {
                "A" => ::std::option::Option::Some(IlluminantType::A),
                "D50" => ::std::option::Option::Some(IlluminantType::D50),
                "D65" => ::std::option::Option::Some(IlluminantType::D65),
                "D75" => ::std::option::Option::Some(IlluminantType::D75),
                "F2" => ::std::option::Option::Some(IlluminantType::F2),
                "F7" => ::std::option::Option::Some(IlluminantType::F7),
                "F11" => ::std::option::Option::Some(IlluminantType::F11),
                "TL84" => ::std::option::Option::Some(IlluminantType::TL84),
                "UNKNOWN" => ::std::option::Option::Some(IlluminantType::UNKNOWN),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [IlluminantType] = &[
            IlluminantType::A,
            IlluminantType::D50,
            IlluminantType::D65,
            IlluminantType::D75,
            IlluminantType::F2,
            IlluminantType::F7,
            IlluminantType::F11,
            IlluminantType::TL84,
            IlluminantType::UNKNOWN,
        ];
    }

    impl ::std::default::Default for IlluminantType {
        fn default() -> Self {
            IlluminantType::A
        }
    }

}
