// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `dead_pixel_map.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

// @@protoc_insertion_point(message:ltpb.DeadPixelMap)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct DeadPixelMap {
    // message fields
    // @@protoc_insertion_point(field:ltpb.DeadPixelMap.data_offset)
    pub data_offset: ::std::option::Option<u64>,
    // @@protoc_insertion_point(field:ltpb.DeadPixelMap.data_size)
    pub data_size: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:ltpb.DeadPixelMap.black_level_threshold)
    pub black_level_threshold: ::std::option::Option<f32>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.DeadPixelMap.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DeadPixelMap {
    fn default() -> &'a DeadPixelMap {
        <DeadPixelMap as ::protobuf::Message>::default_instance()
    }
}

impl DeadPixelMap {
    pub fn new() -> DeadPixelMap {
        ::std::default::Default::default()
    }

    // optional uint64 data_offset = 1;

    pub fn data_offset(&self) -> u64 {
        self.data_offset.unwrap_or(0)
    }

    pub fn clear_data_offset(&mut self) {
        self.data_offset = ::std::option::Option::None;
    }

    pub fn has_data_offset(&self) -> bool {
        self.data_offset.is_some()
    }

    // Param is passed by value, moved
    pub fn set_data_offset(&mut self, v: u64) {
        self.data_offset = ::std::option::Option::Some(v);
    }

    // optional uint32 data_size = 2;

    pub fn data_size(&self) -> u32 {
        self.data_size.unwrap_or(0)
    }

    pub fn clear_data_size(&mut self) {
        self.data_size = ::std::option::Option::None;
    }

    pub fn has_data_size(&self) -> bool {
        self.data_size.is_some()
    }

    // Param is passed by value, moved
    pub fn set_data_size(&mut self, v: u32) {
        self.data_size = ::std::option::Option::Some(v);
    }

    // optional float black_level_threshold = 3;

    pub fn black_level_threshold(&self) -> f32 {
        self.black_level_threshold.unwrap_or(0.)
    }

    pub fn clear_black_level_threshold(&mut self) {
        self.black_level_threshold = ::std::option::Option::None;
    }

    pub fn has_black_level_threshold(&self) -> bool {
        self.black_level_threshold.is_some()
    }

    // Param is passed by value, moved
    pub fn set_black_level_threshold(&mut self, v: f32) {
        self.black_level_threshold = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for DeadPixelMap {
    const NAME: &'static str = "DeadPixelMap";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.data_offset = ::std::option::Option::Some(is.read_uint64()?);
                },
                16 => {
                    self.data_size = ::std::option::Option::Some(is.read_uint32()?);
                },
                29 => {
                    self.black_level_threshold = ::std::option::Option::Some(is.read_float()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.data_offset {
            my_size += ::protobuf::rt::uint64_size(1, v);
        }
        if let Some(v) = self.data_size {
            my_size += ::protobuf::rt::uint32_size(2, v);
        }
        if let Some(v) = self.black_level_threshold {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.data_offset {
            os.write_uint64(1, v)?;
        }
        if let Some(v) = self.data_size {
            os.write_uint32(2, v)?;
        }
        if let Some(v) = self.black_level_threshold {
            os.write_float(3, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DeadPixelMap {
        DeadPixelMap::new()
    }

    fn clear(&mut self) {
        self.data_offset = ::std::option::Option::None;
        self.data_size = ::std::option::Option::None;
        self.black_level_threshold = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DeadPixelMap {
        static instance: DeadPixelMap = DeadPixelMap {
            data_offset: ::std::option::Option::None,
            data_size: ::std::option::Option::None,
            black_level_threshold: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}
