// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `device_temp.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

// @@protoc_insertion_point(message:ltpb.DeviceTemp)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct DeviceTemp {
    // message fields
    // @@protoc_insertion_point(field:ltpb.DeviceTemp.sensor_1)
    pub sensor_1: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:ltpb.DeviceTemp.sensor_2)
    pub sensor_2: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:ltpb.DeviceTemp.sensor_3)
    pub sensor_3: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:ltpb.DeviceTemp.sensor_4)
    pub sensor_4: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:ltpb.DeviceTemp.flex_sensor_1)
    pub flex_sensor_1: ::std::option::Option<i32>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.DeviceTemp.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DeviceTemp {
    fn default() -> &'a DeviceTemp {
        <DeviceTemp as ::protobuf::Message>::default_instance()
    }
}

impl DeviceTemp {
    pub fn new() -> DeviceTemp {
        ::std::default::Default::default()
    }

    // optional sint32 sensor_1 = 1;

    pub fn sensor_1(&self) -> i32 {
        self.sensor_1.unwrap_or(0)
    }

    pub fn clear_sensor_1(&mut self) {
        self.sensor_1 = ::std::option::Option::None;
    }

    pub fn has_sensor_1(&self) -> bool {
        self.sensor_1.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_1(&mut self, v: i32) {
        self.sensor_1 = ::std::option::Option::Some(v);
    }

    // optional sint32 sensor_2 = 2;

    pub fn sensor_2(&self) -> i32 {
        self.sensor_2.unwrap_or(0)
    }

    pub fn clear_sensor_2(&mut self) {
        self.sensor_2 = ::std::option::Option::None;
    }

    pub fn has_sensor_2(&self) -> bool {
        self.sensor_2.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_2(&mut self, v: i32) {
        self.sensor_2 = ::std::option::Option::Some(v);
    }

    // optional sint32 sensor_3 = 3;

    pub fn sensor_3(&self) -> i32 {
        self.sensor_3.unwrap_or(0)
    }

    pub fn clear_sensor_3(&mut self) {
        self.sensor_3 = ::std::option::Option::None;
    }

    pub fn has_sensor_3(&self) -> bool {
        self.sensor_3.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_3(&mut self, v: i32) {
        self.sensor_3 = ::std::option::Option::Some(v);
    }

    // optional sint32 sensor_4 = 4;

    pub fn sensor_4(&self) -> i32 {
        self.sensor_4.unwrap_or(0)
    }

    pub fn clear_sensor_4(&mut self) {
        self.sensor_4 = ::std::option::Option::None;
    }

    pub fn has_sensor_4(&self) -> bool {
        self.sensor_4.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_4(&mut self, v: i32) {
        self.sensor_4 = ::std::option::Option::Some(v);
    }

    // optional sint32 flex_sensor_1 = 5;

    pub fn flex_sensor_1(&self) -> i32 {
        self.flex_sensor_1.unwrap_or(0)
    }

    pub fn clear_flex_sensor_1(&mut self) {
        self.flex_sensor_1 = ::std::option::Option::None;
    }

    pub fn has_flex_sensor_1(&self) -> bool {
        self.flex_sensor_1.is_some()
    }

    // Param is passed by value, moved
    pub fn set_flex_sensor_1(&mut self, v: i32) {
        self.flex_sensor_1 = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for DeviceTemp {
    const NAME: &'static str = "DeviceTemp";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.sensor_1 = ::std::option::Option::Some(is.read_sint32()?);
                },
                16 => {
                    self.sensor_2 = ::std::option::Option::Some(is.read_sint32()?);
                },
                24 => {
                    self.sensor_3 = ::std::option::Option::Some(is.read_sint32()?);
                },
                32 => {
                    self.sensor_4 = ::std::option::Option::Some(is.read_sint32()?);
                },
                40 => {
                    self.flex_sensor_1 = ::std::option::Option::Some(is.read_sint32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.sensor_1 {
            my_size += ::protobuf::rt::sint32_size(1, v);
        }
        if let Some(v) = self.sensor_2 {
            my_size += ::protobuf::rt::sint32_size(2, v);
        }
        if let Some(v) = self.sensor_3 {
            my_size += ::protobuf::rt::sint32_size(3, v);
        }
        if let Some(v) = self.sensor_4 {
            my_size += ::protobuf::rt::sint32_size(4, v);
        }
        if let Some(v) = self.flex_sensor_1 {
            my_size += ::protobuf::rt::sint32_size(5, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.sensor_1 {
            os.write_sint32(1, v)?;
        }
        if let Some(v) = self.sensor_2 {
            os.write_sint32(2, v)?;
        }
        if let Some(v) = self.sensor_3 {
            os.write_sint32(3, v)?;
        }
        if let Some(v) = self.sensor_4 {
            os.write_sint32(4, v)?;
        }
        if let Some(v) = self.flex_sensor_1 {
            os.write_sint32(5, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DeviceTemp {
        DeviceTemp::new()
    }

    fn clear(&mut self) {
        self.sensor_1 = ::std::option::Option::None;
        self.sensor_2 = ::std::option::Option::None;
        self.sensor_3 = ::std::option::Option::None;
        self.sensor_4 = ::std::option::Option::None;
        self.flex_sensor_1 = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DeviceTemp {
        static instance: DeviceTemp = DeviceTemp {
            sensor_1: ::std::option::Option::None,
            sensor_2: ::std::option::Option::None,
            sensor_3: ::std::option::Option::None,
            sensor_4: ::std::option::Option::None,
            flex_sensor_1: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}
