// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `distortion.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

// @@protoc_insertion_point(message:ltpb.Distortion)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Distortion {
    // message fields
    // @@protoc_insertion_point(field:ltpb.Distortion.polynomial)
    pub polynomial: ::protobuf::MessageField<distortion::Polynomial>,
    // @@protoc_insertion_point(field:ltpb.Distortion.cra)
    pub cra: ::protobuf::MessageField<distortion::CRA>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.Distortion.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Distortion {
    fn default() -> &'a Distortion {
        <Distortion as ::protobuf::Message>::default_instance()
    }
}

impl Distortion {
    pub fn new() -> Distortion {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for Distortion {
    const NAME: &'static str = "Distortion";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.polynomial)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.cra)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.polynomial.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.cra.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.polynomial.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.cra.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Distortion {
        Distortion::new()
    }

    fn clear(&mut self) {
        self.polynomial.clear();
        self.cra.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Distortion {
        static instance: Distortion = Distortion {
            polynomial: ::protobuf::MessageField::none(),
            cra: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

/// Nested message and enums of message `Distortion`
pub mod distortion {
    // @@protoc_insertion_point(message:ltpb.Distortion.Polynomial)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct Polynomial {
        // message fields
        // @@protoc_insertion_point(field:ltpb.Distortion.Polynomial.distortion_center)
        pub distortion_center: ::protobuf::MessageField<super::super::point2f::Point2F>,
        // @@protoc_insertion_point(field:ltpb.Distortion.Polynomial.normalization)
        pub normalization: ::protobuf::MessageField<super::super::point2f::Point2F>,
        // @@protoc_insertion_point(field:ltpb.Distortion.Polynomial.coeffs)
        pub coeffs: ::std::vec::Vec<f32>,
        // @@protoc_insertion_point(field:ltpb.Distortion.Polynomial.fit_cost)
        pub fit_cost: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.Distortion.Polynomial.valid_roi)
        pub valid_roi: ::protobuf::MessageField<super::super::rectanglei::RectangleI>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.Distortion.Polynomial.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Polynomial {
        fn default() -> &'a Polynomial {
            <Polynomial as ::protobuf::Message>::default_instance()
        }
    }

    impl Polynomial {
        pub fn new() -> Polynomial {
            ::std::default::Default::default()
        }

        // optional float fit_cost = 4;

        pub fn fit_cost(&self) -> f32 {
            self.fit_cost.unwrap_or(0.)
        }

        pub fn clear_fit_cost(&mut self) {
            self.fit_cost = ::std::option::Option::None;
        }

        pub fn has_fit_cost(&self) -> bool {
            self.fit_cost.is_some()
        }

        // Param is passed by value, moved
        pub fn set_fit_cost(&mut self, v: f32) {
            self.fit_cost = ::std::option::Option::Some(v);
        }
    }

    impl ::protobuf::Message for Polynomial {
        const NAME: &'static str = "Polynomial";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.distortion_center)?;
                    },
                    18 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.normalization)?;
                    },
                    26 => {
                        is.read_repeated_packed_float_into(&mut self.coeffs)?;
                    },
                    29 => {
                        self.coeffs.push(is.read_float()?);
                    },
                    37 => {
                        self.fit_cost = ::std::option::Option::Some(is.read_float()?);
                    },
                    42 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.valid_roi)?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.distortion_center.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.normalization.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            my_size += ::protobuf::rt::vec_packed_float_size(3, &self.coeffs);
            if let Some(v) = self.fit_cost {
                my_size += 1 + 4;
            }
            if let Some(v) = self.valid_roi.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.distortion_center.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
            }
            if let Some(v) = self.normalization.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            }
            os.write_repeated_packed_float(3, &self.coeffs)?;
            if let Some(v) = self.fit_cost {
                os.write_float(4, v)?;
            }
            if let Some(v) = self.valid_roi.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Polynomial {
            Polynomial::new()
        }

        fn clear(&mut self) {
            self.distortion_center.clear();
            self.normalization.clear();
            self.coeffs.clear();
            self.fit_cost = ::std::option::Option::None;
            self.valid_roi.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Polynomial {
            static instance: Polynomial = Polynomial {
                distortion_center: ::protobuf::MessageField::none(),
                normalization: ::protobuf::MessageField::none(),
                coeffs: ::std::vec::Vec::new(),
                fit_cost: ::std::option::Option::None,
                valid_roi: ::protobuf::MessageField::none(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    // @@protoc_insertion_point(message:ltpb.Distortion.CRA)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct CRA {
        // message fields
        // @@protoc_insertion_point(field:ltpb.Distortion.CRA.distortion_center)
        pub distortion_center: ::protobuf::MessageField<super::super::point2f::Point2F>,
        // @@protoc_insertion_point(field:ltpb.Distortion.CRA.sensor_distance)
        pub sensor_distance: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.Distortion.CRA.exit_pupil_distance)
        pub exit_pupil_distance: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.Distortion.CRA.pixel_size)
        pub pixel_size: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.Distortion.CRA.cra)
        pub cra: ::std::vec::Vec<super::super::point2f::Point2F>,
        // @@protoc_insertion_point(field:ltpb.Distortion.CRA.coeffs)
        pub coeffs: ::std::vec::Vec<super::super::point2f::Point2F>,
        // @@protoc_insertion_point(field:ltpb.Distortion.CRA.fit_cost)
        pub fit_cost: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.Distortion.CRA.valid_roi)
        pub valid_roi: ::protobuf::MessageField<super::super::rectanglei::RectangleI>,
        // @@protoc_insertion_point(field:ltpb.Distortion.CRA.lens_hall_code)
        pub lens_hall_code: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.Distortion.CRA.distance_hall_ratio)
        pub distance_hall_ratio: ::std::option::Option<f32>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.Distortion.CRA.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a CRA {
        fn default() -> &'a CRA {
            <CRA as ::protobuf::Message>::default_instance()
        }
    }

    impl CRA {
        pub fn new() -> CRA {
            ::std::default::Default::default()
        }

        // optional float sensor_distance = 2;

        pub fn sensor_distance(&self) -> f32 {
            self.sensor_distance.unwrap_or(0.)
        }

        pub fn clear_sensor_distance(&mut self) {
            self.sensor_distance = ::std::option::Option::None;
        }

        pub fn has_sensor_distance(&self) -> bool {
            self.sensor_distance.is_some()
        }

        // Param is passed by value, moved
        pub fn set_sensor_distance(&mut self, v: f32) {
            self.sensor_distance = ::std::option::Option::Some(v);
        }

        // optional float exit_pupil_distance = 3;

        pub fn exit_pupil_distance(&self) -> f32 {
            self.exit_pupil_distance.unwrap_or(0.)
        }

        pub fn clear_exit_pupil_distance(&mut self) {
            self.exit_pupil_distance = ::std::option::Option::None;
        }

        pub fn has_exit_pupil_distance(&self) -> bool {
            self.exit_pupil_distance.is_some()
        }

        // Param is passed by value, moved
        pub fn set_exit_pupil_distance(&mut self, v: f32) {
            self.exit_pupil_distance = ::std::option::Option::Some(v);
        }

        // optional float pixel_size = 4;

        pub fn pixel_size(&self) -> f32 {
            self.pixel_size.unwrap_or(0.)
        }

        pub fn clear_pixel_size(&mut self) {
            self.pixel_size = ::std::option::Option::None;
        }

        pub fn has_pixel_size(&self) -> bool {
            self.pixel_size.is_some()
        }

        // Param is passed by value, moved
        pub fn set_pixel_size(&mut self, v: f32) {
            self.pixel_size = ::std::option::Option::Some(v);
        }

        // optional float fit_cost = 7;

        pub fn fit_cost(&self) -> f32 {
            self.fit_cost.unwrap_or(0.)
        }

        pub fn clear_fit_cost(&mut self) {
            self.fit_cost = ::std::option::Option::None;
        }

        pub fn has_fit_cost(&self) -> bool {
            self.fit_cost.is_some()
        }

        // Param is passed by value, moved
        pub fn set_fit_cost(&mut self, v: f32) {
            self.fit_cost = ::std::option::Option::Some(v);
        }

        // optional float lens_hall_code = 9;

        pub fn lens_hall_code(&self) -> f32 {
            self.lens_hall_code.unwrap_or(0.)
        }

        pub fn clear_lens_hall_code(&mut self) {
            self.lens_hall_code = ::std::option::Option::None;
        }

        pub fn has_lens_hall_code(&self) -> bool {
            self.lens_hall_code.is_some()
        }

        // Param is passed by value, moved
        pub fn set_lens_hall_code(&mut self, v: f32) {
            self.lens_hall_code = ::std::option::Option::Some(v);
        }

        // optional float distance_hall_ratio = 10;

        pub fn distance_hall_ratio(&self) -> f32 {
            self.distance_hall_ratio.unwrap_or(0.)
        }

        pub fn clear_distance_hall_ratio(&mut self) {
            self.distance_hall_ratio = ::std::option::Option::None;
        }

        pub fn has_distance_hall_ratio(&self) -> bool {
            self.distance_hall_ratio.is_some()
        }

        // Param is passed by value, moved
        pub fn set_distance_hall_ratio(&mut self, v: f32) {
            self.distance_hall_ratio = ::std::option::Option::Some(v);
        }
    }

    impl ::protobuf::Message for CRA {
        const NAME: &'static str = "CRA";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.distortion_center)?;
                    },
                    21 => {
                        self.sensor_distance = ::std::option::Option::Some(is.read_float()?);
                    },
                    29 => {
                        self.exit_pupil_distance = ::std::option::Option::Some(is.read_float()?);
                    },
                    37 => {
                        self.pixel_size = ::std::option::Option::Some(is.read_float()?);
                    },
                    42 => {
                        self.cra.push(is.read_message()?);
                    },
                    50 => {
                        self.coeffs.push(is.read_message()?);
                    },
                    61 => {
                        self.fit_cost = ::std::option::Option::Some(is.read_float()?);
                    },
                    66 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.valid_roi)?;
                    },
                    77 => {
                        self.lens_hall_code = ::std::option::Option::Some(is.read_float()?);
                    },
                    85 => {
                        self.distance_hall_ratio = ::std::option::Option::Some(is.read_float()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.distortion_center.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.sensor_distance {
                my_size += 1 + 4;
            }
            if let Some(v) = self.exit_pupil_distance {
                my_size += 1 + 4;
            }
            if let Some(v) = self.pixel_size {
                my_size += 1 + 4;
            }
            for value in &self.cra {
                let len = value.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            };
            for value in &self.coeffs {
                let len = value.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            };
            if let Some(v) = self.fit_cost {
                my_size += 1 + 4;
            }
            if let Some(v) = self.valid_roi.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.lens_hall_code {
                my_size += 1 + 4;
            }
            if let Some(v) = self.distance_hall_ratio {
                my_size += 1 + 4;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.distortion_center.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
            }
            if let Some(v) = self.sensor_distance {
                os.write_float(2, v)?;
            }
            if let Some(v) = self.exit_pupil_distance {
                os.write_float(3, v)?;
            }
            if let Some(v) = self.pixel_size {
                os.write_float(4, v)?;
            }
            for v in &self.cra {
                ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
            };
            for v in &self.coeffs {
                ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
            };
            if let Some(v) = self.fit_cost {
                os.write_float(7, v)?;
            }
            if let Some(v) = self.valid_roi.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
            }
            if let Some(v) = self.lens_hall_code {
                os.write_float(9, v)?;
            }
            if let Some(v) = self.distance_hall_ratio {
                os.write_float(10, v)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> CRA {
            CRA::new()
        }

        fn clear(&mut self) {
            self.distortion_center.clear();
            self.sensor_distance = ::std::option::Option::None;
            self.exit_pupil_distance = ::std::option::Option::None;
            self.pixel_size = ::std::option::Option::None;
            self.cra.clear();
            self.coeffs.clear();
            self.fit_cost = ::std::option::Option::None;
            self.valid_roi.clear();
            self.lens_hall_code = ::std::option::Option::None;
            self.distance_hall_ratio = ::std::option::Option::None;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static CRA {
            static instance: CRA = CRA {
                distortion_center: ::protobuf::MessageField::none(),
                sensor_distance: ::std::option::Option::None,
                exit_pupil_distance: ::std::option::Option::None,
                pixel_size: ::std::option::Option::None,
                cra: ::std::vec::Vec::new(),
                coeffs: ::std::vec::Vec::new(),
                fit_cost: ::std::option::Option::None,
                valid_roi: ::protobuf::MessageField::none(),
                lens_hall_code: ::std::option::Option::None,
                distance_hall_ratio: ::std::option::Option::None,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }
}
