// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `face_data.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

// @@protoc_insertion_point(message:ltpb.FaceData)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct FaceData {
    // message fields
    // @@protoc_insertion_point(field:ltpb.FaceData.id)
    pub id: ::std::option::Option<::protobuf::EnumOrUnknown<super::camera_id::CameraID>>,
    // @@protoc_insertion_point(field:ltpb.FaceData.frame_index)
    pub frame_index: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:ltpb.FaceData.rois)
    pub rois: ::std::vec::Vec<face_data::ROI>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.FaceData.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a FaceData {
    fn default() -> &'a FaceData {
        <FaceData as ::protobuf::Message>::default_instance()
    }
}

impl FaceData {
    pub fn new() -> FaceData {
        ::std::default::Default::default()
    }

    // optional .ltpb.CameraID id = 1;

    pub fn id(&self) -> super::camera_id::CameraID {
        match self.id {
            Some(e) => e.enum_value_or(super::camera_id::CameraID::A1),
            None => super::camera_id::CameraID::A1,
        }
    }

    pub fn clear_id(&mut self) {
        self.id = ::std::option::Option::None;
    }

    pub fn has_id(&self) -> bool {
        self.id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_id(&mut self, v: super::camera_id::CameraID) {
        self.id = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional uint32 frame_index = 2;

    pub fn frame_index(&self) -> u32 {
        self.frame_index.unwrap_or(0)
    }

    pub fn clear_frame_index(&mut self) {
        self.frame_index = ::std::option::Option::None;
    }

    pub fn has_frame_index(&self) -> bool {
        self.frame_index.is_some()
    }

    // Param is passed by value, moved
    pub fn set_frame_index(&mut self, v: u32) {
        self.frame_index = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for FaceData {
    const NAME: &'static str = "FaceData";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.id = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                16 => {
                    self.frame_index = ::std::option::Option::Some(is.read_uint32()?);
                },
                26 => {
                    self.rois.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.id {
            my_size += ::protobuf::rt::int32_size(1, v.value());
        }
        if let Some(v) = self.frame_index {
            my_size += ::protobuf::rt::uint32_size(2, v);
        }
        for value in &self.rois {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.id {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.frame_index {
            os.write_uint32(2, v)?;
        }
        for v in &self.rois {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> FaceData {
        FaceData::new()
    }

    fn clear(&mut self) {
        self.id = ::std::option::Option::None;
        self.frame_index = ::std::option::Option::None;
        self.rois.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static FaceData {
        static instance: FaceData = FaceData {
            id: ::std::option::Option::None,
            frame_index: ::std::option::Option::None,
            rois: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

/// Nested message and enums of message `FaceData`
pub mod face_data {
    // @@protoc_insertion_point(message:ltpb.FaceData.ROI)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct ROI {
        // message fields
        // @@protoc_insertion_point(field:ltpb.FaceData.ROI.id)
        pub id: ::std::option::Option<u32>,
        // @@protoc_insertion_point(field:ltpb.FaceData.ROI.roi)
        pub roi: ::protobuf::MessageField<super::super::rectanglei::RectangleI>,
        // @@protoc_insertion_point(field:ltpb.FaceData.ROI.confidence)
        pub confidence: ::std::option::Option<f32>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.FaceData.ROI.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a ROI {
        fn default() -> &'a ROI {
            <ROI as ::protobuf::Message>::default_instance()
        }
    }

    impl ROI {
        pub fn new() -> ROI {
            ::std::default::Default::default()
        }

        // optional uint32 id = 1;

        pub fn id(&self) -> u32 {
            self.id.unwrap_or(0)
        }

        pub fn clear_id(&mut self) {
            self.id = ::std::option::Option::None;
        }

        pub fn has_id(&self) -> bool {
            self.id.is_some()
        }

        // Param is passed by value, moved
        pub fn set_id(&mut self, v: u32) {
            self.id = ::std::option::Option::Some(v);
        }

        // optional float confidence = 3;

        pub fn confidence(&self) -> f32 {
            self.confidence.unwrap_or(0.)
        }

        pub fn clear_confidence(&mut self) {
            self.confidence = ::std::option::Option::None;
        }

        pub fn has_confidence(&self) -> bool {
            self.confidence.is_some()
        }

        // Param is passed by value, moved
        pub fn set_confidence(&mut self, v: f32) {
            self.confidence = ::std::option::Option::Some(v);
        }
    }

    impl ::protobuf::Message for ROI {
        const NAME: &'static str = "ROI";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    8 => {
                        self.id = ::std::option::Option::Some(is.read_uint32()?);
                    },
                    18 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.roi)?;
                    },
                    29 => {
                        self.confidence = ::std::option::Option::Some(is.read_float()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.id {
                my_size += ::protobuf::rt::uint32_size(1, v);
            }
            if let Some(v) = self.roi.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.confidence {
                my_size += 1 + 4;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.id {
                os.write_uint32(1, v)?;
            }
            if let Some(v) = self.roi.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            }
            if let Some(v) = self.confidence {
                os.write_float(3, v)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> ROI {
            ROI::new()
        }

        fn clear(&mut self) {
            self.id = ::std::option::Option::None;
            self.roi.clear();
            self.confidence = ::std::option::Option::None;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static ROI {
            static instance: ROI = ROI {
                id: ::std::option::Option::None,
                roi: ::protobuf::MessageField::none(),
                confidence: ::std::option::Option::None,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }
}
