// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `geometric_calibration.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

// @@protoc_insertion_point(message:ltpb.GeometricCalibration)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GeometricCalibration {
    // message fields
    // @@protoc_insertion_point(field:ltpb.GeometricCalibration.mirror_type)
    pub mirror_type: ::std::option::Option<::protobuf::EnumOrUnknown<geometric_calibration::MirrorType>>,
    // @@protoc_insertion_point(field:ltpb.GeometricCalibration.per_focus_calibration)
    pub per_focus_calibration: ::std::vec::Vec<geometric_calibration::CalibrationFocusBundle>,
    // @@protoc_insertion_point(field:ltpb.GeometricCalibration.distortion)
    pub distortion: ::protobuf::MessageField<super::distortion::Distortion>,
    // @@protoc_insertion_point(field:ltpb.GeometricCalibration.lens_hall_code_range)
    pub lens_hall_code_range: ::protobuf::MessageField<super::range2f::Range2F>,
    // @@protoc_insertion_point(field:ltpb.GeometricCalibration.focus_distance_range)
    pub focus_distance_range: ::protobuf::MessageField<super::range2f::Range2F>,
    // @@protoc_insertion_point(field:ltpb.GeometricCalibration.angle_optical_center_mapping)
    pub angle_optical_center_mapping: ::protobuf::MessageField<geometric_calibration::AngleOpticalCenterMapping>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.GeometricCalibration.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GeometricCalibration {
    fn default() -> &'a GeometricCalibration {
        <GeometricCalibration as ::protobuf::Message>::default_instance()
    }
}

impl GeometricCalibration {
    pub fn new() -> GeometricCalibration {
        ::std::default::Default::default()
    }

    // optional .ltpb.GeometricCalibration.MirrorType mirror_type = 1;

    pub fn mirror_type(&self) -> geometric_calibration::MirrorType {
        match self.mirror_type {
            Some(e) => e.enum_value_or(geometric_calibration::MirrorType::NONE),
            None => geometric_calibration::MirrorType::NONE,
        }
    }

    pub fn clear_mirror_type(&mut self) {
        self.mirror_type = ::std::option::Option::None;
    }

    pub fn has_mirror_type(&self) -> bool {
        self.mirror_type.is_some()
    }

    // Param is passed by value, moved
    pub fn set_mirror_type(&mut self, v: geometric_calibration::MirrorType) {
        self.mirror_type = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }
}

impl ::protobuf::Message for GeometricCalibration {
    const NAME: &'static str = "GeometricCalibration";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.mirror_type = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                18 => {
                    self.per_focus_calibration.push(is.read_message()?);
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.distortion)?;
                },
                34 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.lens_hall_code_range)?;
                },
                42 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.focus_distance_range)?;
                },
                50 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.angle_optical_center_mapping)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.mirror_type {
            my_size += ::protobuf::rt::int32_size(1, v.value());
        }
        for value in &self.per_focus_calibration {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.distortion.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.lens_hall_code_range.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.focus_distance_range.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.angle_optical_center_mapping.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.mirror_type {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        for v in &self.per_focus_calibration {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if let Some(v) = self.distortion.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if let Some(v) = self.lens_hall_code_range.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        }
        if let Some(v) = self.focus_distance_range.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        }
        if let Some(v) = self.angle_optical_center_mapping.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GeometricCalibration {
        GeometricCalibration::new()
    }

    fn clear(&mut self) {
        self.mirror_type = ::std::option::Option::None;
        self.per_focus_calibration.clear();
        self.distortion.clear();
        self.lens_hall_code_range.clear();
        self.focus_distance_range.clear();
        self.angle_optical_center_mapping.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GeometricCalibration {
        static instance: GeometricCalibration = GeometricCalibration {
            mirror_type: ::std::option::Option::None,
            per_focus_calibration: ::std::vec::Vec::new(),
            distortion: ::protobuf::MessageField::none(),
            lens_hall_code_range: ::protobuf::MessageField::none(),
            focus_distance_range: ::protobuf::MessageField::none(),
            angle_optical_center_mapping: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

/// Nested message and enums of message `GeometricCalibration`
pub mod geometric_calibration {
    // @@protoc_insertion_point(message:ltpb.GeometricCalibration.CalibrationFocusBundle)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct CalibrationFocusBundle {
        // message fields
        // @@protoc_insertion_point(field:ltpb.GeometricCalibration.CalibrationFocusBundle.focus_distance)
        pub focus_distance: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.GeometricCalibration.CalibrationFocusBundle.intrinsics)
        pub intrinsics: ::protobuf::MessageField<Intrinsics>,
        // @@protoc_insertion_point(field:ltpb.GeometricCalibration.CalibrationFocusBundle.extrinsics)
        pub extrinsics: ::protobuf::MessageField<Extrinsics>,
        // @@protoc_insertion_point(field:ltpb.GeometricCalibration.CalibrationFocusBundle.sensor_temp)
        pub sensor_temp: ::std::option::Option<i32>,
        // @@protoc_insertion_point(field:ltpb.GeometricCalibration.CalibrationFocusBundle.device_temp)
        pub device_temp: ::protobuf::MessageField<super::super::device_temp::DeviceTemp>,
        // @@protoc_insertion_point(field:ltpb.GeometricCalibration.CalibrationFocusBundle.focus_hall_code)
        pub focus_hall_code: ::std::option::Option<f32>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.GeometricCalibration.CalibrationFocusBundle.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a CalibrationFocusBundle {
        fn default() -> &'a CalibrationFocusBundle {
            <CalibrationFocusBundle as ::protobuf::Message>::default_instance()
        }
    }

    impl CalibrationFocusBundle {
        pub fn new() -> CalibrationFocusBundle {
            ::std::default::Default::default()
        }

        // optional float focus_distance = 1;

        pub fn focus_distance(&self) -> f32 {
            self.focus_distance.unwrap_or(0.)
        }

        pub fn clear_focus_distance(&mut self) {
            self.focus_distance = ::std::option::Option::None;
        }

        pub fn has_focus_distance(&self) -> bool {
            self.focus_distance.is_some()
        }

        // Param is passed by value, moved
        pub fn set_focus_distance(&mut self, v: f32) {
            self.focus_distance = ::std::option::Option::Some(v);
        }

        // optional sint32 sensor_temp = 4;

        pub fn sensor_temp(&self) -> i32 {
            self.sensor_temp.unwrap_or(0)
        }

        pub fn clear_sensor_temp(&mut self) {
            self.sensor_temp = ::std::option::Option::None;
        }

        pub fn has_sensor_temp(&self) -> bool {
            self.sensor_temp.is_some()
        }

        // Param is passed by value, moved
        pub fn set_sensor_temp(&mut self, v: i32) {
            self.sensor_temp = ::std::option::Option::Some(v);
        }

        // optional float focus_hall_code = 6;

        pub fn focus_hall_code(&self) -> f32 {
            self.focus_hall_code.unwrap_or(0.)
        }

        pub fn clear_focus_hall_code(&mut self) {
            self.focus_hall_code = ::std::option::Option::None;
        }

        pub fn has_focus_hall_code(&self) -> bool {
            self.focus_hall_code.is_some()
        }

        // Param is passed by value, moved
        pub fn set_focus_hall_code(&mut self, v: f32) {
            self.focus_hall_code = ::std::option::Option::Some(v);
        }
    }

    impl ::protobuf::Message for CalibrationFocusBundle {
        const NAME: &'static str = "CalibrationFocusBundle";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    13 => {
                        self.focus_distance = ::std::option::Option::Some(is.read_float()?);
                    },
                    18 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.intrinsics)?;
                    },
                    26 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.extrinsics)?;
                    },
                    32 => {
                        self.sensor_temp = ::std::option::Option::Some(is.read_sint32()?);
                    },
                    42 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.device_temp)?;
                    },
                    53 => {
                        self.focus_hall_code = ::std::option::Option::Some(is.read_float()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.focus_distance {
                my_size += 1 + 4;
            }
            if let Some(v) = self.intrinsics.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.extrinsics.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.sensor_temp {
                my_size += ::protobuf::rt::sint32_size(4, v);
            }
            if let Some(v) = self.device_temp.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.focus_hall_code {
                my_size += 1 + 4;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.focus_distance {
                os.write_float(1, v)?;
            }
            if let Some(v) = self.intrinsics.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            }
            if let Some(v) = self.extrinsics.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
            }
            if let Some(v) = self.sensor_temp {
                os.write_sint32(4, v)?;
            }
            if let Some(v) = self.device_temp.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
            }
            if let Some(v) = self.focus_hall_code {
                os.write_float(6, v)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> CalibrationFocusBundle {
            CalibrationFocusBundle::new()
        }

        fn clear(&mut self) {
            self.focus_distance = ::std::option::Option::None;
            self.intrinsics.clear();
            self.extrinsics.clear();
            self.sensor_temp = ::std::option::Option::None;
            self.device_temp.clear();
            self.focus_hall_code = ::std::option::Option::None;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static CalibrationFocusBundle {
            static instance: CalibrationFocusBundle = CalibrationFocusBundle {
                focus_distance: ::std::option::Option::None,
                intrinsics: ::protobuf::MessageField::none(),
                extrinsics: ::protobuf::MessageField::none(),
                sensor_temp: ::std::option::Option::None,
                device_temp: ::protobuf::MessageField::none(),
                focus_hall_code: ::std::option::Option::None,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    // @@protoc_insertion_point(message:ltpb.GeometricCalibration.AngleOpticalCenterMapping)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct AngleOpticalCenterMapping {
        // message fields
        // @@protoc_insertion_point(field:ltpb.GeometricCalibration.AngleOpticalCenterMapping.center_start)
        pub center_start: ::protobuf::MessageField<super::super::point2f::Point2F>,
        // @@protoc_insertion_point(field:ltpb.GeometricCalibration.AngleOpticalCenterMapping.center_end)
        pub center_end: ::protobuf::MessageField<super::super::point2f::Point2F>,
        // @@protoc_insertion_point(field:ltpb.GeometricCalibration.AngleOpticalCenterMapping.angle_offset)
        pub angle_offset: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.GeometricCalibration.AngleOpticalCenterMapping.t_scale)
        pub t_scale: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.GeometricCalibration.AngleOpticalCenterMapping.t_offset)
        pub t_offset: ::std::option::Option<f32>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.GeometricCalibration.AngleOpticalCenterMapping.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a AngleOpticalCenterMapping {
        fn default() -> &'a AngleOpticalCenterMapping {
            <AngleOpticalCenterMapping as ::protobuf::Message>::default_instance()
        }
    }

    impl AngleOpticalCenterMapping {
        pub fn new() -> AngleOpticalCenterMapping {
            ::std::default::Default::default()
        }

        // optional float angle_offset = 3;

        pub fn angle_offset(&self) -> f32 {
            self.angle_offset.unwrap_or(0.)
        }

        pub fn clear_angle_offset(&mut self) {
            self.angle_offset = ::std::option::Option::None;
        }

        pub fn has_angle_offset(&self) -> bool {
            self.angle_offset.is_some()
        }

        // Param is passed by value, moved
        pub fn set_angle_offset(&mut self, v: f32) {
            self.angle_offset = ::std::option::Option::Some(v);
        }

        // optional float t_scale = 4;

        pub fn t_scale(&self) -> f32 {
            self.t_scale.unwrap_or(0.)
        }

        pub fn clear_t_scale(&mut self) {
            self.t_scale = ::std::option::Option::None;
        }

        pub fn has_t_scale(&self) -> bool {
            self.t_scale.is_some()
        }

        // Param is passed by value, moved
        pub fn set_t_scale(&mut self, v: f32) {
            self.t_scale = ::std::option::Option::Some(v);
        }

        // optional float t_offset = 5;

        pub fn t_offset(&self) -> f32 {
            self.t_offset.unwrap_or(0.)
        }

        pub fn clear_t_offset(&mut self) {
            self.t_offset = ::std::option::Option::None;
        }

        pub fn has_t_offset(&self) -> bool {
            self.t_offset.is_some()
        }

        // Param is passed by value, moved
        pub fn set_t_offset(&mut self, v: f32) {
            self.t_offset = ::std::option::Option::Some(v);
        }
    }

    impl ::protobuf::Message for AngleOpticalCenterMapping {
        const NAME: &'static str = "AngleOpticalCenterMapping";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.center_start)?;
                    },
                    18 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.center_end)?;
                    },
                    29 => {
                        self.angle_offset = ::std::option::Option::Some(is.read_float()?);
                    },
                    37 => {
                        self.t_scale = ::std::option::Option::Some(is.read_float()?);
                    },
                    45 => {
                        self.t_offset = ::std::option::Option::Some(is.read_float()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.center_start.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.center_end.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.angle_offset {
                my_size += 1 + 4;
            }
            if let Some(v) = self.t_scale {
                my_size += 1 + 4;
            }
            if let Some(v) = self.t_offset {
                my_size += 1 + 4;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.center_start.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
            }
            if let Some(v) = self.center_end.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            }
            if let Some(v) = self.angle_offset {
                os.write_float(3, v)?;
            }
            if let Some(v) = self.t_scale {
                os.write_float(4, v)?;
            }
            if let Some(v) = self.t_offset {
                os.write_float(5, v)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> AngleOpticalCenterMapping {
            AngleOpticalCenterMapping::new()
        }

        fn clear(&mut self) {
            self.center_start.clear();
            self.center_end.clear();
            self.angle_offset = ::std::option::Option::None;
            self.t_scale = ::std::option::Option::None;
            self.t_offset = ::std::option::Option::None;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static AngleOpticalCenterMapping {
            static instance: AngleOpticalCenterMapping = AngleOpticalCenterMapping {
                center_start: ::protobuf::MessageField::none(),
                center_end: ::protobuf::MessageField::none(),
                angle_offset: ::std::option::Option::None,
                t_scale: ::std::option::Option::None,
                t_offset: ::std::option::Option::None,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    // @@protoc_insertion_point(message:ltpb.GeometricCalibration.Intrinsics)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct Intrinsics {
        // message fields
        // @@protoc_insertion_point(field:ltpb.GeometricCalibration.Intrinsics.k_mat)
        pub k_mat: ::protobuf::MessageField<super::super::matrix3x3f::Matrix3x3F>,
        // @@protoc_insertion_point(field:ltpb.GeometricCalibration.Intrinsics.rms_error)
        pub rms_error: ::std::option::Option<f32>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.GeometricCalibration.Intrinsics.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Intrinsics {
        fn default() -> &'a Intrinsics {
            <Intrinsics as ::protobuf::Message>::default_instance()
        }
    }

    impl Intrinsics {
        pub fn new() -> Intrinsics {
            ::std::default::Default::default()
        }

        // optional float rms_error = 2;

        pub fn rms_error(&self) -> f32 {
            self.rms_error.unwrap_or(0.)
        }

        pub fn clear_rms_error(&mut self) {
            self.rms_error = ::std::option::Option::None;
        }

        pub fn has_rms_error(&self) -> bool {
            self.rms_error.is_some()
        }

        // Param is passed by value, moved
        pub fn set_rms_error(&mut self, v: f32) {
            self.rms_error = ::std::option::Option::Some(v);
        }
    }

    impl ::protobuf::Message for Intrinsics {
        const NAME: &'static str = "Intrinsics";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.k_mat)?;
                    },
                    21 => {
                        self.rms_error = ::std::option::Option::Some(is.read_float()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.k_mat.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.rms_error {
                my_size += 1 + 4;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.k_mat.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
            }
            if let Some(v) = self.rms_error {
                os.write_float(2, v)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Intrinsics {
            Intrinsics::new()
        }

        fn clear(&mut self) {
            self.k_mat.clear();
            self.rms_error = ::std::option::Option::None;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Intrinsics {
            static instance: Intrinsics = Intrinsics {
                k_mat: ::protobuf::MessageField::none(),
                rms_error: ::std::option::Option::None,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    // @@protoc_insertion_point(message:ltpb.GeometricCalibration.Extrinsics)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct Extrinsics {
        // message fields
        // @@protoc_insertion_point(field:ltpb.GeometricCalibration.Extrinsics.canonical)
        pub canonical: ::protobuf::MessageField<extrinsics::CanonicalFormat>,
        // @@protoc_insertion_point(field:ltpb.GeometricCalibration.Extrinsics.moveable_mirror)
        pub moveable_mirror: ::protobuf::MessageField<extrinsics::MovableMirrorFormat>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.GeometricCalibration.Extrinsics.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Extrinsics {
        fn default() -> &'a Extrinsics {
            <Extrinsics as ::protobuf::Message>::default_instance()
        }
    }

    impl Extrinsics {
        pub fn new() -> Extrinsics {
            ::std::default::Default::default()
        }
    }

    impl ::protobuf::Message for Extrinsics {
        const NAME: &'static str = "Extrinsics";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.canonical)?;
                    },
                    18 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.moveable_mirror)?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.canonical.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.moveable_mirror.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.canonical.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
            }
            if let Some(v) = self.moveable_mirror.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Extrinsics {
            Extrinsics::new()
        }

        fn clear(&mut self) {
            self.canonical.clear();
            self.moveable_mirror.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Extrinsics {
            static instance: Extrinsics = Extrinsics {
                canonical: ::protobuf::MessageField::none(),
                moveable_mirror: ::protobuf::MessageField::none(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    /// Nested message and enums of message `Extrinsics`
    pub mod extrinsics {
        // @@protoc_insertion_point(message:ltpb.GeometricCalibration.Extrinsics.CanonicalFormat)
        #[derive(PartialEq,Clone,Default,Debug)]
        pub struct CanonicalFormat {
            // message fields
            // @@protoc_insertion_point(field:ltpb.GeometricCalibration.Extrinsics.CanonicalFormat.rotation)
            pub rotation: ::protobuf::MessageField<super::super::super::matrix3x3f::Matrix3x3F>,
            // @@protoc_insertion_point(field:ltpb.GeometricCalibration.Extrinsics.CanonicalFormat.translation)
            pub translation: ::protobuf::MessageField<super::super::super::point3f::Point3F>,
            // @@protoc_insertion_point(field:ltpb.GeometricCalibration.Extrinsics.CanonicalFormat.stereo_error)
            pub stereo_error: ::std::option::Option<f32>,
            // @@protoc_insertion_point(field:ltpb.GeometricCalibration.Extrinsics.CanonicalFormat.reprojection_error)
            pub reprojection_error: ::std::option::Option<f32>,
            // special fields
            // @@protoc_insertion_point(special_field:ltpb.GeometricCalibration.Extrinsics.CanonicalFormat.special_fields)
            pub special_fields: ::protobuf::SpecialFields,
        }

        impl<'a> ::std::default::Default for &'a CanonicalFormat {
            fn default() -> &'a CanonicalFormat {
                <CanonicalFormat as ::protobuf::Message>::default_instance()
            }
        }

        impl CanonicalFormat {
            pub fn new() -> CanonicalFormat {
                ::std::default::Default::default()
            }

            // optional float stereo_error = 3;

            pub fn stereo_error(&self) -> f32 {
                self.stereo_error.unwrap_or(0.)
            }

            pub fn clear_stereo_error(&mut self) {
                self.stereo_error = ::std::option::Option::None;
            }

            pub fn has_stereo_error(&self) -> bool {
                self.stereo_error.is_some()
            }

            // Param is passed by value, moved
            pub fn set_stereo_error(&mut self, v: f32) {
                self.stereo_error = ::std::option::Option::Some(v);
            }

            // optional float reprojection_error = 4;

            pub fn reprojection_error(&self) -> f32 {
                self.reprojection_error.unwrap_or(0.)
            }

            pub fn clear_reprojection_error(&mut self) {
                self.reprojection_error = ::std::option::Option::None;
            }

            pub fn has_reprojection_error(&self) -> bool {
                self.reprojection_error.is_some()
            }

            // Param is passed by value, moved
            pub fn set_reprojection_error(&mut self, v: f32) {
                self.reprojection_error = ::std::option::Option::Some(v);
            }
        }

        impl ::protobuf::Message for CanonicalFormat {
            const NAME: &'static str = "CanonicalFormat";

            fn is_initialized(&self) -> bool {
                true
            }

            fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
                while let Some(tag) = is.read_raw_tag_or_eof()? {
                    match tag {
                        10 => {
                            ::protobuf::rt::read_singular_message_into_field(is, &mut self.rotation)?;
                        },
                        18 => {
                            ::protobuf::rt::read_singular_message_into_field(is, &mut self.translation)?;
                        },
                        29 => {
                            self.stereo_error = ::std::option::Option::Some(is.read_float()?);
                        },
                        37 => {
                            self.reprojection_error = ::std::option::Option::Some(is.read_float()?);
                        },
                        tag => {
                            ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                        },
                    };
                }
                ::std::result::Result::Ok(())
            }

            // Compute sizes of nested messages
            #[allow(unused_variables)]
            fn compute_size(&self) -> u64 {
                let mut my_size = 0;
                if let Some(v) = self.rotation.as_ref() {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                }
                if let Some(v) = self.translation.as_ref() {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                }
                if let Some(v) = self.stereo_error {
                    my_size += 1 + 4;
                }
                if let Some(v) = self.reprojection_error {
                    my_size += 1 + 4;
                }
                my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
                self.special_fields.cached_size().set(my_size as u32);
                my_size
            }

            fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
                if let Some(v) = self.rotation.as_ref() {
                    ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
                }
                if let Some(v) = self.translation.as_ref() {
                    ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
                }
                if let Some(v) = self.stereo_error {
                    os.write_float(3, v)?;
                }
                if let Some(v) = self.reprojection_error {
                    os.write_float(4, v)?;
                }
                os.write_unknown_fields(self.special_fields.unknown_fields())?;
                ::std::result::Result::Ok(())
            }

            fn special_fields(&self) -> &::protobuf::SpecialFields {
                &self.special_fields
            }

            fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
                &mut self.special_fields
            }

            fn new() -> CanonicalFormat {
                CanonicalFormat::new()
            }

            fn clear(&mut self) {
                self.rotation.clear();
                self.translation.clear();
                self.stereo_error = ::std::option::Option::None;
                self.reprojection_error = ::std::option::Option::None;
                self.special_fields.clear();
            }

            fn default_instance() -> &'static CanonicalFormat {
                static instance: CanonicalFormat = CanonicalFormat {
                    rotation: ::protobuf::MessageField::none(),
                    translation: ::protobuf::MessageField::none(),
                    stereo_error: ::std::option::Option::None,
                    reprojection_error: ::std::option::Option::None,
                    special_fields: ::protobuf::SpecialFields::new(),
                };
                &instance
            }
        }

        // @@protoc_insertion_point(message:ltpb.GeometricCalibration.Extrinsics.MovableMirrorFormat)
        #[derive(PartialEq,Clone,Default,Debug)]
        pub struct MovableMirrorFormat {
            // message fields
            // @@protoc_insertion_point(field:ltpb.GeometricCalibration.Extrinsics.MovableMirrorFormat.mirror_system)
            pub mirror_system: ::protobuf::MessageField<super::super::super::mirror_system::MirrorSystem>,
            // @@protoc_insertion_point(field:ltpb.GeometricCalibration.Extrinsics.MovableMirrorFormat.mirror_actuator_mapping)
            pub mirror_actuator_mapping: ::protobuf::MessageField<super::super::super::mirror_system::MirrorActuatorMapping>,
            // special fields
            // @@protoc_insertion_point(special_field:ltpb.GeometricCalibration.Extrinsics.MovableMirrorFormat.special_fields)
            pub special_fields: ::protobuf::SpecialFields,
        }

        impl<'a> ::std::default::Default for &'a MovableMirrorFormat {
            fn default() -> &'a MovableMirrorFormat {
                <MovableMirrorFormat as ::protobuf::Message>::default_instance()
            }
        }

        impl MovableMirrorFormat {
            pub fn new() -> MovableMirrorFormat {
                ::std::default::Default::default()
            }
        }

        impl ::protobuf::Message for MovableMirrorFormat {
            const NAME: &'static str = "MovableMirrorFormat";

            fn is_initialized(&self) -> bool {
                true
            }

            fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
                while let Some(tag) = is.read_raw_tag_or_eof()? {
                    match tag {
                        10 => {
                            ::protobuf::rt::read_singular_message_into_field(is, &mut self.mirror_system)?;
                        },
                        18 => {
                            ::protobuf::rt::read_singular_message_into_field(is, &mut self.mirror_actuator_mapping)?;
                        },
                        tag => {
                            ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                        },
                    };
                }
                ::std::result::Result::Ok(())
            }

            // Compute sizes of nested messages
            #[allow(unused_variables)]
            fn compute_size(&self) -> u64 {
                let mut my_size = 0;
                if let Some(v) = self.mirror_system.as_ref() {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                }
                if let Some(v) = self.mirror_actuator_mapping.as_ref() {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                }
                my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
                self.special_fields.cached_size().set(my_size as u32);
                my_size
            }

            fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
                if let Some(v) = self.mirror_system.as_ref() {
                    ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
                }
                if let Some(v) = self.mirror_actuator_mapping.as_ref() {
                    ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
                }
                os.write_unknown_fields(self.special_fields.unknown_fields())?;
                ::std::result::Result::Ok(())
            }

            fn special_fields(&self) -> &::protobuf::SpecialFields {
                &self.special_fields
            }

            fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
                &mut self.special_fields
            }

            fn new() -> MovableMirrorFormat {
                MovableMirrorFormat::new()
            }

            fn clear(&mut self) {
                self.mirror_system.clear();
                self.mirror_actuator_mapping.clear();
                self.special_fields.clear();
            }

            fn default_instance() -> &'static MovableMirrorFormat {
                static instance: MovableMirrorFormat = MovableMirrorFormat {
                    mirror_system: ::protobuf::MessageField::none(),
                    mirror_actuator_mapping: ::protobuf::MessageField::none(),
                    special_fields: ::protobuf::SpecialFields::new(),
                };
                &instance
            }
        }
    }

    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.GeometricCalibration.MirrorType)
    pub enum MirrorType {
        // @@protoc_insertion_point(enum_value:ltpb.GeometricCalibration.MirrorType.NONE)
        NONE = 0,
        // @@protoc_insertion_point(enum_value:ltpb.GeometricCalibration.MirrorType.GLUED)
        GLUED = 1,
        // @@protoc_insertion_point(enum_value:ltpb.GeometricCalibration.MirrorType.MOVABLE)
        MOVABLE = 2,
    }

    impl ::protobuf::Enum for MirrorType {
        const NAME: &'static str = "MirrorType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<MirrorType> {
            match value {
                0 => ::std::option::Option::Some(MirrorType::NONE),
                1 => ::std::option::Option::Some(MirrorType::GLUED),
                2 => ::std::option::Option::Some(MirrorType::MOVABLE),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<MirrorType> {
            match str {
                "NONE" => ::std::option::Option::Some(MirrorType::NONE),
                "GLUED" => ::std::option::Option::Some(MirrorType::GLUED),
                "MOVABLE" => ::std::option::Option::Some(MirrorType::MOVABLE),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [MirrorType] = &[
            MirrorType::NONE,
            MirrorType::GLUED,
            MirrorType::MOVABLE,
        ];
    }

    impl ::std::default::Default for MirrorType {
        fn default() -> Self {
            MirrorType::NONE
        }
    }

}
