// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `gps_data.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

// @@protoc_insertion_point(message:ltpb.GPSData)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GPSData {
    // message fields
    // @@protoc_insertion_point(field:ltpb.GPSData.latitude)
    pub latitude: ::std::option::Option<f64>,
    // @@protoc_insertion_point(field:ltpb.GPSData.longitude)
    pub longitude: ::std::option::Option<f64>,
    // @@protoc_insertion_point(field:ltpb.GPSData.timestamp)
    pub timestamp: ::std::option::Option<u64>,
    // @@protoc_insertion_point(field:ltpb.GPSData.dop)
    pub dop: ::std::option::Option<f64>,
    // @@protoc_insertion_point(field:ltpb.GPSData.track)
    pub track: ::protobuf::MessageField<gpsdata::Track>,
    // @@protoc_insertion_point(field:ltpb.GPSData.heading)
    pub heading: ::protobuf::MessageField<gpsdata::Heading>,
    // @@protoc_insertion_point(field:ltpb.GPSData.altitude)
    pub altitude: ::protobuf::MessageField<gpsdata::Altitude>,
    // @@protoc_insertion_point(field:ltpb.GPSData.speed)
    pub speed: ::std::option::Option<f64>,
    // @@protoc_insertion_point(field:ltpb.GPSData.processing_method)
    pub processing_method: ::std::option::Option<::protobuf::EnumOrUnknown<gpsdata::ProcessingMethod>>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.GPSData.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GPSData {
    fn default() -> &'a GPSData {
        <GPSData as ::protobuf::Message>::default_instance()
    }
}

impl GPSData {
    pub fn new() -> GPSData {
        ::std::default::Default::default()
    }

    // optional double latitude = 1;

    pub fn latitude(&self) -> f64 {
        self.latitude.unwrap_or(0.)
    }

    pub fn clear_latitude(&mut self) {
        self.latitude = ::std::option::Option::None;
    }

    pub fn has_latitude(&self) -> bool {
        self.latitude.is_some()
    }

    // Param is passed by value, moved
    pub fn set_latitude(&mut self, v: f64) {
        self.latitude = ::std::option::Option::Some(v);
    }

    // optional double longitude = 2;

    pub fn longitude(&self) -> f64 {
        self.longitude.unwrap_or(0.)
    }

    pub fn clear_longitude(&mut self) {
        self.longitude = ::std::option::Option::None;
    }

    pub fn has_longitude(&self) -> bool {
        self.longitude.is_some()
    }

    // Param is passed by value, moved
    pub fn set_longitude(&mut self, v: f64) {
        self.longitude = ::std::option::Option::Some(v);
    }

    // optional uint64 timestamp = 3;

    pub fn timestamp(&self) -> u64 {
        self.timestamp.unwrap_or(0)
    }

    pub fn clear_timestamp(&mut self) {
        self.timestamp = ::std::option::Option::None;
    }

    pub fn has_timestamp(&self) -> bool {
        self.timestamp.is_some()
    }

    // Param is passed by value, moved
    pub fn set_timestamp(&mut self, v: u64) {
        self.timestamp = ::std::option::Option::Some(v);
    }

    // optional double dop = 4;

    pub fn dop(&self) -> f64 {
        self.dop.unwrap_or(0.)
    }

    pub fn clear_dop(&mut self) {
        self.dop = ::std::option::Option::None;
    }

    pub fn has_dop(&self) -> bool {
        self.dop.is_some()
    }

    // Param is passed by value, moved
    pub fn set_dop(&mut self, v: f64) {
        self.dop = ::std::option::Option::Some(v);
    }

    // optional double speed = 8;

    pub fn speed(&self) -> f64 {
        self.speed.unwrap_or(0.)
    }

    pub fn clear_speed(&mut self) {
        self.speed = ::std::option::Option::None;
    }

    pub fn has_speed(&self) -> bool {
        self.speed.is_some()
    }

    // Param is passed by value, moved
    pub fn set_speed(&mut self, v: f64) {
        self.speed = ::std::option::Option::Some(v);
    }

    // optional .ltpb.GPSData.ProcessingMethod processing_method = 9;

    pub fn processing_method(&self) -> gpsdata::ProcessingMethod {
        match self.processing_method {
            Some(e) => e.enum_value_or(gpsdata::ProcessingMethod::PROCESSING_METHOD_UNKNOWN),
            None => gpsdata::ProcessingMethod::PROCESSING_METHOD_UNKNOWN,
        }
    }

    pub fn clear_processing_method(&mut self) {
        self.processing_method = ::std::option::Option::None;
    }

    pub fn has_processing_method(&self) -> bool {
        self.processing_method.is_some()
    }

    // Param is passed by value, moved
    pub fn set_processing_method(&mut self, v: gpsdata::ProcessingMethod) {
        self.processing_method = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }
}

impl ::protobuf::Message for GPSData {
    const NAME: &'static str = "GPSData";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                9 => {
                    self.latitude = ::std::option::Option::Some(is.read_double()?);
                },
                17 => {
                    self.longitude = ::std::option::Option::Some(is.read_double()?);
                },
                24 => {
                    self.timestamp = ::std::option::Option::Some(is.read_uint64()?);
                },
                33 => {
                    self.dop = ::std::option::Option::Some(is.read_double()?);
                },
                42 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.track)?;
                },
                50 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.heading)?;
                },
                58 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.altitude)?;
                },
                65 => {
                    self.speed = ::std::option::Option::Some(is.read_double()?);
                },
                72 => {
                    self.processing_method = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.latitude {
            my_size += 1 + 8;
        }
        if let Some(v) = self.longitude {
            my_size += 1 + 8;
        }
        if let Some(v) = self.timestamp {
            my_size += ::protobuf::rt::uint64_size(3, v);
        }
        if let Some(v) = self.dop {
            my_size += 1 + 8;
        }
        if let Some(v) = self.track.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.heading.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.altitude.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.speed {
            my_size += 1 + 8;
        }
        if let Some(v) = self.processing_method {
            my_size += ::protobuf::rt::int32_size(9, v.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.latitude {
            os.write_double(1, v)?;
        }
        if let Some(v) = self.longitude {
            os.write_double(2, v)?;
        }
        if let Some(v) = self.timestamp {
            os.write_uint64(3, v)?;
        }
        if let Some(v) = self.dop {
            os.write_double(4, v)?;
        }
        if let Some(v) = self.track.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        }
        if let Some(v) = self.heading.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        }
        if let Some(v) = self.altitude.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
        }
        if let Some(v) = self.speed {
            os.write_double(8, v)?;
        }
        if let Some(v) = self.processing_method {
            os.write_enum(9, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GPSData {
        GPSData::new()
    }

    fn clear(&mut self) {
        self.latitude = ::std::option::Option::None;
        self.longitude = ::std::option::Option::None;
        self.timestamp = ::std::option::Option::None;
        self.dop = ::std::option::Option::None;
        self.track.clear();
        self.heading.clear();
        self.altitude.clear();
        self.speed = ::std::option::Option::None;
        self.processing_method = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GPSData {
        static instance: GPSData = GPSData {
            latitude: ::std::option::Option::None,
            longitude: ::std::option::Option::None,
            timestamp: ::std::option::Option::None,
            dop: ::std::option::Option::None,
            track: ::protobuf::MessageField::none(),
            heading: ::protobuf::MessageField::none(),
            altitude: ::protobuf::MessageField::none(),
            speed: ::std::option::Option::None,
            processing_method: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

/// Nested message and enums of message `GPSData`
pub mod gpsdata {
    // @@protoc_insertion_point(message:ltpb.GPSData.Track)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct Track {
        // message fields
        // @@protoc_insertion_point(field:ltpb.GPSData.Track.value)
        pub value: ::std::option::Option<f64>,
        // @@protoc_insertion_point(field:ltpb.GPSData.Track.ref)
        pub ref_: ::std::option::Option<::protobuf::EnumOrUnknown<ReferenceNorth>>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.GPSData.Track.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Track {
        fn default() -> &'a Track {
            <Track as ::protobuf::Message>::default_instance()
        }
    }

    impl Track {
        pub fn new() -> Track {
            ::std::default::Default::default()
        }

        // optional double value = 1;

        pub fn value(&self) -> f64 {
            self.value.unwrap_or(0.)
        }

        pub fn clear_value(&mut self) {
            self.value = ::std::option::Option::None;
        }

        pub fn has_value(&self) -> bool {
            self.value.is_some()
        }

        // Param is passed by value, moved
        pub fn set_value(&mut self, v: f64) {
            self.value = ::std::option::Option::Some(v);
        }

        // optional .ltpb.GPSData.ReferenceNorth ref = 2;

        pub fn ref_(&self) -> ReferenceNorth {
            match self.ref_ {
                Some(e) => e.enum_value_or(ReferenceNorth::REFERENCE_NORTH_MAGNETIC),
                None => ReferenceNorth::REFERENCE_NORTH_MAGNETIC,
            }
        }

        pub fn clear_ref_(&mut self) {
            self.ref_ = ::std::option::Option::None;
        }

        pub fn has_ref(&self) -> bool {
            self.ref_.is_some()
        }

        // Param is passed by value, moved
        pub fn set_ref(&mut self, v: ReferenceNorth) {
            self.ref_ = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
        }
    }

    impl ::protobuf::Message for Track {
        const NAME: &'static str = "Track";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    9 => {
                        self.value = ::std::option::Option::Some(is.read_double()?);
                    },
                    16 => {
                        self.ref_ = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.value {
                my_size += 1 + 8;
            }
            if let Some(v) = self.ref_ {
                my_size += ::protobuf::rt::int32_size(2, v.value());
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.value {
                os.write_double(1, v)?;
            }
            if let Some(v) = self.ref_ {
                os.write_enum(2, ::protobuf::EnumOrUnknown::value(&v))?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Track {
            Track::new()
        }

        fn clear(&mut self) {
            self.value = ::std::option::Option::None;
            self.ref_ = ::std::option::Option::None;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Track {
            static instance: Track = Track {
                value: ::std::option::Option::None,
                ref_: ::std::option::Option::None,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    // @@protoc_insertion_point(message:ltpb.GPSData.Heading)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct Heading {
        // message fields
        // @@protoc_insertion_point(field:ltpb.GPSData.Heading.value)
        pub value: ::std::option::Option<f64>,
        // @@protoc_insertion_point(field:ltpb.GPSData.Heading.ref)
        pub ref_: ::std::option::Option<::protobuf::EnumOrUnknown<ReferenceNorth>>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.GPSData.Heading.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Heading {
        fn default() -> &'a Heading {
            <Heading as ::protobuf::Message>::default_instance()
        }
    }

    impl Heading {
        pub fn new() -> Heading {
            ::std::default::Default::default()
        }

        // optional double value = 1;

        pub fn value(&self) -> f64 {
            self.value.unwrap_or(0.)
        }

        pub fn clear_value(&mut self) {
            self.value = ::std::option::Option::None;
        }

        pub fn has_value(&self) -> bool {
            self.value.is_some()
        }

        // Param is passed by value, moved
        pub fn set_value(&mut self, v: f64) {
            self.value = ::std::option::Option::Some(v);
        }

        // optional .ltpb.GPSData.ReferenceNorth ref = 2;

        pub fn ref_(&self) -> ReferenceNorth {
            match self.ref_ {
                Some(e) => e.enum_value_or(ReferenceNorth::REFERENCE_NORTH_MAGNETIC),
                None => ReferenceNorth::REFERENCE_NORTH_MAGNETIC,
            }
        }

        pub fn clear_ref_(&mut self) {
            self.ref_ = ::std::option::Option::None;
        }

        pub fn has_ref(&self) -> bool {
            self.ref_.is_some()
        }

        // Param is passed by value, moved
        pub fn set_ref(&mut self, v: ReferenceNorth) {
            self.ref_ = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
        }
    }

    impl ::protobuf::Message for Heading {
        const NAME: &'static str = "Heading";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    9 => {
                        self.value = ::std::option::Option::Some(is.read_double()?);
                    },
                    16 => {
                        self.ref_ = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.value {
                my_size += 1 + 8;
            }
            if let Some(v) = self.ref_ {
                my_size += ::protobuf::rt::int32_size(2, v.value());
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.value {
                os.write_double(1, v)?;
            }
            if let Some(v) = self.ref_ {
                os.write_enum(2, ::protobuf::EnumOrUnknown::value(&v))?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Heading {
            Heading::new()
        }

        fn clear(&mut self) {
            self.value = ::std::option::Option::None;
            self.ref_ = ::std::option::Option::None;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Heading {
            static instance: Heading = Heading {
                value: ::std::option::Option::None,
                ref_: ::std::option::Option::None,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    // @@protoc_insertion_point(message:ltpb.GPSData.Altitude)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct Altitude {
        // message fields
        // @@protoc_insertion_point(field:ltpb.GPSData.Altitude.value)
        pub value: ::std::option::Option<f64>,
        // @@protoc_insertion_point(field:ltpb.GPSData.Altitude.ref)
        pub ref_: ::std::option::Option<::protobuf::EnumOrUnknown<ReferenceAltitude>>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.GPSData.Altitude.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Altitude {
        fn default() -> &'a Altitude {
            <Altitude as ::protobuf::Message>::default_instance()
        }
    }

    impl Altitude {
        pub fn new() -> Altitude {
            ::std::default::Default::default()
        }

        // optional double value = 1;

        pub fn value(&self) -> f64 {
            self.value.unwrap_or(0.)
        }

        pub fn clear_value(&mut self) {
            self.value = ::std::option::Option::None;
        }

        pub fn has_value(&self) -> bool {
            self.value.is_some()
        }

        // Param is passed by value, moved
        pub fn set_value(&mut self, v: f64) {
            self.value = ::std::option::Option::Some(v);
        }

        // optional .ltpb.GPSData.ReferenceAltitude ref = 2;

        pub fn ref_(&self) -> ReferenceAltitude {
            match self.ref_ {
                Some(e) => e.enum_value_or(ReferenceAltitude::REFERENCE_ALTITUDE_SEA_LEVEL),
                None => ReferenceAltitude::REFERENCE_ALTITUDE_SEA_LEVEL,
            }
        }

        pub fn clear_ref_(&mut self) {
            self.ref_ = ::std::option::Option::None;
        }

        pub fn has_ref(&self) -> bool {
            self.ref_.is_some()
        }

        // Param is passed by value, moved
        pub fn set_ref(&mut self, v: ReferenceAltitude) {
            self.ref_ = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
        }
    }

    impl ::protobuf::Message for Altitude {
        const NAME: &'static str = "Altitude";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    9 => {
                        self.value = ::std::option::Option::Some(is.read_double()?);
                    },
                    16 => {
                        self.ref_ = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.value {
                my_size += 1 + 8;
            }
            if let Some(v) = self.ref_ {
                my_size += ::protobuf::rt::int32_size(2, v.value());
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.value {
                os.write_double(1, v)?;
            }
            if let Some(v) = self.ref_ {
                os.write_enum(2, ::protobuf::EnumOrUnknown::value(&v))?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Altitude {
            Altitude::new()
        }

        fn clear(&mut self) {
            self.value = ::std::option::Option::None;
            self.ref_ = ::std::option::Option::None;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Altitude {
            static instance: Altitude = Altitude {
                value: ::std::option::Option::None,
                ref_: ::std::option::Option::None,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.GPSData.ProcessingMethod)
    pub enum ProcessingMethod {
        // @@protoc_insertion_point(enum_value:ltpb.GPSData.ProcessingMethod.PROCESSING_METHOD_UNKNOWN)
        PROCESSING_METHOD_UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:ltpb.GPSData.ProcessingMethod.PROCESSING_METHOD_GPS)
        PROCESSING_METHOD_GPS = 1,
        // @@protoc_insertion_point(enum_value:ltpb.GPSData.ProcessingMethod.PROCESSING_METHOD_CELLID)
        PROCESSING_METHOD_CELLID = 2,
        // @@protoc_insertion_point(enum_value:ltpb.GPSData.ProcessingMethod.PROCESSING_METHOD_WLAN)
        PROCESSING_METHOD_WLAN = 3,
        // @@protoc_insertion_point(enum_value:ltpb.GPSData.ProcessingMethod.PROCESSING_METHOD_MANUAL)
        PROCESSING_METHOD_MANUAL = 4,
        // @@protoc_insertion_point(enum_value:ltpb.GPSData.ProcessingMethod.PROCESSING_METHOD_FUSED)
        PROCESSING_METHOD_FUSED = 5,
    }

    impl ::protobuf::Enum for ProcessingMethod {
        const NAME: &'static str = "ProcessingMethod";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<ProcessingMethod> {
            match value {
                0 => ::std::option::Option::Some(ProcessingMethod::PROCESSING_METHOD_UNKNOWN),
                1 => ::std::option::Option::Some(ProcessingMethod::PROCESSING_METHOD_GPS),
                2 => ::std::option::Option::Some(ProcessingMethod::PROCESSING_METHOD_CELLID),
                3 => ::std::option::Option::Some(ProcessingMethod::PROCESSING_METHOD_WLAN),
                4 => ::std::option::Option::Some(ProcessingMethod::PROCESSING_METHOD_MANUAL),
                5 => ::std::option::Option::Some(ProcessingMethod::PROCESSING_METHOD_FUSED),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<ProcessingMethod> {
            match str {
                "PROCESSING_METHOD_UNKNOWN" => ::std::option::Option::Some(ProcessingMethod::PROCESSING_METHOD_UNKNOWN),
                "PROCESSING_METHOD_GPS" => ::std::option::Option::Some(ProcessingMethod::PROCESSING_METHOD_GPS),
                "PROCESSING_METHOD_CELLID" => ::std::option::Option::Some(ProcessingMethod::PROCESSING_METHOD_CELLID),
                "PROCESSING_METHOD_WLAN" => ::std::option::Option::Some(ProcessingMethod::PROCESSING_METHOD_WLAN),
                "PROCESSING_METHOD_MANUAL" => ::std::option::Option::Some(ProcessingMethod::PROCESSING_METHOD_MANUAL),
                "PROCESSING_METHOD_FUSED" => ::std::option::Option::Some(ProcessingMethod::PROCESSING_METHOD_FUSED),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [ProcessingMethod] = &[
            ProcessingMethod::PROCESSING_METHOD_UNKNOWN,
            ProcessingMethod::PROCESSING_METHOD_GPS,
            ProcessingMethod::PROCESSING_METHOD_CELLID,
            ProcessingMethod::PROCESSING_METHOD_WLAN,
            ProcessingMethod::PROCESSING_METHOD_MANUAL,
            ProcessingMethod::PROCESSING_METHOD_FUSED,
        ];
    }

    impl ::std::default::Default for ProcessingMethod {
        fn default() -> Self {
            ProcessingMethod::PROCESSING_METHOD_UNKNOWN
        }
    }


    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.GPSData.ReferenceNorth)
    pub enum ReferenceNorth {
        // @@protoc_insertion_point(enum_value:ltpb.GPSData.ReferenceNorth.REFERENCE_NORTH_MAGNETIC)
        REFERENCE_NORTH_MAGNETIC = 0,
        // @@protoc_insertion_point(enum_value:ltpb.GPSData.ReferenceNorth.REFERENCE_NORTH_TRUE)
        REFERENCE_NORTH_TRUE = 1,
    }

    impl ::protobuf::Enum for ReferenceNorth {
        const NAME: &'static str = "ReferenceNorth";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<ReferenceNorth> {
            match value {
                0 => ::std::option::Option::Some(ReferenceNorth::REFERENCE_NORTH_MAGNETIC),
                1 => ::std::option::Option::Some(ReferenceNorth::REFERENCE_NORTH_TRUE),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<ReferenceNorth> {
            match str {
                "REFERENCE_NORTH_MAGNETIC" => ::std::option::Option::Some(ReferenceNorth::REFERENCE_NORTH_MAGNETIC),
                "REFERENCE_NORTH_TRUE" => ::std::option::Option::Some(ReferenceNorth::REFERENCE_NORTH_TRUE),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [ReferenceNorth] = &[
            ReferenceNorth::REFERENCE_NORTH_MAGNETIC,
            ReferenceNorth::REFERENCE_NORTH_TRUE,
        ];
    }

    impl ::std::default::Default for ReferenceNorth {
        fn default() -> Self {
            ReferenceNorth::REFERENCE_NORTH_MAGNETIC
        }
    }


    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.GPSData.ReferenceAltitude)
    pub enum ReferenceAltitude {
        // @@protoc_insertion_point(enum_value:ltpb.GPSData.ReferenceAltitude.REFERENCE_ALTITUDE_SEA_LEVEL)
        REFERENCE_ALTITUDE_SEA_LEVEL = 0,
    }

    impl ::protobuf::Enum for ReferenceAltitude {
        const NAME: &'static str = "ReferenceAltitude";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<ReferenceAltitude> {
            match value {
                0 => ::std::option::Option::Some(ReferenceAltitude::REFERENCE_ALTITUDE_SEA_LEVEL),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<ReferenceAltitude> {
            match str {
                "REFERENCE_ALTITUDE_SEA_LEVEL" => ::std::option::Option::Some(ReferenceAltitude::REFERENCE_ALTITUDE_SEA_LEVEL),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [ReferenceAltitude] = &[
            ReferenceAltitude::REFERENCE_ALTITUDE_SEA_LEVEL,
        ];
    }

    impl ::std::default::Default for ReferenceAltitude {
        fn default() -> Self {
            ReferenceAltitude::REFERENCE_ALTITUDE_SEA_LEVEL
        }
    }

}
