// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `hot_pixel_map.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

// @@protoc_insertion_point(message:ltpb.HotPixelMap)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct HotPixelMap {
    // message fields
    // @@protoc_insertion_point(field:ltpb.HotPixelMap.data)
    pub data: ::std::vec::Vec<hot_pixel_map::HotPixelMeasurement>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.HotPixelMap.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a HotPixelMap {
    fn default() -> &'a HotPixelMap {
        <HotPixelMap as ::protobuf::Message>::default_instance()
    }
}

impl HotPixelMap {
    pub fn new() -> HotPixelMap {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for HotPixelMap {
    const NAME: &'static str = "HotPixelMap";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.data.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.data {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.data {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> HotPixelMap {
        HotPixelMap::new()
    }

    fn clear(&mut self) {
        self.data.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static HotPixelMap {
        static instance: HotPixelMap = HotPixelMap {
            data: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

/// Nested message and enums of message `HotPixelMap`
pub mod hot_pixel_map {
    // @@protoc_insertion_point(message:ltpb.HotPixelMap.HotPixelMeasurement)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct HotPixelMeasurement {
        // message fields
        // @@protoc_insertion_point(field:ltpb.HotPixelMap.HotPixelMeasurement.data_offset)
        pub data_offset: ::std::option::Option<u64>,
        // @@protoc_insertion_point(field:ltpb.HotPixelMap.HotPixelMeasurement.data_size)
        pub data_size: ::std::option::Option<u32>,
        // @@protoc_insertion_point(field:ltpb.HotPixelMap.HotPixelMeasurement.data_exposure)
        pub data_exposure: ::std::option::Option<u32>,
        // @@protoc_insertion_point(field:ltpb.HotPixelMap.HotPixelMeasurement.sensor_temparature)
        pub sensor_temparature: ::std::option::Option<i32>,
        // @@protoc_insertion_point(field:ltpb.HotPixelMap.HotPixelMeasurement.sensor_gain)
        pub sensor_gain: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.HotPixelMap.HotPixelMeasurement.pixel_variance)
        pub pixel_variance: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.HotPixelMap.HotPixelMeasurement.threshold)
        pub threshold: ::std::option::Option<f32>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.HotPixelMap.HotPixelMeasurement.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a HotPixelMeasurement {
        fn default() -> &'a HotPixelMeasurement {
            <HotPixelMeasurement as ::protobuf::Message>::default_instance()
        }
    }

    impl HotPixelMeasurement {
        pub fn new() -> HotPixelMeasurement {
            ::std::default::Default::default()
        }

        // optional uint64 data_offset = 1;

        pub fn data_offset(&self) -> u64 {
            self.data_offset.unwrap_or(0)
        }

        pub fn clear_data_offset(&mut self) {
            self.data_offset = ::std::option::Option::None;
        }

        pub fn has_data_offset(&self) -> bool {
            self.data_offset.is_some()
        }

        // Param is passed by value, moved
        pub fn set_data_offset(&mut self, v: u64) {
            self.data_offset = ::std::option::Option::Some(v);
        }

        // optional uint32 data_size = 2;

        pub fn data_size(&self) -> u32 {
            self.data_size.unwrap_or(0)
        }

        pub fn clear_data_size(&mut self) {
            self.data_size = ::std::option::Option::None;
        }

        pub fn has_data_size(&self) -> bool {
            self.data_size.is_some()
        }

        // Param is passed by value, moved
        pub fn set_data_size(&mut self, v: u32) {
            self.data_size = ::std::option::Option::Some(v);
        }

        // optional uint32 data_exposure = 3;

        pub fn data_exposure(&self) -> u32 {
            self.data_exposure.unwrap_or(0)
        }

        pub fn clear_data_exposure(&mut self) {
            self.data_exposure = ::std::option::Option::None;
        }

        pub fn has_data_exposure(&self) -> bool {
            self.data_exposure.is_some()
        }

        // Param is passed by value, moved
        pub fn set_data_exposure(&mut self, v: u32) {
            self.data_exposure = ::std::option::Option::Some(v);
        }

        // optional int32 sensor_temparature = 4;

        pub fn sensor_temparature(&self) -> i32 {
            self.sensor_temparature.unwrap_or(0)
        }

        pub fn clear_sensor_temparature(&mut self) {
            self.sensor_temparature = ::std::option::Option::None;
        }

        pub fn has_sensor_temparature(&self) -> bool {
            self.sensor_temparature.is_some()
        }

        // Param is passed by value, moved
        pub fn set_sensor_temparature(&mut self, v: i32) {
            self.sensor_temparature = ::std::option::Option::Some(v);
        }

        // optional float sensor_gain = 5;

        pub fn sensor_gain(&self) -> f32 {
            self.sensor_gain.unwrap_or(0.)
        }

        pub fn clear_sensor_gain(&mut self) {
            self.sensor_gain = ::std::option::Option::None;
        }

        pub fn has_sensor_gain(&self) -> bool {
            self.sensor_gain.is_some()
        }

        // Param is passed by value, moved
        pub fn set_sensor_gain(&mut self, v: f32) {
            self.sensor_gain = ::std::option::Option::Some(v);
        }

        // optional float pixel_variance = 6;

        pub fn pixel_variance(&self) -> f32 {
            self.pixel_variance.unwrap_or(0.)
        }

        pub fn clear_pixel_variance(&mut self) {
            self.pixel_variance = ::std::option::Option::None;
        }

        pub fn has_pixel_variance(&self) -> bool {
            self.pixel_variance.is_some()
        }

        // Param is passed by value, moved
        pub fn set_pixel_variance(&mut self, v: f32) {
            self.pixel_variance = ::std::option::Option::Some(v);
        }

        // optional float threshold = 7;

        pub fn threshold(&self) -> f32 {
            self.threshold.unwrap_or(0.)
        }

        pub fn clear_threshold(&mut self) {
            self.threshold = ::std::option::Option::None;
        }

        pub fn has_threshold(&self) -> bool {
            self.threshold.is_some()
        }

        // Param is passed by value, moved
        pub fn set_threshold(&mut self, v: f32) {
            self.threshold = ::std::option::Option::Some(v);
        }
    }

    impl ::protobuf::Message for HotPixelMeasurement {
        const NAME: &'static str = "HotPixelMeasurement";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    8 => {
                        self.data_offset = ::std::option::Option::Some(is.read_uint64()?);
                    },
                    16 => {
                        self.data_size = ::std::option::Option::Some(is.read_uint32()?);
                    },
                    24 => {
                        self.data_exposure = ::std::option::Option::Some(is.read_uint32()?);
                    },
                    32 => {
                        self.sensor_temparature = ::std::option::Option::Some(is.read_int32()?);
                    },
                    45 => {
                        self.sensor_gain = ::std::option::Option::Some(is.read_float()?);
                    },
                    53 => {
                        self.pixel_variance = ::std::option::Option::Some(is.read_float()?);
                    },
                    61 => {
                        self.threshold = ::std::option::Option::Some(is.read_float()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.data_offset {
                my_size += ::protobuf::rt::uint64_size(1, v);
            }
            if let Some(v) = self.data_size {
                my_size += ::protobuf::rt::uint32_size(2, v);
            }
            if let Some(v) = self.data_exposure {
                my_size += ::protobuf::rt::uint32_size(3, v);
            }
            if let Some(v) = self.sensor_temparature {
                my_size += ::protobuf::rt::int32_size(4, v);
            }
            if let Some(v) = self.sensor_gain {
                my_size += 1 + 4;
            }
            if let Some(v) = self.pixel_variance {
                my_size += 1 + 4;
            }
            if let Some(v) = self.threshold {
                my_size += 1 + 4;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.data_offset {
                os.write_uint64(1, v)?;
            }
            if let Some(v) = self.data_size {
                os.write_uint32(2, v)?;
            }
            if let Some(v) = self.data_exposure {
                os.write_uint32(3, v)?;
            }
            if let Some(v) = self.sensor_temparature {
                os.write_int32(4, v)?;
            }
            if let Some(v) = self.sensor_gain {
                os.write_float(5, v)?;
            }
            if let Some(v) = self.pixel_variance {
                os.write_float(6, v)?;
            }
            if let Some(v) = self.threshold {
                os.write_float(7, v)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> HotPixelMeasurement {
            HotPixelMeasurement::new()
        }

        fn clear(&mut self) {
            self.data_offset = ::std::option::Option::None;
            self.data_size = ::std::option::Option::None;
            self.data_exposure = ::std::option::Option::None;
            self.sensor_temparature = ::std::option::Option::None;
            self.sensor_gain = ::std::option::Option::None;
            self.pixel_variance = ::std::option::Option::None;
            self.threshold = ::std::option::Option::None;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static HotPixelMeasurement {
            static instance: HotPixelMeasurement = HotPixelMeasurement {
                data_offset: ::std::option::Option::None,
                data_size: ::std::option::Option::None,
                data_exposure: ::std::option::Option::None,
                sensor_temparature: ::std::option::Option::None,
                sensor_gain: ::std::option::Option::None,
                pixel_variance: ::std::option::Option::None,
                threshold: ::std::option::Option::None,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }
}
