// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `hw_info.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

// @@protoc_insertion_point(message:ltpb.CameraModuleHwInfo)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CameraModuleHwInfo {
    // message fields
    // @@protoc_insertion_point(field:ltpb.CameraModuleHwInfo.id)
    pub id: ::std::option::Option<::protobuf::EnumOrUnknown<super::camera_id::CameraID>>,
    // @@protoc_insertion_point(field:ltpb.CameraModuleHwInfo.sensor)
    pub sensor: ::std::option::Option<::protobuf::EnumOrUnknown<super::sensor_type::SensorType>>,
    // @@protoc_insertion_point(field:ltpb.CameraModuleHwInfo.lens)
    pub lens: ::std::option::Option<::protobuf::EnumOrUnknown<camera_module_hw_info::LensType>>,
    // @@protoc_insertion_point(field:ltpb.CameraModuleHwInfo.mirror_actuator)
    pub mirror_actuator: ::std::option::Option<::protobuf::EnumOrUnknown<camera_module_hw_info::MirrorActuatorType>>,
    // @@protoc_insertion_point(field:ltpb.CameraModuleHwInfo.mirror)
    pub mirror: ::std::option::Option<::protobuf::EnumOrUnknown<camera_module_hw_info::MirrorType>>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.CameraModuleHwInfo.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CameraModuleHwInfo {
    fn default() -> &'a CameraModuleHwInfo {
        <CameraModuleHwInfo as ::protobuf::Message>::default_instance()
    }
}

impl CameraModuleHwInfo {
    pub fn new() -> CameraModuleHwInfo {
        ::std::default::Default::default()
    }

    // optional .ltpb.CameraID id = 1;

    pub fn id(&self) -> super::camera_id::CameraID {
        match self.id {
            Some(e) => e.enum_value_or(super::camera_id::CameraID::A1),
            None => super::camera_id::CameraID::A1,
        }
    }

    pub fn clear_id(&mut self) {
        self.id = ::std::option::Option::None;
    }

    pub fn has_id(&self) -> bool {
        self.id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_id(&mut self, v: super::camera_id::CameraID) {
        self.id = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional .ltpb.SensorType sensor = 2;

    pub fn sensor(&self) -> super::sensor_type::SensorType {
        match self.sensor {
            Some(e) => e.enum_value_or(super::sensor_type::SensorType::SENSOR_UNKNOWN),
            None => super::sensor_type::SensorType::SENSOR_UNKNOWN,
        }
    }

    pub fn clear_sensor(&mut self) {
        self.sensor = ::std::option::Option::None;
    }

    pub fn has_sensor(&self) -> bool {
        self.sensor.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor(&mut self, v: super::sensor_type::SensorType) {
        self.sensor = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional .ltpb.CameraModuleHwInfo.LensType lens = 3;

    pub fn lens(&self) -> camera_module_hw_info::LensType {
        match self.lens {
            Some(e) => e.enum_value_or(camera_module_hw_info::LensType::LENS_UNKNOWN),
            None => camera_module_hw_info::LensType::LENS_UNKNOWN,
        }
    }

    pub fn clear_lens(&mut self) {
        self.lens = ::std::option::Option::None;
    }

    pub fn has_lens(&self) -> bool {
        self.lens.is_some()
    }

    // Param is passed by value, moved
    pub fn set_lens(&mut self, v: camera_module_hw_info::LensType) {
        self.lens = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional .ltpb.CameraModuleHwInfo.MirrorActuatorType mirror_actuator = 4;

    pub fn mirror_actuator(&self) -> camera_module_hw_info::MirrorActuatorType {
        match self.mirror_actuator {
            Some(e) => e.enum_value_or(camera_module_hw_info::MirrorActuatorType::MIRROR_ACTUATOR_UNKNOWN),
            None => camera_module_hw_info::MirrorActuatorType::MIRROR_ACTUATOR_UNKNOWN,
        }
    }

    pub fn clear_mirror_actuator(&mut self) {
        self.mirror_actuator = ::std::option::Option::None;
    }

    pub fn has_mirror_actuator(&self) -> bool {
        self.mirror_actuator.is_some()
    }

    // Param is passed by value, moved
    pub fn set_mirror_actuator(&mut self, v: camera_module_hw_info::MirrorActuatorType) {
        self.mirror_actuator = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional .ltpb.CameraModuleHwInfo.MirrorType mirror = 5;

    pub fn mirror(&self) -> camera_module_hw_info::MirrorType {
        match self.mirror {
            Some(e) => e.enum_value_or(camera_module_hw_info::MirrorType::MIRROR_UNKNOWN),
            None => camera_module_hw_info::MirrorType::MIRROR_UNKNOWN,
        }
    }

    pub fn clear_mirror(&mut self) {
        self.mirror = ::std::option::Option::None;
    }

    pub fn has_mirror(&self) -> bool {
        self.mirror.is_some()
    }

    // Param is passed by value, moved
    pub fn set_mirror(&mut self, v: camera_module_hw_info::MirrorType) {
        self.mirror = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }
}

impl ::protobuf::Message for CameraModuleHwInfo {
    const NAME: &'static str = "CameraModuleHwInfo";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.id = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                16 => {
                    self.sensor = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                24 => {
                    self.lens = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                32 => {
                    self.mirror_actuator = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                40 => {
                    self.mirror = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.id {
            my_size += ::protobuf::rt::int32_size(1, v.value());
        }
        if let Some(v) = self.sensor {
            my_size += ::protobuf::rt::int32_size(2, v.value());
        }
        if let Some(v) = self.lens {
            my_size += ::protobuf::rt::int32_size(3, v.value());
        }
        if let Some(v) = self.mirror_actuator {
            my_size += ::protobuf::rt::int32_size(4, v.value());
        }
        if let Some(v) = self.mirror {
            my_size += ::protobuf::rt::int32_size(5, v.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.id {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.sensor {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.lens {
            os.write_enum(3, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.mirror_actuator {
            os.write_enum(4, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.mirror {
            os.write_enum(5, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CameraModuleHwInfo {
        CameraModuleHwInfo::new()
    }

    fn clear(&mut self) {
        self.id = ::std::option::Option::None;
        self.sensor = ::std::option::Option::None;
        self.lens = ::std::option::Option::None;
        self.mirror_actuator = ::std::option::Option::None;
        self.mirror = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CameraModuleHwInfo {
        static instance: CameraModuleHwInfo = CameraModuleHwInfo {
            id: ::std::option::Option::None,
            sensor: ::std::option::Option::None,
            lens: ::std::option::Option::None,
            mirror_actuator: ::std::option::Option::None,
            mirror: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

/// Nested message and enums of message `CameraModuleHwInfo`
pub mod camera_module_hw_info {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.CameraModuleHwInfo.LensType)
    pub enum LensType {
        // @@protoc_insertion_point(enum_value:ltpb.CameraModuleHwInfo.LensType.LENS_UNKNOWN)
        LENS_UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:ltpb.CameraModuleHwInfo.LensType.LENS_SHOWIN)
        LENS_SHOWIN = 1,
        // @@protoc_insertion_point(enum_value:ltpb.CameraModuleHwInfo.LensType.LENS_LARGAN)
        LENS_LARGAN = 2,
        // @@protoc_insertion_point(enum_value:ltpb.CameraModuleHwInfo.LensType.LENS_SUNNY)
        LENS_SUNNY = 3,
        // @@protoc_insertion_point(enum_value:ltpb.CameraModuleHwInfo.LensType.LENS_KANTATSU)
        LENS_KANTATSU = 4,
    }

    impl ::protobuf::Enum for LensType {
        const NAME: &'static str = "LensType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<LensType> {
            match value {
                0 => ::std::option::Option::Some(LensType::LENS_UNKNOWN),
                1 => ::std::option::Option::Some(LensType::LENS_SHOWIN),
                2 => ::std::option::Option::Some(LensType::LENS_LARGAN),
                3 => ::std::option::Option::Some(LensType::LENS_SUNNY),
                4 => ::std::option::Option::Some(LensType::LENS_KANTATSU),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<LensType> {
            match str {
                "LENS_UNKNOWN" => ::std::option::Option::Some(LensType::LENS_UNKNOWN),
                "LENS_SHOWIN" => ::std::option::Option::Some(LensType::LENS_SHOWIN),
                "LENS_LARGAN" => ::std::option::Option::Some(LensType::LENS_LARGAN),
                "LENS_SUNNY" => ::std::option::Option::Some(LensType::LENS_SUNNY),
                "LENS_KANTATSU" => ::std::option::Option::Some(LensType::LENS_KANTATSU),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [LensType] = &[
            LensType::LENS_UNKNOWN,
            LensType::LENS_SHOWIN,
            LensType::LENS_LARGAN,
            LensType::LENS_SUNNY,
            LensType::LENS_KANTATSU,
        ];
    }

    impl ::std::default::Default for LensType {
        fn default() -> Self {
            LensType::LENS_UNKNOWN
        }
    }


    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.CameraModuleHwInfo.MirrorActuatorType)
    pub enum MirrorActuatorType {
        // @@protoc_insertion_point(enum_value:ltpb.CameraModuleHwInfo.MirrorActuatorType.MIRROR_ACTUATOR_UNKNOWN)
        MIRROR_ACTUATOR_UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:ltpb.CameraModuleHwInfo.MirrorActuatorType.MIRROR_ACTUATOR_PZT)
        MIRROR_ACTUATOR_PZT = 1,
    }

    impl ::protobuf::Enum for MirrorActuatorType {
        const NAME: &'static str = "MirrorActuatorType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<MirrorActuatorType> {
            match value {
                0 => ::std::option::Option::Some(MirrorActuatorType::MIRROR_ACTUATOR_UNKNOWN),
                1 => ::std::option::Option::Some(MirrorActuatorType::MIRROR_ACTUATOR_PZT),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<MirrorActuatorType> {
            match str {
                "MIRROR_ACTUATOR_UNKNOWN" => ::std::option::Option::Some(MirrorActuatorType::MIRROR_ACTUATOR_UNKNOWN),
                "MIRROR_ACTUATOR_PZT" => ::std::option::Option::Some(MirrorActuatorType::MIRROR_ACTUATOR_PZT),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [MirrorActuatorType] = &[
            MirrorActuatorType::MIRROR_ACTUATOR_UNKNOWN,
            MirrorActuatorType::MIRROR_ACTUATOR_PZT,
        ];
    }

    impl ::std::default::Default for MirrorActuatorType {
        fn default() -> Self {
            MirrorActuatorType::MIRROR_ACTUATOR_UNKNOWN
        }
    }


    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.CameraModuleHwInfo.MirrorType)
    pub enum MirrorType {
        // @@protoc_insertion_point(enum_value:ltpb.CameraModuleHwInfo.MirrorType.MIRROR_UNKNOWN)
        MIRROR_UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:ltpb.CameraModuleHwInfo.MirrorType.MIRROR_DIELECTRIC_SNX)
        MIRROR_DIELECTRIC_SNX = 1,
        // @@protoc_insertion_point(enum_value:ltpb.CameraModuleHwInfo.MirrorType.MIRROR_SILVER_ZUISHO)
        MIRROR_SILVER_ZUISHO = 2,
    }

    impl ::protobuf::Enum for MirrorType {
        const NAME: &'static str = "MirrorType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<MirrorType> {
            match value {
                0 => ::std::option::Option::Some(MirrorType::MIRROR_UNKNOWN),
                1 => ::std::option::Option::Some(MirrorType::MIRROR_DIELECTRIC_SNX),
                2 => ::std::option::Option::Some(MirrorType::MIRROR_SILVER_ZUISHO),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<MirrorType> {
            match str {
                "MIRROR_UNKNOWN" => ::std::option::Option::Some(MirrorType::MIRROR_UNKNOWN),
                "MIRROR_DIELECTRIC_SNX" => ::std::option::Option::Some(MirrorType::MIRROR_DIELECTRIC_SNX),
                "MIRROR_SILVER_ZUISHO" => ::std::option::Option::Some(MirrorType::MIRROR_SILVER_ZUISHO),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [MirrorType] = &[
            MirrorType::MIRROR_UNKNOWN,
            MirrorType::MIRROR_DIELECTRIC_SNX,
            MirrorType::MIRROR_SILVER_ZUISHO,
        ];
    }

    impl ::std::default::Default for MirrorType {
        fn default() -> Self {
            MirrorType::MIRROR_UNKNOWN
        }
    }


    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.CameraModuleHwInfo.LensActuatorType)
    pub enum LensActuatorType {
        // @@protoc_insertion_point(enum_value:ltpb.CameraModuleHwInfo.LensActuatorType.LENS_ACTUATOR_UNKNOWN)
        LENS_ACTUATOR_UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:ltpb.CameraModuleHwInfo.LensActuatorType.LENS_ACTUATOR_SHICOH)
        LENS_ACTUATOR_SHICOH = 1,
        // @@protoc_insertion_point(enum_value:ltpb.CameraModuleHwInfo.LensActuatorType.LENS_ACTUATOR_PZT)
        LENS_ACTUATOR_PZT = 2,
    }

    impl ::protobuf::Enum for LensActuatorType {
        const NAME: &'static str = "LensActuatorType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<LensActuatorType> {
            match value {
                0 => ::std::option::Option::Some(LensActuatorType::LENS_ACTUATOR_UNKNOWN),
                1 => ::std::option::Option::Some(LensActuatorType::LENS_ACTUATOR_SHICOH),
                2 => ::std::option::Option::Some(LensActuatorType::LENS_ACTUATOR_PZT),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<LensActuatorType> {
            match str {
                "LENS_ACTUATOR_UNKNOWN" => ::std::option::Option::Some(LensActuatorType::LENS_ACTUATOR_UNKNOWN),
                "LENS_ACTUATOR_SHICOH" => ::std::option::Option::Some(LensActuatorType::LENS_ACTUATOR_SHICOH),
                "LENS_ACTUATOR_PZT" => ::std::option::Option::Some(LensActuatorType::LENS_ACTUATOR_PZT),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [LensActuatorType] = &[
            LensActuatorType::LENS_ACTUATOR_UNKNOWN,
            LensActuatorType::LENS_ACTUATOR_SHICOH,
            LensActuatorType::LENS_ACTUATOR_PZT,
        ];
    }

    impl ::std::default::Default for LensActuatorType {
        fn default() -> Self {
            LensActuatorType::LENS_ACTUATOR_UNKNOWN
        }
    }

}

// @@protoc_insertion_point(message:ltpb.HwInfo)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct HwInfo {
    // message fields
    // @@protoc_insertion_point(field:ltpb.HwInfo.camera)
    pub camera: ::std::vec::Vec<CameraModuleHwInfo>,
    // @@protoc_insertion_point(field:ltpb.HwInfo.flash)
    pub flash: ::std::option::Option<::protobuf::EnumOrUnknown<hw_info::FlashType>>,
    // @@protoc_insertion_point(field:ltpb.HwInfo.tof)
    pub tof: ::std::option::Option<::protobuf::EnumOrUnknown<hw_info::ToFType>>,
    // @@protoc_insertion_point(field:ltpb.HwInfo.model)
    pub model: ::std::option::Option<::protobuf::EnumOrUnknown<hw_info::ModelType>>,
    // @@protoc_insertion_point(field:ltpb.HwInfo.manufacturer)
    pub manufacturer: ::std::option::Option<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.HwInfo.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a HwInfo {
    fn default() -> &'a HwInfo {
        <HwInfo as ::protobuf::Message>::default_instance()
    }
}

impl HwInfo {
    pub fn new() -> HwInfo {
        ::std::default::Default::default()
    }

    // optional .ltpb.HwInfo.FlashType flash = 2;

    pub fn flash(&self) -> hw_info::FlashType {
        match self.flash {
            Some(e) => e.enum_value_or(hw_info::FlashType::FLASH_UNKNOWN),
            None => hw_info::FlashType::FLASH_UNKNOWN,
        }
    }

    pub fn clear_flash(&mut self) {
        self.flash = ::std::option::Option::None;
    }

    pub fn has_flash(&self) -> bool {
        self.flash.is_some()
    }

    // Param is passed by value, moved
    pub fn set_flash(&mut self, v: hw_info::FlashType) {
        self.flash = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional .ltpb.HwInfo.ToFType tof = 3;

    pub fn tof(&self) -> hw_info::ToFType {
        match self.tof {
            Some(e) => e.enum_value_or(hw_info::ToFType::TOF_UNKNOWN),
            None => hw_info::ToFType::TOF_UNKNOWN,
        }
    }

    pub fn clear_tof(&mut self) {
        self.tof = ::std::option::Option::None;
    }

    pub fn has_tof(&self) -> bool {
        self.tof.is_some()
    }

    // Param is passed by value, moved
    pub fn set_tof(&mut self, v: hw_info::ToFType) {
        self.tof = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional .ltpb.HwInfo.ModelType model = 4;

    pub fn model(&self) -> hw_info::ModelType {
        match self.model {
            Some(e) => e.enum_value_or(hw_info::ModelType::MODEL_P1),
            None => hw_info::ModelType::MODEL_P1,
        }
    }

    pub fn clear_model(&mut self) {
        self.model = ::std::option::Option::None;
    }

    pub fn has_model(&self) -> bool {
        self.model.is_some()
    }

    // Param is passed by value, moved
    pub fn set_model(&mut self, v: hw_info::ModelType) {
        self.model = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional string manufacturer = 5;

    pub fn manufacturer(&self) -> &str {
        match self.manufacturer.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_manufacturer(&mut self) {
        self.manufacturer = ::std::option::Option::None;
    }

    pub fn has_manufacturer(&self) -> bool {
        self.manufacturer.is_some()
    }

    // Param is passed by value, moved
    pub fn set_manufacturer(&mut self, v: ::std::string::String) {
        self.manufacturer = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_manufacturer(&mut self) -> &mut ::std::string::String {
        if self.manufacturer.is_none() {
            self.manufacturer = ::std::option::Option::Some(::std::string::String::new());
        }
        self.manufacturer.as_mut().unwrap()
    }

    // Take field
    pub fn take_manufacturer(&mut self) -> ::std::string::String {
        self.manufacturer.take().unwrap_or_else(|| ::std::string::String::new())
    }
}

impl ::protobuf::Message for HwInfo {
    const NAME: &'static str = "HwInfo";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.camera.push(is.read_message()?);
                },
                16 => {
                    self.flash = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                24 => {
                    self.tof = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                32 => {
                    self.model = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                42 => {
                    self.manufacturer = ::std::option::Option::Some(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.camera {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.flash {
            my_size += ::protobuf::rt::int32_size(2, v.value());
        }
        if let Some(v) = self.tof {
            my_size += ::protobuf::rt::int32_size(3, v.value());
        }
        if let Some(v) = self.model {
            my_size += ::protobuf::rt::int32_size(4, v.value());
        }
        if let Some(v) = self.manufacturer.as_ref() {
            my_size += ::protobuf::rt::string_size(5, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.camera {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        if let Some(v) = self.flash {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.tof {
            os.write_enum(3, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.model {
            os.write_enum(4, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.manufacturer.as_ref() {
            os.write_string(5, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> HwInfo {
        HwInfo::new()
    }

    fn clear(&mut self) {
        self.camera.clear();
        self.flash = ::std::option::Option::None;
        self.tof = ::std::option::Option::None;
        self.model = ::std::option::Option::None;
        self.manufacturer = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static HwInfo {
        static instance: HwInfo = HwInfo {
            camera: ::std::vec::Vec::new(),
            flash: ::std::option::Option::None,
            tof: ::std::option::Option::None,
            model: ::std::option::Option::None,
            manufacturer: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

/// Nested message and enums of message `HwInfo`
pub mod hw_info {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.HwInfo.FlashType)
    pub enum FlashType {
        // @@protoc_insertion_point(enum_value:ltpb.HwInfo.FlashType.FLASH_UNKNOWN)
        FLASH_UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:ltpb.HwInfo.FlashType.FLASH_OSRAM_CBLPM1)
        FLASH_OSRAM_CBLPM1 = 1,
    }

    impl ::protobuf::Enum for FlashType {
        const NAME: &'static str = "FlashType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<FlashType> {
            match value {
                0 => ::std::option::Option::Some(FlashType::FLASH_UNKNOWN),
                1 => ::std::option::Option::Some(FlashType::FLASH_OSRAM_CBLPM1),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<FlashType> {
            match str {
                "FLASH_UNKNOWN" => ::std::option::Option::Some(FlashType::FLASH_UNKNOWN),
                "FLASH_OSRAM_CBLPM1" => ::std::option::Option::Some(FlashType::FLASH_OSRAM_CBLPM1),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [FlashType] = &[
            FlashType::FLASH_UNKNOWN,
            FlashType::FLASH_OSRAM_CBLPM1,
        ];
    }

    impl ::std::default::Default for FlashType {
        fn default() -> Self {
            FlashType::FLASH_UNKNOWN
        }
    }


    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.HwInfo.ToFType)
    pub enum ToFType {
        // @@protoc_insertion_point(enum_value:ltpb.HwInfo.ToFType.TOF_UNKNOWN)
        TOF_UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:ltpb.HwInfo.ToFType.TOF_STMICRO_VL53L0)
        TOF_STMICRO_VL53L0 = 1,
    }

    impl ::protobuf::Enum for ToFType {
        const NAME: &'static str = "ToFType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<ToFType> {
            match value {
                0 => ::std::option::Option::Some(ToFType::TOF_UNKNOWN),
                1 => ::std::option::Option::Some(ToFType::TOF_STMICRO_VL53L0),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<ToFType> {
            match str {
                "TOF_UNKNOWN" => ::std::option::Option::Some(ToFType::TOF_UNKNOWN),
                "TOF_STMICRO_VL53L0" => ::std::option::Option::Some(ToFType::TOF_STMICRO_VL53L0),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [ToFType] = &[
            ToFType::TOF_UNKNOWN,
            ToFType::TOF_STMICRO_VL53L0,
        ];
    }

    impl ::std::default::Default for ToFType {
        fn default() -> Self {
            ToFType::TOF_UNKNOWN
        }
    }


    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.HwInfo.ModelType)
    pub enum ModelType {
        // @@protoc_insertion_point(enum_value:ltpb.HwInfo.ModelType.MODEL_P1)
        MODEL_P1 = 0,
        // @@protoc_insertion_point(enum_value:ltpb.HwInfo.ModelType.MODEL_P1_1)
        MODEL_P1_1 = 1,
        // @@protoc_insertion_point(enum_value:ltpb.HwInfo.ModelType.MODEL_P2)
        MODEL_P2 = 2,
    }

    impl ::protobuf::Enum for ModelType {
        const NAME: &'static str = "ModelType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<ModelType> {
            match value {
                0 => ::std::option::Option::Some(ModelType::MODEL_P1),
                1 => ::std::option::Option::Some(ModelType::MODEL_P1_1),
                2 => ::std::option::Option::Some(ModelType::MODEL_P2),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<ModelType> {
            match str {
                "MODEL_P1" => ::std::option::Option::Some(ModelType::MODEL_P1),
                "MODEL_P1_1" => ::std::option::Option::Some(ModelType::MODEL_P1_1),
                "MODEL_P2" => ::std::option::Option::Some(ModelType::MODEL_P2),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [ModelType] = &[
            ModelType::MODEL_P1,
            ModelType::MODEL_P1_1,
            ModelType::MODEL_P2,
        ];
    }

    impl ::std::default::Default for ModelType {
        fn default() -> Self {
            ModelType::MODEL_P1
        }
    }

}
