// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `matrix4x4f.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

// @@protoc_insertion_point(message:ltpb.Matrix4x4F)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Matrix4x4F {
    // message fields
    // @@protoc_insertion_point(field:ltpb.Matrix4x4F.x00)
    pub x00: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.Matrix4x4F.x01)
    pub x01: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.Matrix4x4F.x02)
    pub x02: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.Matrix4x4F.x03)
    pub x03: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.Matrix4x4F.x10)
    pub x10: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.Matrix4x4F.x11)
    pub x11: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.Matrix4x4F.x12)
    pub x12: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.Matrix4x4F.x13)
    pub x13: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.Matrix4x4F.x20)
    pub x20: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.Matrix4x4F.x21)
    pub x21: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.Matrix4x4F.x22)
    pub x22: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.Matrix4x4F.x23)
    pub x23: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.Matrix4x4F.x30)
    pub x30: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.Matrix4x4F.x31)
    pub x31: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.Matrix4x4F.x32)
    pub x32: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.Matrix4x4F.x33)
    pub x33: ::std::option::Option<f32>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.Matrix4x4F.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Matrix4x4F {
    fn default() -> &'a Matrix4x4F {
        <Matrix4x4F as ::protobuf::Message>::default_instance()
    }
}

impl Matrix4x4F {
    pub fn new() -> Matrix4x4F {
        ::std::default::Default::default()
    }

    // optional float x00 = 1;

    pub fn x00(&self) -> f32 {
        self.x00.unwrap_or(0.)
    }

    pub fn clear_x00(&mut self) {
        self.x00 = ::std::option::Option::None;
    }

    pub fn has_x00(&self) -> bool {
        self.x00.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x00(&mut self, v: f32) {
        self.x00 = ::std::option::Option::Some(v);
    }

    // optional float x01 = 2;

    pub fn x01(&self) -> f32 {
        self.x01.unwrap_or(0.)
    }

    pub fn clear_x01(&mut self) {
        self.x01 = ::std::option::Option::None;
    }

    pub fn has_x01(&self) -> bool {
        self.x01.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x01(&mut self, v: f32) {
        self.x01 = ::std::option::Option::Some(v);
    }

    // optional float x02 = 3;

    pub fn x02(&self) -> f32 {
        self.x02.unwrap_or(0.)
    }

    pub fn clear_x02(&mut self) {
        self.x02 = ::std::option::Option::None;
    }

    pub fn has_x02(&self) -> bool {
        self.x02.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x02(&mut self, v: f32) {
        self.x02 = ::std::option::Option::Some(v);
    }

    // optional float x03 = 4;

    pub fn x03(&self) -> f32 {
        self.x03.unwrap_or(0.)
    }

    pub fn clear_x03(&mut self) {
        self.x03 = ::std::option::Option::None;
    }

    pub fn has_x03(&self) -> bool {
        self.x03.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x03(&mut self, v: f32) {
        self.x03 = ::std::option::Option::Some(v);
    }

    // optional float x10 = 5;

    pub fn x10(&self) -> f32 {
        self.x10.unwrap_or(0.)
    }

    pub fn clear_x10(&mut self) {
        self.x10 = ::std::option::Option::None;
    }

    pub fn has_x10(&self) -> bool {
        self.x10.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x10(&mut self, v: f32) {
        self.x10 = ::std::option::Option::Some(v);
    }

    // optional float x11 = 6;

    pub fn x11(&self) -> f32 {
        self.x11.unwrap_or(0.)
    }

    pub fn clear_x11(&mut self) {
        self.x11 = ::std::option::Option::None;
    }

    pub fn has_x11(&self) -> bool {
        self.x11.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x11(&mut self, v: f32) {
        self.x11 = ::std::option::Option::Some(v);
    }

    // optional float x12 = 7;

    pub fn x12(&self) -> f32 {
        self.x12.unwrap_or(0.)
    }

    pub fn clear_x12(&mut self) {
        self.x12 = ::std::option::Option::None;
    }

    pub fn has_x12(&self) -> bool {
        self.x12.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x12(&mut self, v: f32) {
        self.x12 = ::std::option::Option::Some(v);
    }

    // optional float x13 = 8;

    pub fn x13(&self) -> f32 {
        self.x13.unwrap_or(0.)
    }

    pub fn clear_x13(&mut self) {
        self.x13 = ::std::option::Option::None;
    }

    pub fn has_x13(&self) -> bool {
        self.x13.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x13(&mut self, v: f32) {
        self.x13 = ::std::option::Option::Some(v);
    }

    // optional float x20 = 9;

    pub fn x20(&self) -> f32 {
        self.x20.unwrap_or(0.)
    }

    pub fn clear_x20(&mut self) {
        self.x20 = ::std::option::Option::None;
    }

    pub fn has_x20(&self) -> bool {
        self.x20.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x20(&mut self, v: f32) {
        self.x20 = ::std::option::Option::Some(v);
    }

    // optional float x21 = 10;

    pub fn x21(&self) -> f32 {
        self.x21.unwrap_or(0.)
    }

    pub fn clear_x21(&mut self) {
        self.x21 = ::std::option::Option::None;
    }

    pub fn has_x21(&self) -> bool {
        self.x21.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x21(&mut self, v: f32) {
        self.x21 = ::std::option::Option::Some(v);
    }

    // optional float x22 = 11;

    pub fn x22(&self) -> f32 {
        self.x22.unwrap_or(0.)
    }

    pub fn clear_x22(&mut self) {
        self.x22 = ::std::option::Option::None;
    }

    pub fn has_x22(&self) -> bool {
        self.x22.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x22(&mut self, v: f32) {
        self.x22 = ::std::option::Option::Some(v);
    }

    // optional float x23 = 12;

    pub fn x23(&self) -> f32 {
        self.x23.unwrap_or(0.)
    }

    pub fn clear_x23(&mut self) {
        self.x23 = ::std::option::Option::None;
    }

    pub fn has_x23(&self) -> bool {
        self.x23.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x23(&mut self, v: f32) {
        self.x23 = ::std::option::Option::Some(v);
    }

    // optional float x30 = 13;

    pub fn x30(&self) -> f32 {
        self.x30.unwrap_or(0.)
    }

    pub fn clear_x30(&mut self) {
        self.x30 = ::std::option::Option::None;
    }

    pub fn has_x30(&self) -> bool {
        self.x30.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x30(&mut self, v: f32) {
        self.x30 = ::std::option::Option::Some(v);
    }

    // optional float x31 = 14;

    pub fn x31(&self) -> f32 {
        self.x31.unwrap_or(0.)
    }

    pub fn clear_x31(&mut self) {
        self.x31 = ::std::option::Option::None;
    }

    pub fn has_x31(&self) -> bool {
        self.x31.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x31(&mut self, v: f32) {
        self.x31 = ::std::option::Option::Some(v);
    }

    // optional float x32 = 15;

    pub fn x32(&self) -> f32 {
        self.x32.unwrap_or(0.)
    }

    pub fn clear_x32(&mut self) {
        self.x32 = ::std::option::Option::None;
    }

    pub fn has_x32(&self) -> bool {
        self.x32.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x32(&mut self, v: f32) {
        self.x32 = ::std::option::Option::Some(v);
    }

    // optional float x33 = 16;

    pub fn x33(&self) -> f32 {
        self.x33.unwrap_or(0.)
    }

    pub fn clear_x33(&mut self) {
        self.x33 = ::std::option::Option::None;
    }

    pub fn has_x33(&self) -> bool {
        self.x33.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x33(&mut self, v: f32) {
        self.x33 = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for Matrix4x4F {
    const NAME: &'static str = "Matrix4x4F";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                13 => {
                    self.x00 = ::std::option::Option::Some(is.read_float()?);
                },
                21 => {
                    self.x01 = ::std::option::Option::Some(is.read_float()?);
                },
                29 => {
                    self.x02 = ::std::option::Option::Some(is.read_float()?);
                },
                37 => {
                    self.x03 = ::std::option::Option::Some(is.read_float()?);
                },
                45 => {
                    self.x10 = ::std::option::Option::Some(is.read_float()?);
                },
                53 => {
                    self.x11 = ::std::option::Option::Some(is.read_float()?);
                },
                61 => {
                    self.x12 = ::std::option::Option::Some(is.read_float()?);
                },
                69 => {
                    self.x13 = ::std::option::Option::Some(is.read_float()?);
                },
                77 => {
                    self.x20 = ::std::option::Option::Some(is.read_float()?);
                },
                85 => {
                    self.x21 = ::std::option::Option::Some(is.read_float()?);
                },
                93 => {
                    self.x22 = ::std::option::Option::Some(is.read_float()?);
                },
                101 => {
                    self.x23 = ::std::option::Option::Some(is.read_float()?);
                },
                109 => {
                    self.x30 = ::std::option::Option::Some(is.read_float()?);
                },
                117 => {
                    self.x31 = ::std::option::Option::Some(is.read_float()?);
                },
                125 => {
                    self.x32 = ::std::option::Option::Some(is.read_float()?);
                },
                133 => {
                    self.x33 = ::std::option::Option::Some(is.read_float()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.x00 {
            my_size += 1 + 4;
        }
        if let Some(v) = self.x01 {
            my_size += 1 + 4;
        }
        if let Some(v) = self.x02 {
            my_size += 1 + 4;
        }
        if let Some(v) = self.x03 {
            my_size += 1 + 4;
        }
        if let Some(v) = self.x10 {
            my_size += 1 + 4;
        }
        if let Some(v) = self.x11 {
            my_size += 1 + 4;
        }
        if let Some(v) = self.x12 {
            my_size += 1 + 4;
        }
        if let Some(v) = self.x13 {
            my_size += 1 + 4;
        }
        if let Some(v) = self.x20 {
            my_size += 1 + 4;
        }
        if let Some(v) = self.x21 {
            my_size += 1 + 4;
        }
        if let Some(v) = self.x22 {
            my_size += 1 + 4;
        }
        if let Some(v) = self.x23 {
            my_size += 1 + 4;
        }
        if let Some(v) = self.x30 {
            my_size += 1 + 4;
        }
        if let Some(v) = self.x31 {
            my_size += 1 + 4;
        }
        if let Some(v) = self.x32 {
            my_size += 1 + 4;
        }
        if let Some(v) = self.x33 {
            my_size += 2 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.x00 {
            os.write_float(1, v)?;
        }
        if let Some(v) = self.x01 {
            os.write_float(2, v)?;
        }
        if let Some(v) = self.x02 {
            os.write_float(3, v)?;
        }
        if let Some(v) = self.x03 {
            os.write_float(4, v)?;
        }
        if let Some(v) = self.x10 {
            os.write_float(5, v)?;
        }
        if let Some(v) = self.x11 {
            os.write_float(6, v)?;
        }
        if let Some(v) = self.x12 {
            os.write_float(7, v)?;
        }
        if let Some(v) = self.x13 {
            os.write_float(8, v)?;
        }
        if let Some(v) = self.x20 {
            os.write_float(9, v)?;
        }
        if let Some(v) = self.x21 {
            os.write_float(10, v)?;
        }
        if let Some(v) = self.x22 {
            os.write_float(11, v)?;
        }
        if let Some(v) = self.x23 {
            os.write_float(12, v)?;
        }
        if let Some(v) = self.x30 {
            os.write_float(13, v)?;
        }
        if let Some(v) = self.x31 {
            os.write_float(14, v)?;
        }
        if let Some(v) = self.x32 {
            os.write_float(15, v)?;
        }
        if let Some(v) = self.x33 {
            os.write_float(16, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Matrix4x4F {
        Matrix4x4F::new()
    }

    fn clear(&mut self) {
        self.x00 = ::std::option::Option::None;
        self.x01 = ::std::option::Option::None;
        self.x02 = ::std::option::Option::None;
        self.x03 = ::std::option::Option::None;
        self.x10 = ::std::option::Option::None;
        self.x11 = ::std::option::Option::None;
        self.x12 = ::std::option::Option::None;
        self.x13 = ::std::option::Option::None;
        self.x20 = ::std::option::Option::None;
        self.x21 = ::std::option::Option::None;
        self.x22 = ::std::option::Option::None;
        self.x23 = ::std::option::Option::None;
        self.x30 = ::std::option::Option::None;
        self.x31 = ::std::option::Option::None;
        self.x32 = ::std::option::Option::None;
        self.x33 = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Matrix4x4F {
        static instance: Matrix4x4F = Matrix4x4F {
            x00: ::std::option::Option::None,
            x01: ::std::option::Option::None,
            x02: ::std::option::Option::None,
            x03: ::std::option::Option::None,
            x10: ::std::option::Option::None,
            x11: ::std::option::Option::None,
            x12: ::std::option::Option::None,
            x13: ::std::option::Option::None,
            x20: ::std::option::Option::None,
            x21: ::std::option::Option::None,
            x22: ::std::option::Option::None,
            x23: ::std::option::Option::None,
            x30: ::std::option::Option::None,
            x31: ::std::option::Option::None,
            x32: ::std::option::Option::None,
            x33: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}
