// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `mirror_system.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

// @@protoc_insertion_point(message:ltpb.MirrorSystem)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct MirrorSystem {
    // message fields
    // @@protoc_insertion_point(field:ltpb.MirrorSystem.real_camera_location)
    pub real_camera_location: ::protobuf::MessageField<super::point3f::Point3F>,
    // @@protoc_insertion_point(field:ltpb.MirrorSystem.real_camera_orientation)
    pub real_camera_orientation: ::protobuf::MessageField<super::matrix3x3f::Matrix3x3F>,
    // @@protoc_insertion_point(field:ltpb.MirrorSystem.rotation_axis)
    pub rotation_axis: ::protobuf::MessageField<super::point3f::Point3F>,
    // @@protoc_insertion_point(field:ltpb.MirrorSystem.point_on_rotation_axis)
    pub point_on_rotation_axis: ::protobuf::MessageField<super::point3f::Point3F>,
    // @@protoc_insertion_point(field:ltpb.MirrorSystem.distance_mirror_plane_to_point_on_rotation_axis)
    pub distance_mirror_plane_to_point_on_rotation_axis: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.MirrorSystem.mirror_normal_at_zero_degrees)
    pub mirror_normal_at_zero_degrees: ::protobuf::MessageField<super::point3f::Point3F>,
    // @@protoc_insertion_point(field:ltpb.MirrorSystem.flip_img_around_x)
    pub flip_img_around_x: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:ltpb.MirrorSystem.mirror_angle_range)
    pub mirror_angle_range: ::protobuf::MessageField<super::range2f::Range2F>,
    // @@protoc_insertion_point(field:ltpb.MirrorSystem.reprojection_error)
    pub reprojection_error: ::std::option::Option<f32>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.MirrorSystem.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MirrorSystem {
    fn default() -> &'a MirrorSystem {
        <MirrorSystem as ::protobuf::Message>::default_instance()
    }
}

impl MirrorSystem {
    pub fn new() -> MirrorSystem {
        ::std::default::Default::default()
    }

    // optional float distance_mirror_plane_to_point_on_rotation_axis = 5;

    pub fn distance_mirror_plane_to_point_on_rotation_axis(&self) -> f32 {
        self.distance_mirror_plane_to_point_on_rotation_axis.unwrap_or(0.)
    }

    pub fn clear_distance_mirror_plane_to_point_on_rotation_axis(&mut self) {
        self.distance_mirror_plane_to_point_on_rotation_axis = ::std::option::Option::None;
    }

    pub fn has_distance_mirror_plane_to_point_on_rotation_axis(&self) -> bool {
        self.distance_mirror_plane_to_point_on_rotation_axis.is_some()
    }

    // Param is passed by value, moved
    pub fn set_distance_mirror_plane_to_point_on_rotation_axis(&mut self, v: f32) {
        self.distance_mirror_plane_to_point_on_rotation_axis = ::std::option::Option::Some(v);
    }

    // optional bool flip_img_around_x = 7;

    pub fn flip_img_around_x(&self) -> bool {
        self.flip_img_around_x.unwrap_or(false)
    }

    pub fn clear_flip_img_around_x(&mut self) {
        self.flip_img_around_x = ::std::option::Option::None;
    }

    pub fn has_flip_img_around_x(&self) -> bool {
        self.flip_img_around_x.is_some()
    }

    // Param is passed by value, moved
    pub fn set_flip_img_around_x(&mut self, v: bool) {
        self.flip_img_around_x = ::std::option::Option::Some(v);
    }

    // optional float reprojection_error = 9;

    pub fn reprojection_error(&self) -> f32 {
        self.reprojection_error.unwrap_or(0.)
    }

    pub fn clear_reprojection_error(&mut self) {
        self.reprojection_error = ::std::option::Option::None;
    }

    pub fn has_reprojection_error(&self) -> bool {
        self.reprojection_error.is_some()
    }

    // Param is passed by value, moved
    pub fn set_reprojection_error(&mut self, v: f32) {
        self.reprojection_error = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for MirrorSystem {
    const NAME: &'static str = "MirrorSystem";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.real_camera_location)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.real_camera_orientation)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.rotation_axis)?;
                },
                34 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.point_on_rotation_axis)?;
                },
                45 => {
                    self.distance_mirror_plane_to_point_on_rotation_axis = ::std::option::Option::Some(is.read_float()?);
                },
                50 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.mirror_normal_at_zero_degrees)?;
                },
                56 => {
                    self.flip_img_around_x = ::std::option::Option::Some(is.read_bool()?);
                },
                66 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.mirror_angle_range)?;
                },
                77 => {
                    self.reprojection_error = ::std::option::Option::Some(is.read_float()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.real_camera_location.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.real_camera_orientation.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.rotation_axis.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.point_on_rotation_axis.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.distance_mirror_plane_to_point_on_rotation_axis {
            my_size += 1 + 4;
        }
        if let Some(v) = self.mirror_normal_at_zero_degrees.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.flip_img_around_x {
            my_size += 1 + 1;
        }
        if let Some(v) = self.mirror_angle_range.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.reprojection_error {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.real_camera_location.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.real_camera_orientation.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.rotation_axis.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if let Some(v) = self.point_on_rotation_axis.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        }
        if let Some(v) = self.distance_mirror_plane_to_point_on_rotation_axis {
            os.write_float(5, v)?;
        }
        if let Some(v) = self.mirror_normal_at_zero_degrees.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        }
        if let Some(v) = self.flip_img_around_x {
            os.write_bool(7, v)?;
        }
        if let Some(v) = self.mirror_angle_range.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        }
        if let Some(v) = self.reprojection_error {
            os.write_float(9, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MirrorSystem {
        MirrorSystem::new()
    }

    fn clear(&mut self) {
        self.real_camera_location.clear();
        self.real_camera_orientation.clear();
        self.rotation_axis.clear();
        self.point_on_rotation_axis.clear();
        self.distance_mirror_plane_to_point_on_rotation_axis = ::std::option::Option::None;
        self.mirror_normal_at_zero_degrees.clear();
        self.flip_img_around_x = ::std::option::Option::None;
        self.mirror_angle_range.clear();
        self.reprojection_error = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MirrorSystem {
        static instance: MirrorSystem = MirrorSystem {
            real_camera_location: ::protobuf::MessageField::none(),
            real_camera_orientation: ::protobuf::MessageField::none(),
            rotation_axis: ::protobuf::MessageField::none(),
            point_on_rotation_axis: ::protobuf::MessageField::none(),
            distance_mirror_plane_to_point_on_rotation_axis: ::std::option::Option::None,
            mirror_normal_at_zero_degrees: ::protobuf::MessageField::none(),
            flip_img_around_x: ::std::option::Option::None,
            mirror_angle_range: ::protobuf::MessageField::none(),
            reprojection_error: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

// @@protoc_insertion_point(message:ltpb.MirrorActuatorMapping)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct MirrorActuatorMapping {
    // message fields
    // @@protoc_insertion_point(field:ltpb.MirrorActuatorMapping.transformation_type)
    pub transformation_type: ::std::option::Option<::protobuf::EnumOrUnknown<mirror_actuator_mapping::TransformationType>>,
    // @@protoc_insertion_point(field:ltpb.MirrorActuatorMapping.actuator_length_offset)
    pub actuator_length_offset: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.MirrorActuatorMapping.actuator_length_scale)
    pub actuator_length_scale: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.MirrorActuatorMapping.mirror_angle_offset)
    pub mirror_angle_offset: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.MirrorActuatorMapping.mirror_angle_scale)
    pub mirror_angle_scale: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.MirrorActuatorMapping.actuator_angle_pair_vec)
    pub actuator_angle_pair_vec: ::std::vec::Vec<mirror_actuator_mapping::ActuatorAnglePair>,
    // @@protoc_insertion_point(field:ltpb.MirrorActuatorMapping.quadratic_model)
    pub quadratic_model: ::protobuf::MessageField<mirror_actuator_mapping::QuadraticModel>,
    // @@protoc_insertion_point(field:ltpb.MirrorActuatorMapping.angle_to_hall_code_error)
    pub angle_to_hall_code_error: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.MirrorActuatorMapping.hall_code_to_angle_error)
    pub hall_code_to_angle_error: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.MirrorActuatorMapping.hall_code_range)
    pub hall_code_range: ::protobuf::MessageField<super::range2f::Range2F>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.MirrorActuatorMapping.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MirrorActuatorMapping {
    fn default() -> &'a MirrorActuatorMapping {
        <MirrorActuatorMapping as ::protobuf::Message>::default_instance()
    }
}

impl MirrorActuatorMapping {
    pub fn new() -> MirrorActuatorMapping {
        ::std::default::Default::default()
    }

    // optional .ltpb.MirrorActuatorMapping.TransformationType transformation_type = 1;

    pub fn transformation_type(&self) -> mirror_actuator_mapping::TransformationType {
        match self.transformation_type {
            Some(e) => e.enum_value_or(mirror_actuator_mapping::TransformationType::MEAN_STD_NORMALIZE),
            None => mirror_actuator_mapping::TransformationType::MEAN_STD_NORMALIZE,
        }
    }

    pub fn clear_transformation_type(&mut self) {
        self.transformation_type = ::std::option::Option::None;
    }

    pub fn has_transformation_type(&self) -> bool {
        self.transformation_type.is_some()
    }

    // Param is passed by value, moved
    pub fn set_transformation_type(&mut self, v: mirror_actuator_mapping::TransformationType) {
        self.transformation_type = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional float actuator_length_offset = 2;

    pub fn actuator_length_offset(&self) -> f32 {
        self.actuator_length_offset.unwrap_or(0.)
    }

    pub fn clear_actuator_length_offset(&mut self) {
        self.actuator_length_offset = ::std::option::Option::None;
    }

    pub fn has_actuator_length_offset(&self) -> bool {
        self.actuator_length_offset.is_some()
    }

    // Param is passed by value, moved
    pub fn set_actuator_length_offset(&mut self, v: f32) {
        self.actuator_length_offset = ::std::option::Option::Some(v);
    }

    // optional float actuator_length_scale = 3;

    pub fn actuator_length_scale(&self) -> f32 {
        self.actuator_length_scale.unwrap_or(0.)
    }

    pub fn clear_actuator_length_scale(&mut self) {
        self.actuator_length_scale = ::std::option::Option::None;
    }

    pub fn has_actuator_length_scale(&self) -> bool {
        self.actuator_length_scale.is_some()
    }

    // Param is passed by value, moved
    pub fn set_actuator_length_scale(&mut self, v: f32) {
        self.actuator_length_scale = ::std::option::Option::Some(v);
    }

    // optional float mirror_angle_offset = 4;

    pub fn mirror_angle_offset(&self) -> f32 {
        self.mirror_angle_offset.unwrap_or(0.)
    }

    pub fn clear_mirror_angle_offset(&mut self) {
        self.mirror_angle_offset = ::std::option::Option::None;
    }

    pub fn has_mirror_angle_offset(&self) -> bool {
        self.mirror_angle_offset.is_some()
    }

    // Param is passed by value, moved
    pub fn set_mirror_angle_offset(&mut self, v: f32) {
        self.mirror_angle_offset = ::std::option::Option::Some(v);
    }

    // optional float mirror_angle_scale = 5;

    pub fn mirror_angle_scale(&self) -> f32 {
        self.mirror_angle_scale.unwrap_or(0.)
    }

    pub fn clear_mirror_angle_scale(&mut self) {
        self.mirror_angle_scale = ::std::option::Option::None;
    }

    pub fn has_mirror_angle_scale(&self) -> bool {
        self.mirror_angle_scale.is_some()
    }

    // Param is passed by value, moved
    pub fn set_mirror_angle_scale(&mut self, v: f32) {
        self.mirror_angle_scale = ::std::option::Option::Some(v);
    }

    // optional float angle_to_hall_code_error = 8;

    pub fn angle_to_hall_code_error(&self) -> f32 {
        self.angle_to_hall_code_error.unwrap_or(0.)
    }

    pub fn clear_angle_to_hall_code_error(&mut self) {
        self.angle_to_hall_code_error = ::std::option::Option::None;
    }

    pub fn has_angle_to_hall_code_error(&self) -> bool {
        self.angle_to_hall_code_error.is_some()
    }

    // Param is passed by value, moved
    pub fn set_angle_to_hall_code_error(&mut self, v: f32) {
        self.angle_to_hall_code_error = ::std::option::Option::Some(v);
    }

    // optional float hall_code_to_angle_error = 9;

    pub fn hall_code_to_angle_error(&self) -> f32 {
        self.hall_code_to_angle_error.unwrap_or(0.)
    }

    pub fn clear_hall_code_to_angle_error(&mut self) {
        self.hall_code_to_angle_error = ::std::option::Option::None;
    }

    pub fn has_hall_code_to_angle_error(&self) -> bool {
        self.hall_code_to_angle_error.is_some()
    }

    // Param is passed by value, moved
    pub fn set_hall_code_to_angle_error(&mut self, v: f32) {
        self.hall_code_to_angle_error = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for MirrorActuatorMapping {
    const NAME: &'static str = "MirrorActuatorMapping";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.transformation_type = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                21 => {
                    self.actuator_length_offset = ::std::option::Option::Some(is.read_float()?);
                },
                29 => {
                    self.actuator_length_scale = ::std::option::Option::Some(is.read_float()?);
                },
                37 => {
                    self.mirror_angle_offset = ::std::option::Option::Some(is.read_float()?);
                },
                45 => {
                    self.mirror_angle_scale = ::std::option::Option::Some(is.read_float()?);
                },
                50 => {
                    self.actuator_angle_pair_vec.push(is.read_message()?);
                },
                58 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.quadratic_model)?;
                },
                69 => {
                    self.angle_to_hall_code_error = ::std::option::Option::Some(is.read_float()?);
                },
                77 => {
                    self.hall_code_to_angle_error = ::std::option::Option::Some(is.read_float()?);
                },
                82 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.hall_code_range)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.transformation_type {
            my_size += ::protobuf::rt::int32_size(1, v.value());
        }
        if let Some(v) = self.actuator_length_offset {
            my_size += 1 + 4;
        }
        if let Some(v) = self.actuator_length_scale {
            my_size += 1 + 4;
        }
        if let Some(v) = self.mirror_angle_offset {
            my_size += 1 + 4;
        }
        if let Some(v) = self.mirror_angle_scale {
            my_size += 1 + 4;
        }
        for value in &self.actuator_angle_pair_vec {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.quadratic_model.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.angle_to_hall_code_error {
            my_size += 1 + 4;
        }
        if let Some(v) = self.hall_code_to_angle_error {
            my_size += 1 + 4;
        }
        if let Some(v) = self.hall_code_range.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.transformation_type {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.actuator_length_offset {
            os.write_float(2, v)?;
        }
        if let Some(v) = self.actuator_length_scale {
            os.write_float(3, v)?;
        }
        if let Some(v) = self.mirror_angle_offset {
            os.write_float(4, v)?;
        }
        if let Some(v) = self.mirror_angle_scale {
            os.write_float(5, v)?;
        }
        for v in &self.actuator_angle_pair_vec {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        };
        if let Some(v) = self.quadratic_model.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
        }
        if let Some(v) = self.angle_to_hall_code_error {
            os.write_float(8, v)?;
        }
        if let Some(v) = self.hall_code_to_angle_error {
            os.write_float(9, v)?;
        }
        if let Some(v) = self.hall_code_range.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(10, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MirrorActuatorMapping {
        MirrorActuatorMapping::new()
    }

    fn clear(&mut self) {
        self.transformation_type = ::std::option::Option::None;
        self.actuator_length_offset = ::std::option::Option::None;
        self.actuator_length_scale = ::std::option::Option::None;
        self.mirror_angle_offset = ::std::option::Option::None;
        self.mirror_angle_scale = ::std::option::Option::None;
        self.actuator_angle_pair_vec.clear();
        self.quadratic_model.clear();
        self.angle_to_hall_code_error = ::std::option::Option::None;
        self.hall_code_to_angle_error = ::std::option::Option::None;
        self.hall_code_range.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MirrorActuatorMapping {
        static instance: MirrorActuatorMapping = MirrorActuatorMapping {
            transformation_type: ::std::option::Option::None,
            actuator_length_offset: ::std::option::Option::None,
            actuator_length_scale: ::std::option::Option::None,
            mirror_angle_offset: ::std::option::Option::None,
            mirror_angle_scale: ::std::option::Option::None,
            actuator_angle_pair_vec: ::std::vec::Vec::new(),
            quadratic_model: ::protobuf::MessageField::none(),
            angle_to_hall_code_error: ::std::option::Option::None,
            hall_code_to_angle_error: ::std::option::Option::None,
            hall_code_range: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

/// Nested message and enums of message `MirrorActuatorMapping`
pub mod mirror_actuator_mapping {
    // @@protoc_insertion_point(message:ltpb.MirrorActuatorMapping.ActuatorAnglePair)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct ActuatorAnglePair {
        // message fields
        // @@protoc_insertion_point(field:ltpb.MirrorActuatorMapping.ActuatorAnglePair.hall_code)
        pub hall_code: ::std::option::Option<i32>,
        // @@protoc_insertion_point(field:ltpb.MirrorActuatorMapping.ActuatorAnglePair.angle)
        pub angle: ::std::option::Option<f32>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.MirrorActuatorMapping.ActuatorAnglePair.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a ActuatorAnglePair {
        fn default() -> &'a ActuatorAnglePair {
            <ActuatorAnglePair as ::protobuf::Message>::default_instance()
        }
    }

    impl ActuatorAnglePair {
        pub fn new() -> ActuatorAnglePair {
            ::std::default::Default::default()
        }

        // optional int32 hall_code = 1;

        pub fn hall_code(&self) -> i32 {
            self.hall_code.unwrap_or(0)
        }

        pub fn clear_hall_code(&mut self) {
            self.hall_code = ::std::option::Option::None;
        }

        pub fn has_hall_code(&self) -> bool {
            self.hall_code.is_some()
        }

        // Param is passed by value, moved
        pub fn set_hall_code(&mut self, v: i32) {
            self.hall_code = ::std::option::Option::Some(v);
        }

        // optional float angle = 2;

        pub fn angle(&self) -> f32 {
            self.angle.unwrap_or(0.)
        }

        pub fn clear_angle(&mut self) {
            self.angle = ::std::option::Option::None;
        }

        pub fn has_angle(&self) -> bool {
            self.angle.is_some()
        }

        // Param is passed by value, moved
        pub fn set_angle(&mut self, v: f32) {
            self.angle = ::std::option::Option::Some(v);
        }
    }

    impl ::protobuf::Message for ActuatorAnglePair {
        const NAME: &'static str = "ActuatorAnglePair";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    8 => {
                        self.hall_code = ::std::option::Option::Some(is.read_int32()?);
                    },
                    21 => {
                        self.angle = ::std::option::Option::Some(is.read_float()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.hall_code {
                my_size += ::protobuf::rt::int32_size(1, v);
            }
            if let Some(v) = self.angle {
                my_size += 1 + 4;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.hall_code {
                os.write_int32(1, v)?;
            }
            if let Some(v) = self.angle {
                os.write_float(2, v)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> ActuatorAnglePair {
            ActuatorAnglePair::new()
        }

        fn clear(&mut self) {
            self.hall_code = ::std::option::Option::None;
            self.angle = ::std::option::Option::None;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static ActuatorAnglePair {
            static instance: ActuatorAnglePair = ActuatorAnglePair {
                hall_code: ::std::option::Option::None,
                angle: ::std::option::Option::None,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    // @@protoc_insertion_point(message:ltpb.MirrorActuatorMapping.QuadraticModel)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct QuadraticModel {
        // message fields
        // @@protoc_insertion_point(field:ltpb.MirrorActuatorMapping.QuadraticModel.use_rplus_for_left_segment)
        pub use_rplus_for_left_segment: ::std::option::Option<bool>,
        // @@protoc_insertion_point(field:ltpb.MirrorActuatorMapping.QuadraticModel.use_rplus_for_right_segment)
        pub use_rplus_for_right_segment: ::std::option::Option<bool>,
        // @@protoc_insertion_point(field:ltpb.MirrorActuatorMapping.QuadraticModel.inflection_value)
        pub inflection_value: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.MirrorActuatorMapping.QuadraticModel.model_coeffs)
        pub model_coeffs: ::std::vec::Vec<f32>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.MirrorActuatorMapping.QuadraticModel.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a QuadraticModel {
        fn default() -> &'a QuadraticModel {
            <QuadraticModel as ::protobuf::Message>::default_instance()
        }
    }

    impl QuadraticModel {
        pub fn new() -> QuadraticModel {
            ::std::default::Default::default()
        }

        // optional bool use_rplus_for_left_segment = 1;

        pub fn use_rplus_for_left_segment(&self) -> bool {
            self.use_rplus_for_left_segment.unwrap_or(false)
        }

        pub fn clear_use_rplus_for_left_segment(&mut self) {
            self.use_rplus_for_left_segment = ::std::option::Option::None;
        }

        pub fn has_use_rplus_for_left_segment(&self) -> bool {
            self.use_rplus_for_left_segment.is_some()
        }

        // Param is passed by value, moved
        pub fn set_use_rplus_for_left_segment(&mut self, v: bool) {
            self.use_rplus_for_left_segment = ::std::option::Option::Some(v);
        }

        // optional bool use_rplus_for_right_segment = 2;

        pub fn use_rplus_for_right_segment(&self) -> bool {
            self.use_rplus_for_right_segment.unwrap_or(false)
        }

        pub fn clear_use_rplus_for_right_segment(&mut self) {
            self.use_rplus_for_right_segment = ::std::option::Option::None;
        }

        pub fn has_use_rplus_for_right_segment(&self) -> bool {
            self.use_rplus_for_right_segment.is_some()
        }

        // Param is passed by value, moved
        pub fn set_use_rplus_for_right_segment(&mut self, v: bool) {
            self.use_rplus_for_right_segment = ::std::option::Option::Some(v);
        }

        // optional float inflection_value = 3;

        pub fn inflection_value(&self) -> f32 {
            self.inflection_value.unwrap_or(0.)
        }

        pub fn clear_inflection_value(&mut self) {
            self.inflection_value = ::std::option::Option::None;
        }

        pub fn has_inflection_value(&self) -> bool {
            self.inflection_value.is_some()
        }

        // Param is passed by value, moved
        pub fn set_inflection_value(&mut self, v: f32) {
            self.inflection_value = ::std::option::Option::Some(v);
        }
    }

    impl ::protobuf::Message for QuadraticModel {
        const NAME: &'static str = "QuadraticModel";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    8 => {
                        self.use_rplus_for_left_segment = ::std::option::Option::Some(is.read_bool()?);
                    },
                    16 => {
                        self.use_rplus_for_right_segment = ::std::option::Option::Some(is.read_bool()?);
                    },
                    29 => {
                        self.inflection_value = ::std::option::Option::Some(is.read_float()?);
                    },
                    34 => {
                        is.read_repeated_packed_float_into(&mut self.model_coeffs)?;
                    },
                    37 => {
                        self.model_coeffs.push(is.read_float()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.use_rplus_for_left_segment {
                my_size += 1 + 1;
            }
            if let Some(v) = self.use_rplus_for_right_segment {
                my_size += 1 + 1;
            }
            if let Some(v) = self.inflection_value {
                my_size += 1 + 4;
            }
            my_size += ::protobuf::rt::vec_packed_float_size(4, &self.model_coeffs);
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.use_rplus_for_left_segment {
                os.write_bool(1, v)?;
            }
            if let Some(v) = self.use_rplus_for_right_segment {
                os.write_bool(2, v)?;
            }
            if let Some(v) = self.inflection_value {
                os.write_float(3, v)?;
            }
            os.write_repeated_packed_float(4, &self.model_coeffs)?;
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> QuadraticModel {
            QuadraticModel::new()
        }

        fn clear(&mut self) {
            self.use_rplus_for_left_segment = ::std::option::Option::None;
            self.use_rplus_for_right_segment = ::std::option::Option::None;
            self.inflection_value = ::std::option::Option::None;
            self.model_coeffs.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static QuadraticModel {
            static instance: QuadraticModel = QuadraticModel {
                use_rplus_for_left_segment: ::std::option::Option::None,
                use_rplus_for_right_segment: ::std::option::Option::None,
                inflection_value: ::std::option::Option::None,
                model_coeffs: ::std::vec::Vec::new(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.MirrorActuatorMapping.TransformationType)
    pub enum TransformationType {
        // @@protoc_insertion_point(enum_value:ltpb.MirrorActuatorMapping.TransformationType.MEAN_STD_NORMALIZE)
        MEAN_STD_NORMALIZE = 0,
        // @@protoc_insertion_point(enum_value:ltpb.MirrorActuatorMapping.TransformationType.TAN_HALF_THETA)
        TAN_HALF_THETA = 1,
    }

    impl ::protobuf::Enum for TransformationType {
        const NAME: &'static str = "TransformationType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<TransformationType> {
            match value {
                0 => ::std::option::Option::Some(TransformationType::MEAN_STD_NORMALIZE),
                1 => ::std::option::Option::Some(TransformationType::TAN_HALF_THETA),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<TransformationType> {
            match str {
                "MEAN_STD_NORMALIZE" => ::std::option::Option::Some(TransformationType::MEAN_STD_NORMALIZE),
                "TAN_HALF_THETA" => ::std::option::Option::Some(TransformationType::TAN_HALF_THETA),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [TransformationType] = &[
            TransformationType::MEAN_STD_NORMALIZE,
            TransformationType::TAN_HALF_THETA,
        ];
    }

    impl ::std::default::Default for TransformationType {
        fn default() -> Self {
            TransformationType::MEAN_STD_NORMALIZE
        }
    }

}
