// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `proximity_sensors.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

// @@protoc_insertion_point(message:ltpb.ProximitySensors)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ProximitySensors {
    // message fields
    // @@protoc_insertion_point(field:ltpb.ProximitySensors.sensor_1)
    pub sensor_1: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:ltpb.ProximitySensors.sensor_2)
    pub sensor_2: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:ltpb.ProximitySensors.sensor_3)
    pub sensor_3: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:ltpb.ProximitySensors.sensor_4)
    pub sensor_4: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:ltpb.ProximitySensors.sensor_5)
    pub sensor_5: ::std::option::Option<bool>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.ProximitySensors.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ProximitySensors {
    fn default() -> &'a ProximitySensors {
        <ProximitySensors as ::protobuf::Message>::default_instance()
    }
}

impl ProximitySensors {
    pub fn new() -> ProximitySensors {
        ::std::default::Default::default()
    }

    // optional bool sensor_1 = 1;

    pub fn sensor_1(&self) -> bool {
        self.sensor_1.unwrap_or(false)
    }

    pub fn clear_sensor_1(&mut self) {
        self.sensor_1 = ::std::option::Option::None;
    }

    pub fn has_sensor_1(&self) -> bool {
        self.sensor_1.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_1(&mut self, v: bool) {
        self.sensor_1 = ::std::option::Option::Some(v);
    }

    // optional bool sensor_2 = 2;

    pub fn sensor_2(&self) -> bool {
        self.sensor_2.unwrap_or(false)
    }

    pub fn clear_sensor_2(&mut self) {
        self.sensor_2 = ::std::option::Option::None;
    }

    pub fn has_sensor_2(&self) -> bool {
        self.sensor_2.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_2(&mut self, v: bool) {
        self.sensor_2 = ::std::option::Option::Some(v);
    }

    // optional bool sensor_3 = 3;

    pub fn sensor_3(&self) -> bool {
        self.sensor_3.unwrap_or(false)
    }

    pub fn clear_sensor_3(&mut self) {
        self.sensor_3 = ::std::option::Option::None;
    }

    pub fn has_sensor_3(&self) -> bool {
        self.sensor_3.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_3(&mut self, v: bool) {
        self.sensor_3 = ::std::option::Option::Some(v);
    }

    // optional bool sensor_4 = 4;

    pub fn sensor_4(&self) -> bool {
        self.sensor_4.unwrap_or(false)
    }

    pub fn clear_sensor_4(&mut self) {
        self.sensor_4 = ::std::option::Option::None;
    }

    pub fn has_sensor_4(&self) -> bool {
        self.sensor_4.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_4(&mut self, v: bool) {
        self.sensor_4 = ::std::option::Option::Some(v);
    }

    // optional bool sensor_5 = 5;

    pub fn sensor_5(&self) -> bool {
        self.sensor_5.unwrap_or(false)
    }

    pub fn clear_sensor_5(&mut self) {
        self.sensor_5 = ::std::option::Option::None;
    }

    pub fn has_sensor_5(&self) -> bool {
        self.sensor_5.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sensor_5(&mut self, v: bool) {
        self.sensor_5 = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for ProximitySensors {
    const NAME: &'static str = "ProximitySensors";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.sensor_1 = ::std::option::Option::Some(is.read_bool()?);
                },
                16 => {
                    self.sensor_2 = ::std::option::Option::Some(is.read_bool()?);
                },
                24 => {
                    self.sensor_3 = ::std::option::Option::Some(is.read_bool()?);
                },
                32 => {
                    self.sensor_4 = ::std::option::Option::Some(is.read_bool()?);
                },
                40 => {
                    self.sensor_5 = ::std::option::Option::Some(is.read_bool()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.sensor_1 {
            my_size += 1 + 1;
        }
        if let Some(v) = self.sensor_2 {
            my_size += 1 + 1;
        }
        if let Some(v) = self.sensor_3 {
            my_size += 1 + 1;
        }
        if let Some(v) = self.sensor_4 {
            my_size += 1 + 1;
        }
        if let Some(v) = self.sensor_5 {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.sensor_1 {
            os.write_bool(1, v)?;
        }
        if let Some(v) = self.sensor_2 {
            os.write_bool(2, v)?;
        }
        if let Some(v) = self.sensor_3 {
            os.write_bool(3, v)?;
        }
        if let Some(v) = self.sensor_4 {
            os.write_bool(4, v)?;
        }
        if let Some(v) = self.sensor_5 {
            os.write_bool(5, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ProximitySensors {
        ProximitySensors::new()
    }

    fn clear(&mut self) {
        self.sensor_1 = ::std::option::Option::None;
        self.sensor_2 = ::std::option::Option::None;
        self.sensor_3 = ::std::option::Option::None;
        self.sensor_4 = ::std::option::Option::None;
        self.sensor_5 = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ProximitySensors {
        static instance: ProximitySensors = ProximitySensors {
            sensor_1: ::std::option::Option::None,
            sensor_2: ::std::option::Option::None,
            sensor_3: ::std::option::Option::None,
            sensor_4: ::std::option::Option::None,
            sensor_5: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}
