// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `sensor_type.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:ltpb.SensorType)
pub enum SensorType {
    // @@protoc_insertion_point(enum_value:ltpb.SensorType.SENSOR_UNKNOWN)
    SENSOR_UNKNOWN = 0,
    // @@protoc_insertion_point(enum_value:ltpb.SensorType.SENSOR_AR835)
    SENSOR_AR835 = 1,
    // @@protoc_insertion_point(enum_value:ltpb.SensorType.SENSOR_AR1335)
    SENSOR_AR1335 = 2,
    // @@protoc_insertion_point(enum_value:ltpb.SensorType.SENSOR_AR1335_MONO)
    SENSOR_AR1335_MONO = 3,
    // @@protoc_insertion_point(enum_value:ltpb.SensorType.SENSOR_IMX386)
    SENSOR_IMX386 = 4,
    // @@protoc_insertion_point(enum_value:ltpb.SensorType.SENSOR_IMX386_MONO)
    SENSOR_IMX386_MONO = 5,
}

impl ::protobuf::Enum for SensorType {
    const NAME: &'static str = "SensorType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<SensorType> {
        match value {
            0 => ::std::option::Option::Some(SensorType::SENSOR_UNKNOWN),
            1 => ::std::option::Option::Some(SensorType::SENSOR_AR835),
            2 => ::std::option::Option::Some(SensorType::SENSOR_AR1335),
            3 => ::std::option::Option::Some(SensorType::SENSOR_AR1335_MONO),
            4 => ::std::option::Option::Some(SensorType::SENSOR_IMX386),
            5 => ::std::option::Option::Some(SensorType::SENSOR_IMX386_MONO),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<SensorType> {
        match str {
            "SENSOR_UNKNOWN" => ::std::option::Option::Some(SensorType::SENSOR_UNKNOWN),
            "SENSOR_AR835" => ::std::option::Option::Some(SensorType::SENSOR_AR835),
            "SENSOR_AR1335" => ::std::option::Option::Some(SensorType::SENSOR_AR1335),
            "SENSOR_AR1335_MONO" => ::std::option::Option::Some(SensorType::SENSOR_AR1335_MONO),
            "SENSOR_IMX386" => ::std::option::Option::Some(SensorType::SENSOR_IMX386),
            "SENSOR_IMX386_MONO" => ::std::option::Option::Some(SensorType::SENSOR_IMX386_MONO),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [SensorType] = &[
        SensorType::SENSOR_UNKNOWN,
        SensorType::SENSOR_AR835,
        SensorType::SENSOR_AR1335,
        SensorType::SENSOR_AR1335_MONO,
        SensorType::SENSOR_IMX386,
        SensorType::SENSOR_IMX386_MONO,
    ];
}

impl ::std::default::Default for SensorType {
    fn default() -> Self {
        SensorType::SENSOR_UNKNOWN
    }
}

