// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `sensor_characterization.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

// @@protoc_insertion_point(message:ltpb.SensorCharacterization)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SensorCharacterization {
    // message fields
    // @@protoc_insertion_point(field:ltpb.SensorCharacterization.black_level)
    pub black_level: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.SensorCharacterization.white_level)
    pub white_level: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.SensorCharacterization.cliff_slope)
    pub cliff_slope: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.SensorCharacterization.vst_model)
    pub vst_model: ::std::vec::Vec<sensor_characterization::VstNoiseModel>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.SensorCharacterization.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SensorCharacterization {
    fn default() -> &'a SensorCharacterization {
        <SensorCharacterization as ::protobuf::Message>::default_instance()
    }
}

impl SensorCharacterization {
    pub fn new() -> SensorCharacterization {
        ::std::default::Default::default()
    }

    // optional float black_level = 1;

    pub fn black_level(&self) -> f32 {
        self.black_level.unwrap_or(0.)
    }

    pub fn clear_black_level(&mut self) {
        self.black_level = ::std::option::Option::None;
    }

    pub fn has_black_level(&self) -> bool {
        self.black_level.is_some()
    }

    // Param is passed by value, moved
    pub fn set_black_level(&mut self, v: f32) {
        self.black_level = ::std::option::Option::Some(v);
    }

    // optional float white_level = 2;

    pub fn white_level(&self) -> f32 {
        self.white_level.unwrap_or(0.)
    }

    pub fn clear_white_level(&mut self) {
        self.white_level = ::std::option::Option::None;
    }

    pub fn has_white_level(&self) -> bool {
        self.white_level.is_some()
    }

    // Param is passed by value, moved
    pub fn set_white_level(&mut self, v: f32) {
        self.white_level = ::std::option::Option::Some(v);
    }

    // optional float cliff_slope = 3;

    pub fn cliff_slope(&self) -> f32 {
        self.cliff_slope.unwrap_or(0.)
    }

    pub fn clear_cliff_slope(&mut self) {
        self.cliff_slope = ::std::option::Option::None;
    }

    pub fn has_cliff_slope(&self) -> bool {
        self.cliff_slope.is_some()
    }

    // Param is passed by value, moved
    pub fn set_cliff_slope(&mut self, v: f32) {
        self.cliff_slope = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for SensorCharacterization {
    const NAME: &'static str = "SensorCharacterization";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                13 => {
                    self.black_level = ::std::option::Option::Some(is.read_float()?);
                },
                21 => {
                    self.white_level = ::std::option::Option::Some(is.read_float()?);
                },
                29 => {
                    self.cliff_slope = ::std::option::Option::Some(is.read_float()?);
                },
                34 => {
                    self.vst_model.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.black_level {
            my_size += 1 + 4;
        }
        if let Some(v) = self.white_level {
            my_size += 1 + 4;
        }
        if let Some(v) = self.cliff_slope {
            my_size += 1 + 4;
        }
        for value in &self.vst_model {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.black_level {
            os.write_float(1, v)?;
        }
        if let Some(v) = self.white_level {
            os.write_float(2, v)?;
        }
        if let Some(v) = self.cliff_slope {
            os.write_float(3, v)?;
        }
        for v in &self.vst_model {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SensorCharacterization {
        SensorCharacterization::new()
    }

    fn clear(&mut self) {
        self.black_level = ::std::option::Option::None;
        self.white_level = ::std::option::Option::None;
        self.cliff_slope = ::std::option::Option::None;
        self.vst_model.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SensorCharacterization {
        static instance: SensorCharacterization = SensorCharacterization {
            black_level: ::std::option::Option::None,
            white_level: ::std::option::Option::None,
            cliff_slope: ::std::option::Option::None,
            vst_model: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

/// Nested message and enums of message `SensorCharacterization`
pub mod sensor_characterization {
    // @@protoc_insertion_point(message:ltpb.SensorCharacterization.VstNoiseModel)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct VstNoiseModel {
        // message fields
        // @@protoc_insertion_point(field:ltpb.SensorCharacterization.VstNoiseModel.gain)
        pub gain: ::std::option::Option<u32>,
        // @@protoc_insertion_point(field:ltpb.SensorCharacterization.VstNoiseModel.threshold)
        pub threshold: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.SensorCharacterization.VstNoiseModel.scale)
        pub scale: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.SensorCharacterization.VstNoiseModel.red)
        pub red: ::protobuf::MessageField<vst_noise_model::VstModel>,
        // @@protoc_insertion_point(field:ltpb.SensorCharacterization.VstNoiseModel.green)
        pub green: ::protobuf::MessageField<vst_noise_model::VstModel>,
        // @@protoc_insertion_point(field:ltpb.SensorCharacterization.VstNoiseModel.blue)
        pub blue: ::protobuf::MessageField<vst_noise_model::VstModel>,
        // @@protoc_insertion_point(field:ltpb.SensorCharacterization.VstNoiseModel.panchromatic)
        pub panchromatic: ::protobuf::MessageField<vst_noise_model::VstModel>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.SensorCharacterization.VstNoiseModel.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a VstNoiseModel {
        fn default() -> &'a VstNoiseModel {
            <VstNoiseModel as ::protobuf::Message>::default_instance()
        }
    }

    impl VstNoiseModel {
        pub fn new() -> VstNoiseModel {
            ::std::default::Default::default()
        }

        // optional uint32 gain = 1;

        pub fn gain(&self) -> u32 {
            self.gain.unwrap_or(0)
        }

        pub fn clear_gain(&mut self) {
            self.gain = ::std::option::Option::None;
        }

        pub fn has_gain(&self) -> bool {
            self.gain.is_some()
        }

        // Param is passed by value, moved
        pub fn set_gain(&mut self, v: u32) {
            self.gain = ::std::option::Option::Some(v);
        }

        // optional float threshold = 2;

        pub fn threshold(&self) -> f32 {
            self.threshold.unwrap_or(0.)
        }

        pub fn clear_threshold(&mut self) {
            self.threshold = ::std::option::Option::None;
        }

        pub fn has_threshold(&self) -> bool {
            self.threshold.is_some()
        }

        // Param is passed by value, moved
        pub fn set_threshold(&mut self, v: f32) {
            self.threshold = ::std::option::Option::Some(v);
        }

        // optional float scale = 3;

        pub fn scale(&self) -> f32 {
            self.scale.unwrap_or(0.)
        }

        pub fn clear_scale(&mut self) {
            self.scale = ::std::option::Option::None;
        }

        pub fn has_scale(&self) -> bool {
            self.scale.is_some()
        }

        // Param is passed by value, moved
        pub fn set_scale(&mut self, v: f32) {
            self.scale = ::std::option::Option::Some(v);
        }
    }

    impl ::protobuf::Message for VstNoiseModel {
        const NAME: &'static str = "VstNoiseModel";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    8 => {
                        self.gain = ::std::option::Option::Some(is.read_uint32()?);
                    },
                    21 => {
                        self.threshold = ::std::option::Option::Some(is.read_float()?);
                    },
                    29 => {
                        self.scale = ::std::option::Option::Some(is.read_float()?);
                    },
                    34 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.red)?;
                    },
                    42 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.green)?;
                    },
                    50 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.blue)?;
                    },
                    58 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.panchromatic)?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.gain {
                my_size += ::protobuf::rt::uint32_size(1, v);
            }
            if let Some(v) = self.threshold {
                my_size += 1 + 4;
            }
            if let Some(v) = self.scale {
                my_size += 1 + 4;
            }
            if let Some(v) = self.red.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.green.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.blue.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.panchromatic.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.gain {
                os.write_uint32(1, v)?;
            }
            if let Some(v) = self.threshold {
                os.write_float(2, v)?;
            }
            if let Some(v) = self.scale {
                os.write_float(3, v)?;
            }
            if let Some(v) = self.red.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
            }
            if let Some(v) = self.green.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
            }
            if let Some(v) = self.blue.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
            }
            if let Some(v) = self.panchromatic.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> VstNoiseModel {
            VstNoiseModel::new()
        }

        fn clear(&mut self) {
            self.gain = ::std::option::Option::None;
            self.threshold = ::std::option::Option::None;
            self.scale = ::std::option::Option::None;
            self.red.clear();
            self.green.clear();
            self.blue.clear();
            self.panchromatic.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static VstNoiseModel {
            static instance: VstNoiseModel = VstNoiseModel {
                gain: ::std::option::Option::None,
                threshold: ::std::option::Option::None,
                scale: ::std::option::Option::None,
                red: ::protobuf::MessageField::none(),
                green: ::protobuf::MessageField::none(),
                blue: ::protobuf::MessageField::none(),
                panchromatic: ::protobuf::MessageField::none(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    /// Nested message and enums of message `VstNoiseModel`
    pub mod vst_noise_model {
        // @@protoc_insertion_point(message:ltpb.SensorCharacterization.VstNoiseModel.VstModel)
        #[derive(PartialEq,Clone,Default,Debug)]
        pub struct VstModel {
            // message fields
            // @@protoc_insertion_point(field:ltpb.SensorCharacterization.VstNoiseModel.VstModel.a)
            pub a: ::std::option::Option<f32>,
            // @@protoc_insertion_point(field:ltpb.SensorCharacterization.VstNoiseModel.VstModel.b)
            pub b: ::std::option::Option<f32>,
            // special fields
            // @@protoc_insertion_point(special_field:ltpb.SensorCharacterization.VstNoiseModel.VstModel.special_fields)
            pub special_fields: ::protobuf::SpecialFields,
        }

        impl<'a> ::std::default::Default for &'a VstModel {
            fn default() -> &'a VstModel {
                <VstModel as ::protobuf::Message>::default_instance()
            }
        }

        impl VstModel {
            pub fn new() -> VstModel {
                ::std::default::Default::default()
            }

            // optional float a = 1;

            pub fn a(&self) -> f32 {
                self.a.unwrap_or(0.)
            }

            pub fn clear_a(&mut self) {
                self.a = ::std::option::Option::None;
            }

            pub fn has_a(&self) -> bool {
                self.a.is_some()
            }

            // Param is passed by value, moved
            pub fn set_a(&mut self, v: f32) {
                self.a = ::std::option::Option::Some(v);
            }

            // optional float b = 2;

            pub fn b(&self) -> f32 {
                self.b.unwrap_or(0.)
            }

            pub fn clear_b(&mut self) {
                self.b = ::std::option::Option::None;
            }

            pub fn has_b(&self) -> bool {
                self.b.is_some()
            }

            // Param is passed by value, moved
            pub fn set_b(&mut self, v: f32) {
                self.b = ::std::option::Option::Some(v);
            }
        }

        impl ::protobuf::Message for VstModel {
            const NAME: &'static str = "VstModel";

            fn is_initialized(&self) -> bool {
                true
            }

            fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
                while let Some(tag) = is.read_raw_tag_or_eof()? {
                    match tag {
                        13 => {
                            self.a = ::std::option::Option::Some(is.read_float()?);
                        },
                        21 => {
                            self.b = ::std::option::Option::Some(is.read_float()?);
                        },
                        tag => {
                            ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                        },
                    };
                }
                ::std::result::Result::Ok(())
            }

            // Compute sizes of nested messages
            #[allow(unused_variables)]
            fn compute_size(&self) -> u64 {
                let mut my_size = 0;
                if let Some(v) = self.a {
                    my_size += 1 + 4;
                }
                if let Some(v) = self.b {
                    my_size += 1 + 4;
                }
                my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
                self.special_fields.cached_size().set(my_size as u32);
                my_size
            }

            fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
                if let Some(v) = self.a {
                    os.write_float(1, v)?;
                }
                if let Some(v) = self.b {
                    os.write_float(2, v)?;
                }
                os.write_unknown_fields(self.special_fields.unknown_fields())?;
                ::std::result::Result::Ok(())
            }

            fn special_fields(&self) -> &::protobuf::SpecialFields {
                &self.special_fields
            }

            fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
                &mut self.special_fields
            }

            fn new() -> VstModel {
                VstModel::new()
            }

            fn clear(&mut self) {
                self.a = ::std::option::Option::None;
                self.b = ::std::option::Option::None;
                self.special_fields.clear();
            }

            fn default_instance() -> &'static VstModel {
                static instance: VstModel = VstModel {
                    a: ::std::option::Option::None,
                    b: ::std::option::Option::None,
                    special_fields: ::protobuf::SpecialFields::new(),
                };
                &instance
            }
        }
    }
}
