// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `time_stamp.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

// @@protoc_insertion_point(message:ltpb.TimeStamp)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TimeStamp {
    // message fields
    // @@protoc_insertion_point(field:ltpb.TimeStamp.year)
    pub year: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:ltpb.TimeStamp.month)
    pub month: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:ltpb.TimeStamp.day)
    pub day: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:ltpb.TimeStamp.hour)
    pub hour: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:ltpb.TimeStamp.minute)
    pub minute: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:ltpb.TimeStamp.second)
    pub second: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:ltpb.TimeStamp.tz_offset)
    pub tz_offset: ::std::option::Option<i32>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.TimeStamp.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TimeStamp {
    fn default() -> &'a TimeStamp {
        <TimeStamp as ::protobuf::Message>::default_instance()
    }
}

impl TimeStamp {
    pub fn new() -> TimeStamp {
        ::std::default::Default::default()
    }

    // optional uint32 year = 1;

    pub fn year(&self) -> u32 {
        self.year.unwrap_or(0)
    }

    pub fn clear_year(&mut self) {
        self.year = ::std::option::Option::None;
    }

    pub fn has_year(&self) -> bool {
        self.year.is_some()
    }

    // Param is passed by value, moved
    pub fn set_year(&mut self, v: u32) {
        self.year = ::std::option::Option::Some(v);
    }

    // optional uint32 month = 2;

    pub fn month(&self) -> u32 {
        self.month.unwrap_or(0)
    }

    pub fn clear_month(&mut self) {
        self.month = ::std::option::Option::None;
    }

    pub fn has_month(&self) -> bool {
        self.month.is_some()
    }

    // Param is passed by value, moved
    pub fn set_month(&mut self, v: u32) {
        self.month = ::std::option::Option::Some(v);
    }

    // optional uint32 day = 3;

    pub fn day(&self) -> u32 {
        self.day.unwrap_or(0)
    }

    pub fn clear_day(&mut self) {
        self.day = ::std::option::Option::None;
    }

    pub fn has_day(&self) -> bool {
        self.day.is_some()
    }

    // Param is passed by value, moved
    pub fn set_day(&mut self, v: u32) {
        self.day = ::std::option::Option::Some(v);
    }

    // optional uint32 hour = 4;

    pub fn hour(&self) -> u32 {
        self.hour.unwrap_or(0)
    }

    pub fn clear_hour(&mut self) {
        self.hour = ::std::option::Option::None;
    }

    pub fn has_hour(&self) -> bool {
        self.hour.is_some()
    }

    // Param is passed by value, moved
    pub fn set_hour(&mut self, v: u32) {
        self.hour = ::std::option::Option::Some(v);
    }

    // optional uint32 minute = 5;

    pub fn minute(&self) -> u32 {
        self.minute.unwrap_or(0)
    }

    pub fn clear_minute(&mut self) {
        self.minute = ::std::option::Option::None;
    }

    pub fn has_minute(&self) -> bool {
        self.minute.is_some()
    }

    // Param is passed by value, moved
    pub fn set_minute(&mut self, v: u32) {
        self.minute = ::std::option::Option::Some(v);
    }

    // optional uint32 second = 6;

    pub fn second(&self) -> u32 {
        self.second.unwrap_or(0)
    }

    pub fn clear_second(&mut self) {
        self.second = ::std::option::Option::None;
    }

    pub fn has_second(&self) -> bool {
        self.second.is_some()
    }

    // Param is passed by value, moved
    pub fn set_second(&mut self, v: u32) {
        self.second = ::std::option::Option::Some(v);
    }

    // optional sint32 tz_offset = 7;

    pub fn tz_offset(&self) -> i32 {
        self.tz_offset.unwrap_or(0)
    }

    pub fn clear_tz_offset(&mut self) {
        self.tz_offset = ::std::option::Option::None;
    }

    pub fn has_tz_offset(&self) -> bool {
        self.tz_offset.is_some()
    }

    // Param is passed by value, moved
    pub fn set_tz_offset(&mut self, v: i32) {
        self.tz_offset = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for TimeStamp {
    const NAME: &'static str = "TimeStamp";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.year = ::std::option::Option::Some(is.read_uint32()?);
                },
                16 => {
                    self.month = ::std::option::Option::Some(is.read_uint32()?);
                },
                24 => {
                    self.day = ::std::option::Option::Some(is.read_uint32()?);
                },
                32 => {
                    self.hour = ::std::option::Option::Some(is.read_uint32()?);
                },
                40 => {
                    self.minute = ::std::option::Option::Some(is.read_uint32()?);
                },
                48 => {
                    self.second = ::std::option::Option::Some(is.read_uint32()?);
                },
                56 => {
                    self.tz_offset = ::std::option::Option::Some(is.read_sint32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.year {
            my_size += ::protobuf::rt::uint32_size(1, v);
        }
        if let Some(v) = self.month {
            my_size += ::protobuf::rt::uint32_size(2, v);
        }
        if let Some(v) = self.day {
            my_size += ::protobuf::rt::uint32_size(3, v);
        }
        if let Some(v) = self.hour {
            my_size += ::protobuf::rt::uint32_size(4, v);
        }
        if let Some(v) = self.minute {
            my_size += ::protobuf::rt::uint32_size(5, v);
        }
        if let Some(v) = self.second {
            my_size += ::protobuf::rt::uint32_size(6, v);
        }
        if let Some(v) = self.tz_offset {
            my_size += ::protobuf::rt::sint32_size(7, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.year {
            os.write_uint32(1, v)?;
        }
        if let Some(v) = self.month {
            os.write_uint32(2, v)?;
        }
        if let Some(v) = self.day {
            os.write_uint32(3, v)?;
        }
        if let Some(v) = self.hour {
            os.write_uint32(4, v)?;
        }
        if let Some(v) = self.minute {
            os.write_uint32(5, v)?;
        }
        if let Some(v) = self.second {
            os.write_uint32(6, v)?;
        }
        if let Some(v) = self.tz_offset {
            os.write_sint32(7, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TimeStamp {
        TimeStamp::new()
    }

    fn clear(&mut self) {
        self.year = ::std::option::Option::None;
        self.month = ::std::option::Option::None;
        self.day = ::std::option::Option::None;
        self.hour = ::std::option::Option::None;
        self.minute = ::std::option::Option::None;
        self.second = ::std::option::Option::None;
        self.tz_offset = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TimeStamp {
        static instance: TimeStamp = TimeStamp {
            year: ::std::option::Option::None,
            month: ::std::option::Option::None,
            day: ::std::option::Option::None,
            hour: ::std::option::Option::None,
            minute: ::std::option::Option::None,
            second: ::std::option::Option::None,
            tz_offset: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}
