// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `view_preferences.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

// @@protoc_insertion_point(message:ltpb.ViewPreferences)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ViewPreferences {
    // message fields
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.f_number)
    pub f_number: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.ev_offset)
    pub ev_offset: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.disable_cropping)
    pub disable_cropping: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.hdr_mode)
    pub hdr_mode: ::std::option::Option<::protobuf::EnumOrUnknown<view_preferences::HDRMode>>,
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.view_preset)
    pub view_preset: ::std::option::Option<::protobuf::EnumOrUnknown<view_preferences::ViewPresets>>,
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.scene_mode)
    pub scene_mode: ::std::option::Option<::protobuf::EnumOrUnknown<view_preferences::SceneMode>>,
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.awb_mode)
    pub awb_mode: ::std::option::Option<::protobuf::EnumOrUnknown<view_preferences::AWBMode>>,
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.orientation)
    pub orientation: ::std::option::Option<::protobuf::EnumOrUnknown<view_preferences::Orientation>>,
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.image_gain)
    pub image_gain: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.image_integration_time_ns)
    pub image_integration_time_ns: ::std::option::Option<u64>,
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.user_rating)
    pub user_rating: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.aspect_ratio)
    pub aspect_ratio: ::std::option::Option<::protobuf::EnumOrUnknown<view_preferences::AspectRatio>>,
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.crop)
    pub crop: ::protobuf::MessageField<view_preferences::Crop>,
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.awb_gains)
    pub awb_gains: ::protobuf::MessageField<view_preferences::ChannelGain>,
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.is_on_tripod)
    pub is_on_tripod: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.qc_lux_index)
    pub qc_lux_index: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.display_gain)
    pub display_gain: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.ViewPreferences.display_integration_time_ns)
    pub display_integration_time_ns: ::std::option::Option<u64>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.ViewPreferences.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ViewPreferences {
    fn default() -> &'a ViewPreferences {
        <ViewPreferences as ::protobuf::Message>::default_instance()
    }
}

impl ViewPreferences {
    pub fn new() -> ViewPreferences {
        ::std::default::Default::default()
    }

    // optional float f_number = 1;

    pub fn f_number(&self) -> f32 {
        self.f_number.unwrap_or(0.)
    }

    pub fn clear_f_number(&mut self) {
        self.f_number = ::std::option::Option::None;
    }

    pub fn has_f_number(&self) -> bool {
        self.f_number.is_some()
    }

    // Param is passed by value, moved
    pub fn set_f_number(&mut self, v: f32) {
        self.f_number = ::std::option::Option::Some(v);
    }

    // optional float ev_offset = 2;

    pub fn ev_offset(&self) -> f32 {
        self.ev_offset.unwrap_or(0.)
    }

    pub fn clear_ev_offset(&mut self) {
        self.ev_offset = ::std::option::Option::None;
    }

    pub fn has_ev_offset(&self) -> bool {
        self.ev_offset.is_some()
    }

    // Param is passed by value, moved
    pub fn set_ev_offset(&mut self, v: f32) {
        self.ev_offset = ::std::option::Option::Some(v);
    }

    // optional bool disable_cropping = 3;

    pub fn disable_cropping(&self) -> bool {
        self.disable_cropping.unwrap_or(false)
    }

    pub fn clear_disable_cropping(&mut self) {
        self.disable_cropping = ::std::option::Option::None;
    }

    pub fn has_disable_cropping(&self) -> bool {
        self.disable_cropping.is_some()
    }

    // Param is passed by value, moved
    pub fn set_disable_cropping(&mut self, v: bool) {
        self.disable_cropping = ::std::option::Option::Some(v);
    }

    // optional .ltpb.ViewPreferences.HDRMode hdr_mode = 4;

    pub fn hdr_mode(&self) -> view_preferences::HDRMode {
        match self.hdr_mode {
            Some(e) => e.enum_value_or(view_preferences::HDRMode::HDR_MODE_NONE),
            None => view_preferences::HDRMode::HDR_MODE_NONE,
        }
    }

    pub fn clear_hdr_mode(&mut self) {
        self.hdr_mode = ::std::option::Option::None;
    }

    pub fn has_hdr_mode(&self) -> bool {
        self.hdr_mode.is_some()
    }

    // Param is passed by value, moved
    pub fn set_hdr_mode(&mut self, v: view_preferences::HDRMode) {
        self.hdr_mode = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional .ltpb.ViewPreferences.ViewPresets view_preset = 5;

    pub fn view_preset(&self) -> view_preferences::ViewPresets {
        match self.view_preset {
            Some(e) => e.enum_value_or(view_preferences::ViewPresets::VIEW_PRESET_NONE),
            None => view_preferences::ViewPresets::VIEW_PRESET_NONE,
        }
    }

    pub fn clear_view_preset(&mut self) {
        self.view_preset = ::std::option::Option::None;
    }

    pub fn has_view_preset(&self) -> bool {
        self.view_preset.is_some()
    }

    // Param is passed by value, moved
    pub fn set_view_preset(&mut self, v: view_preferences::ViewPresets) {
        self.view_preset = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional .ltpb.ViewPreferences.SceneMode scene_mode = 6;

    pub fn scene_mode(&self) -> view_preferences::SceneMode {
        match self.scene_mode {
            Some(e) => e.enum_value_or(view_preferences::SceneMode::SCENE_MODE_PORTRAIT),
            None => view_preferences::SceneMode::SCENE_MODE_PORTRAIT,
        }
    }

    pub fn clear_scene_mode(&mut self) {
        self.scene_mode = ::std::option::Option::None;
    }

    pub fn has_scene_mode(&self) -> bool {
        self.scene_mode.is_some()
    }

    // Param is passed by value, moved
    pub fn set_scene_mode(&mut self, v: view_preferences::SceneMode) {
        self.scene_mode = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional .ltpb.ViewPreferences.AWBMode awb_mode = 7;

    pub fn awb_mode(&self) -> view_preferences::AWBMode {
        match self.awb_mode {
            Some(e) => e.enum_value_or(view_preferences::AWBMode::AWB_MODE_AUTO),
            None => view_preferences::AWBMode::AWB_MODE_AUTO,
        }
    }

    pub fn clear_awb_mode(&mut self) {
        self.awb_mode = ::std::option::Option::None;
    }

    pub fn has_awb_mode(&self) -> bool {
        self.awb_mode.is_some()
    }

    // Param is passed by value, moved
    pub fn set_awb_mode(&mut self, v: view_preferences::AWBMode) {
        self.awb_mode = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional .ltpb.ViewPreferences.Orientation orientation = 9;

    pub fn orientation(&self) -> view_preferences::Orientation {
        match self.orientation {
            Some(e) => e.enum_value_or(view_preferences::Orientation::ORIENTATION_NORMAL),
            None => view_preferences::Orientation::ORIENTATION_NORMAL,
        }
    }

    pub fn clear_orientation(&mut self) {
        self.orientation = ::std::option::Option::None;
    }

    pub fn has_orientation(&self) -> bool {
        self.orientation.is_some()
    }

    // Param is passed by value, moved
    pub fn set_orientation(&mut self, v: view_preferences::Orientation) {
        self.orientation = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional float image_gain = 10;

    pub fn image_gain(&self) -> f32 {
        self.image_gain.unwrap_or(0.)
    }

    pub fn clear_image_gain(&mut self) {
        self.image_gain = ::std::option::Option::None;
    }

    pub fn has_image_gain(&self) -> bool {
        self.image_gain.is_some()
    }

    // Param is passed by value, moved
    pub fn set_image_gain(&mut self, v: f32) {
        self.image_gain = ::std::option::Option::Some(v);
    }

    // optional uint64 image_integration_time_ns = 11;

    pub fn image_integration_time_ns(&self) -> u64 {
        self.image_integration_time_ns.unwrap_or(0)
    }

    pub fn clear_image_integration_time_ns(&mut self) {
        self.image_integration_time_ns = ::std::option::Option::None;
    }

    pub fn has_image_integration_time_ns(&self) -> bool {
        self.image_integration_time_ns.is_some()
    }

    // Param is passed by value, moved
    pub fn set_image_integration_time_ns(&mut self, v: u64) {
        self.image_integration_time_ns = ::std::option::Option::Some(v);
    }

    // optional uint32 user_rating = 12;

    pub fn user_rating(&self) -> u32 {
        self.user_rating.unwrap_or(0)
    }

    pub fn clear_user_rating(&mut self) {
        self.user_rating = ::std::option::Option::None;
    }

    pub fn has_user_rating(&self) -> bool {
        self.user_rating.is_some()
    }

    // Param is passed by value, moved
    pub fn set_user_rating(&mut self, v: u32) {
        self.user_rating = ::std::option::Option::Some(v);
    }

    // optional .ltpb.ViewPreferences.AspectRatio aspect_ratio = 13;

    pub fn aspect_ratio(&self) -> view_preferences::AspectRatio {
        match self.aspect_ratio {
            Some(e) => e.enum_value_or(view_preferences::AspectRatio::ASPECT_RATIO_4_3),
            None => view_preferences::AspectRatio::ASPECT_RATIO_4_3,
        }
    }

    pub fn clear_aspect_ratio(&mut self) {
        self.aspect_ratio = ::std::option::Option::None;
    }

    pub fn has_aspect_ratio(&self) -> bool {
        self.aspect_ratio.is_some()
    }

    // Param is passed by value, moved
    pub fn set_aspect_ratio(&mut self, v: view_preferences::AspectRatio) {
        self.aspect_ratio = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional bool is_on_tripod = 16;

    pub fn is_on_tripod(&self) -> bool {
        self.is_on_tripod.unwrap_or(false)
    }

    pub fn clear_is_on_tripod(&mut self) {
        self.is_on_tripod = ::std::option::Option::None;
    }

    pub fn has_is_on_tripod(&self) -> bool {
        self.is_on_tripod.is_some()
    }

    // Param is passed by value, moved
    pub fn set_is_on_tripod(&mut self, v: bool) {
        self.is_on_tripod = ::std::option::Option::Some(v);
    }

    // optional float qc_lux_index = 17;

    pub fn qc_lux_index(&self) -> f32 {
        self.qc_lux_index.unwrap_or(0.)
    }

    pub fn clear_qc_lux_index(&mut self) {
        self.qc_lux_index = ::std::option::Option::None;
    }

    pub fn has_qc_lux_index(&self) -> bool {
        self.qc_lux_index.is_some()
    }

    // Param is passed by value, moved
    pub fn set_qc_lux_index(&mut self, v: f32) {
        self.qc_lux_index = ::std::option::Option::Some(v);
    }

    // optional float display_gain = 18;

    pub fn display_gain(&self) -> f32 {
        self.display_gain.unwrap_or(0.)
    }

    pub fn clear_display_gain(&mut self) {
        self.display_gain = ::std::option::Option::None;
    }

    pub fn has_display_gain(&self) -> bool {
        self.display_gain.is_some()
    }

    // Param is passed by value, moved
    pub fn set_display_gain(&mut self, v: f32) {
        self.display_gain = ::std::option::Option::Some(v);
    }

    // optional uint64 display_integration_time_ns = 19;

    pub fn display_integration_time_ns(&self) -> u64 {
        self.display_integration_time_ns.unwrap_or(0)
    }

    pub fn clear_display_integration_time_ns(&mut self) {
        self.display_integration_time_ns = ::std::option::Option::None;
    }

    pub fn has_display_integration_time_ns(&self) -> bool {
        self.display_integration_time_ns.is_some()
    }

    // Param is passed by value, moved
    pub fn set_display_integration_time_ns(&mut self, v: u64) {
        self.display_integration_time_ns = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for ViewPreferences {
    const NAME: &'static str = "ViewPreferences";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                13 => {
                    self.f_number = ::std::option::Option::Some(is.read_float()?);
                },
                21 => {
                    self.ev_offset = ::std::option::Option::Some(is.read_float()?);
                },
                24 => {
                    self.disable_cropping = ::std::option::Option::Some(is.read_bool()?);
                },
                32 => {
                    self.hdr_mode = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                40 => {
                    self.view_preset = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                48 => {
                    self.scene_mode = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                56 => {
                    self.awb_mode = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                72 => {
                    self.orientation = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                85 => {
                    self.image_gain = ::std::option::Option::Some(is.read_float()?);
                },
                88 => {
                    self.image_integration_time_ns = ::std::option::Option::Some(is.read_uint64()?);
                },
                96 => {
                    self.user_rating = ::std::option::Option::Some(is.read_uint32()?);
                },
                104 => {
                    self.aspect_ratio = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                114 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.crop)?;
                },
                122 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.awb_gains)?;
                },
                128 => {
                    self.is_on_tripod = ::std::option::Option::Some(is.read_bool()?);
                },
                141 => {
                    self.qc_lux_index = ::std::option::Option::Some(is.read_float()?);
                },
                149 => {
                    self.display_gain = ::std::option::Option::Some(is.read_float()?);
                },
                152 => {
                    self.display_integration_time_ns = ::std::option::Option::Some(is.read_uint64()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.f_number {
            my_size += 1 + 4;
        }
        if let Some(v) = self.ev_offset {
            my_size += 1 + 4;
        }
        if let Some(v) = self.disable_cropping {
            my_size += 1 + 1;
        }
        if let Some(v) = self.hdr_mode {
            my_size += ::protobuf::rt::int32_size(4, v.value());
        }
        if let Some(v) = self.view_preset {
            my_size += ::protobuf::rt::int32_size(5, v.value());
        }
        if let Some(v) = self.scene_mode {
            my_size += ::protobuf::rt::int32_size(6, v.value());
        }
        if let Some(v) = self.awb_mode {
            my_size += ::protobuf::rt::int32_size(7, v.value());
        }
        if let Some(v) = self.orientation {
            my_size += ::protobuf::rt::int32_size(9, v.value());
        }
        if let Some(v) = self.image_gain {
            my_size += 1 + 4;
        }
        if let Some(v) = self.image_integration_time_ns {
            my_size += ::protobuf::rt::uint64_size(11, v);
        }
        if let Some(v) = self.user_rating {
            my_size += ::protobuf::rt::uint32_size(12, v);
        }
        if let Some(v) = self.aspect_ratio {
            my_size += ::protobuf::rt::int32_size(13, v.value());
        }
        if let Some(v) = self.crop.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.awb_gains.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.is_on_tripod {
            my_size += 2 + 1;
        }
        if let Some(v) = self.qc_lux_index {
            my_size += 2 + 4;
        }
        if let Some(v) = self.display_gain {
            my_size += 2 + 4;
        }
        if let Some(v) = self.display_integration_time_ns {
            my_size += ::protobuf::rt::uint64_size(19, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.f_number {
            os.write_float(1, v)?;
        }
        if let Some(v) = self.ev_offset {
            os.write_float(2, v)?;
        }
        if let Some(v) = self.disable_cropping {
            os.write_bool(3, v)?;
        }
        if let Some(v) = self.hdr_mode {
            os.write_enum(4, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.view_preset {
            os.write_enum(5, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.scene_mode {
            os.write_enum(6, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.awb_mode {
            os.write_enum(7, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.orientation {
            os.write_enum(9, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.image_gain {
            os.write_float(10, v)?;
        }
        if let Some(v) = self.image_integration_time_ns {
            os.write_uint64(11, v)?;
        }
        if let Some(v) = self.user_rating {
            os.write_uint32(12, v)?;
        }
        if let Some(v) = self.aspect_ratio {
            os.write_enum(13, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.crop.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(14, v, os)?;
        }
        if let Some(v) = self.awb_gains.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(15, v, os)?;
        }
        if let Some(v) = self.is_on_tripod {
            os.write_bool(16, v)?;
        }
        if let Some(v) = self.qc_lux_index {
            os.write_float(17, v)?;
        }
        if let Some(v) = self.display_gain {
            os.write_float(18, v)?;
        }
        if let Some(v) = self.display_integration_time_ns {
            os.write_uint64(19, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ViewPreferences {
        ViewPreferences::new()
    }

    fn clear(&mut self) {
        self.f_number = ::std::option::Option::None;
        self.ev_offset = ::std::option::Option::None;
        self.disable_cropping = ::std::option::Option::None;
        self.hdr_mode = ::std::option::Option::None;
        self.view_preset = ::std::option::Option::None;
        self.scene_mode = ::std::option::Option::None;
        self.awb_mode = ::std::option::Option::None;
        self.orientation = ::std::option::Option::None;
        self.image_gain = ::std::option::Option::None;
        self.image_integration_time_ns = ::std::option::Option::None;
        self.user_rating = ::std::option::Option::None;
        self.aspect_ratio = ::std::option::Option::None;
        self.crop.clear();
        self.awb_gains.clear();
        self.is_on_tripod = ::std::option::Option::None;
        self.qc_lux_index = ::std::option::Option::None;
        self.display_gain = ::std::option::Option::None;
        self.display_integration_time_ns = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ViewPreferences {
        static instance: ViewPreferences = ViewPreferences {
            f_number: ::std::option::Option::None,
            ev_offset: ::std::option::Option::None,
            disable_cropping: ::std::option::Option::None,
            hdr_mode: ::std::option::Option::None,
            view_preset: ::std::option::Option::None,
            scene_mode: ::std::option::Option::None,
            awb_mode: ::std::option::Option::None,
            orientation: ::std::option::Option::None,
            image_gain: ::std::option::Option::None,
            image_integration_time_ns: ::std::option::Option::None,
            user_rating: ::std::option::Option::None,
            aspect_ratio: ::std::option::Option::None,
            crop: ::protobuf::MessageField::none(),
            awb_gains: ::protobuf::MessageField::none(),
            is_on_tripod: ::std::option::Option::None,
            qc_lux_index: ::std::option::Option::None,
            display_gain: ::std::option::Option::None,
            display_integration_time_ns: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

/// Nested message and enums of message `ViewPreferences`
pub mod view_preferences {
    // @@protoc_insertion_point(message:ltpb.ViewPreferences.Crop)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct Crop {
        // message fields
        // @@protoc_insertion_point(field:ltpb.ViewPreferences.Crop.start)
        pub start: ::protobuf::MessageField<super::super::point2f::Point2F>,
        // @@protoc_insertion_point(field:ltpb.ViewPreferences.Crop.size)
        pub size: ::protobuf::MessageField<super::super::point2f::Point2F>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.ViewPreferences.Crop.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Crop {
        fn default() -> &'a Crop {
            <Crop as ::protobuf::Message>::default_instance()
        }
    }

    impl Crop {
        pub fn new() -> Crop {
            ::std::default::Default::default()
        }
    }

    impl ::protobuf::Message for Crop {
        const NAME: &'static str = "Crop";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.start)?;
                    },
                    18 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.size)?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.start.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.size.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.start.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
            }
            if let Some(v) = self.size.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Crop {
            Crop::new()
        }

        fn clear(&mut self) {
            self.start.clear();
            self.size.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Crop {
            static instance: Crop = Crop {
                start: ::protobuf::MessageField::none(),
                size: ::protobuf::MessageField::none(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    // @@protoc_insertion_point(message:ltpb.ViewPreferences.ChannelGain)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct ChannelGain {
        // message fields
        // @@protoc_insertion_point(field:ltpb.ViewPreferences.ChannelGain.r)
        pub r: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.ViewPreferences.ChannelGain.g_r)
        pub g_r: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.ViewPreferences.ChannelGain.g_b)
        pub g_b: ::std::option::Option<f32>,
        // @@protoc_insertion_point(field:ltpb.ViewPreferences.ChannelGain.b)
        pub b: ::std::option::Option<f32>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.ViewPreferences.ChannelGain.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a ChannelGain {
        fn default() -> &'a ChannelGain {
            <ChannelGain as ::protobuf::Message>::default_instance()
        }
    }

    impl ChannelGain {
        pub fn new() -> ChannelGain {
            ::std::default::Default::default()
        }

        // optional float r = 1;

        pub fn r(&self) -> f32 {
            self.r.unwrap_or(0.)
        }

        pub fn clear_r(&mut self) {
            self.r = ::std::option::Option::None;
        }

        pub fn has_r(&self) -> bool {
            self.r.is_some()
        }

        // Param is passed by value, moved
        pub fn set_r(&mut self, v: f32) {
            self.r = ::std::option::Option::Some(v);
        }

        // optional float g_r = 2;

        pub fn g_r(&self) -> f32 {
            self.g_r.unwrap_or(0.)
        }

        pub fn clear_g_r(&mut self) {
            self.g_r = ::std::option::Option::None;
        }

        pub fn has_g_r(&self) -> bool {
            self.g_r.is_some()
        }

        // Param is passed by value, moved
        pub fn set_g_r(&mut self, v: f32) {
            self.g_r = ::std::option::Option::Some(v);
        }

        // optional float g_b = 3;

        pub fn g_b(&self) -> f32 {
            self.g_b.unwrap_or(0.)
        }

        pub fn clear_g_b(&mut self) {
            self.g_b = ::std::option::Option::None;
        }

        pub fn has_g_b(&self) -> bool {
            self.g_b.is_some()
        }

        // Param is passed by value, moved
        pub fn set_g_b(&mut self, v: f32) {
            self.g_b = ::std::option::Option::Some(v);
        }

        // optional float b = 4;

        pub fn b(&self) -> f32 {
            self.b.unwrap_or(0.)
        }

        pub fn clear_b(&mut self) {
            self.b = ::std::option::Option::None;
        }

        pub fn has_b(&self) -> bool {
            self.b.is_some()
        }

        // Param is passed by value, moved
        pub fn set_b(&mut self, v: f32) {
            self.b = ::std::option::Option::Some(v);
        }
    }

    impl ::protobuf::Message for ChannelGain {
        const NAME: &'static str = "ChannelGain";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    13 => {
                        self.r = ::std::option::Option::Some(is.read_float()?);
                    },
                    21 => {
                        self.g_r = ::std::option::Option::Some(is.read_float()?);
                    },
                    29 => {
                        self.g_b = ::std::option::Option::Some(is.read_float()?);
                    },
                    37 => {
                        self.b = ::std::option::Option::Some(is.read_float()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.r {
                my_size += 1 + 4;
            }
            if let Some(v) = self.g_r {
                my_size += 1 + 4;
            }
            if let Some(v) = self.g_b {
                my_size += 1 + 4;
            }
            if let Some(v) = self.b {
                my_size += 1 + 4;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.r {
                os.write_float(1, v)?;
            }
            if let Some(v) = self.g_r {
                os.write_float(2, v)?;
            }
            if let Some(v) = self.g_b {
                os.write_float(3, v)?;
            }
            if let Some(v) = self.b {
                os.write_float(4, v)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> ChannelGain {
            ChannelGain::new()
        }

        fn clear(&mut self) {
            self.r = ::std::option::Option::None;
            self.g_r = ::std::option::Option::None;
            self.g_b = ::std::option::Option::None;
            self.b = ::std::option::Option::None;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static ChannelGain {
            static instance: ChannelGain = ChannelGain {
                r: ::std::option::Option::None,
                g_r: ::std::option::Option::None,
                g_b: ::std::option::Option::None,
                b: ::std::option::Option::None,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.ViewPreferences.HDRMode)
    pub enum HDRMode {
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.HDRMode.HDR_MODE_NONE)
        HDR_MODE_NONE = 0,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.HDRMode.HDR_MODE_DEFAULT)
        HDR_MODE_DEFAULT = 1,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.HDRMode.HDR_MODE_NATURAL)
        HDR_MODE_NATURAL = 2,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.HDRMode.HDR_MODE_SURREAL)
        HDR_MODE_SURREAL = 3,
    }

    impl ::protobuf::Enum for HDRMode {
        const NAME: &'static str = "HDRMode";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<HDRMode> {
            match value {
                0 => ::std::option::Option::Some(HDRMode::HDR_MODE_NONE),
                1 => ::std::option::Option::Some(HDRMode::HDR_MODE_DEFAULT),
                2 => ::std::option::Option::Some(HDRMode::HDR_MODE_NATURAL),
                3 => ::std::option::Option::Some(HDRMode::HDR_MODE_SURREAL),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<HDRMode> {
            match str {
                "HDR_MODE_NONE" => ::std::option::Option::Some(HDRMode::HDR_MODE_NONE),
                "HDR_MODE_DEFAULT" => ::std::option::Option::Some(HDRMode::HDR_MODE_DEFAULT),
                "HDR_MODE_NATURAL" => ::std::option::Option::Some(HDRMode::HDR_MODE_NATURAL),
                "HDR_MODE_SURREAL" => ::std::option::Option::Some(HDRMode::HDR_MODE_SURREAL),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [HDRMode] = &[
            HDRMode::HDR_MODE_NONE,
            HDRMode::HDR_MODE_DEFAULT,
            HDRMode::HDR_MODE_NATURAL,
            HDRMode::HDR_MODE_SURREAL,
        ];
    }

    impl ::std::default::Default for HDRMode {
        fn default() -> Self {
            HDRMode::HDR_MODE_NONE
        }
    }


    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.ViewPreferences.ViewPresets)
    pub enum ViewPresets {
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.ViewPresets.VIEW_PRESET_NONE)
        VIEW_PRESET_NONE = 0,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.ViewPresets.VIEW_PRESET_NATURAL)
        VIEW_PRESET_NATURAL = 1,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.ViewPresets.VIEW_PRESET_FAITHFUL)
        VIEW_PRESET_FAITHFUL = 2,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.ViewPresets.VIEW_PRESET_LANDSCAPE)
        VIEW_PRESET_LANDSCAPE = 3,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.ViewPresets.VIEW_PRESET_PORTRAIT)
        VIEW_PRESET_PORTRAIT = 4,
    }

    impl ::protobuf::Enum for ViewPresets {
        const NAME: &'static str = "ViewPresets";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<ViewPresets> {
            match value {
                0 => ::std::option::Option::Some(ViewPresets::VIEW_PRESET_NONE),
                1 => ::std::option::Option::Some(ViewPresets::VIEW_PRESET_NATURAL),
                2 => ::std::option::Option::Some(ViewPresets::VIEW_PRESET_FAITHFUL),
                3 => ::std::option::Option::Some(ViewPresets::VIEW_PRESET_LANDSCAPE),
                4 => ::std::option::Option::Some(ViewPresets::VIEW_PRESET_PORTRAIT),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<ViewPresets> {
            match str {
                "VIEW_PRESET_NONE" => ::std::option::Option::Some(ViewPresets::VIEW_PRESET_NONE),
                "VIEW_PRESET_NATURAL" => ::std::option::Option::Some(ViewPresets::VIEW_PRESET_NATURAL),
                "VIEW_PRESET_FAITHFUL" => ::std::option::Option::Some(ViewPresets::VIEW_PRESET_FAITHFUL),
                "VIEW_PRESET_LANDSCAPE" => ::std::option::Option::Some(ViewPresets::VIEW_PRESET_LANDSCAPE),
                "VIEW_PRESET_PORTRAIT" => ::std::option::Option::Some(ViewPresets::VIEW_PRESET_PORTRAIT),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [ViewPresets] = &[
            ViewPresets::VIEW_PRESET_NONE,
            ViewPresets::VIEW_PRESET_NATURAL,
            ViewPresets::VIEW_PRESET_FAITHFUL,
            ViewPresets::VIEW_PRESET_LANDSCAPE,
            ViewPresets::VIEW_PRESET_PORTRAIT,
        ];
    }

    impl ::std::default::Default for ViewPresets {
        fn default() -> Self {
            ViewPresets::VIEW_PRESET_NONE
        }
    }


    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.ViewPreferences.SceneMode)
    pub enum SceneMode {
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.SceneMode.SCENE_MODE_PORTRAIT)
        SCENE_MODE_PORTRAIT = 0,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.SceneMode.SCENE_MODE_LANDSCAPE)
        SCENE_MODE_LANDSCAPE = 1,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.SceneMode.SCENE_MODE_SPORT)
        SCENE_MODE_SPORT = 2,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.SceneMode.SCENE_MODE_MACRO)
        SCENE_MODE_MACRO = 3,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.SceneMode.SCENE_MODE_NIGHT)
        SCENE_MODE_NIGHT = 4,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.SceneMode.SCENE_MODE_NONE)
        SCENE_MODE_NONE = 5,
    }

    impl ::protobuf::Enum for SceneMode {
        const NAME: &'static str = "SceneMode";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<SceneMode> {
            match value {
                0 => ::std::option::Option::Some(SceneMode::SCENE_MODE_PORTRAIT),
                1 => ::std::option::Option::Some(SceneMode::SCENE_MODE_LANDSCAPE),
                2 => ::std::option::Option::Some(SceneMode::SCENE_MODE_SPORT),
                3 => ::std::option::Option::Some(SceneMode::SCENE_MODE_MACRO),
                4 => ::std::option::Option::Some(SceneMode::SCENE_MODE_NIGHT),
                5 => ::std::option::Option::Some(SceneMode::SCENE_MODE_NONE),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<SceneMode> {
            match str {
                "SCENE_MODE_PORTRAIT" => ::std::option::Option::Some(SceneMode::SCENE_MODE_PORTRAIT),
                "SCENE_MODE_LANDSCAPE" => ::std::option::Option::Some(SceneMode::SCENE_MODE_LANDSCAPE),
                "SCENE_MODE_SPORT" => ::std::option::Option::Some(SceneMode::SCENE_MODE_SPORT),
                "SCENE_MODE_MACRO" => ::std::option::Option::Some(SceneMode::SCENE_MODE_MACRO),
                "SCENE_MODE_NIGHT" => ::std::option::Option::Some(SceneMode::SCENE_MODE_NIGHT),
                "SCENE_MODE_NONE" => ::std::option::Option::Some(SceneMode::SCENE_MODE_NONE),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [SceneMode] = &[
            SceneMode::SCENE_MODE_PORTRAIT,
            SceneMode::SCENE_MODE_LANDSCAPE,
            SceneMode::SCENE_MODE_SPORT,
            SceneMode::SCENE_MODE_MACRO,
            SceneMode::SCENE_MODE_NIGHT,
            SceneMode::SCENE_MODE_NONE,
        ];
    }

    impl ::std::default::Default for SceneMode {
        fn default() -> Self {
            SceneMode::SCENE_MODE_PORTRAIT
        }
    }


    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.ViewPreferences.AWBMode)
    pub enum AWBMode {
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.AWBMode.AWB_MODE_AUTO)
        AWB_MODE_AUTO = 0,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.AWBMode.AWB_MODE_DAYLIGHT)
        AWB_MODE_DAYLIGHT = 1,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.AWBMode.AWB_MODE_SHADE)
        AWB_MODE_SHADE = 2,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.AWBMode.AWB_MODE_CLOUDY)
        AWB_MODE_CLOUDY = 3,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.AWBMode.AWB_MODE_TUNGSTEN)
        AWB_MODE_TUNGSTEN = 4,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.AWBMode.AWB_MODE_FLUORESCENT)
        AWB_MODE_FLUORESCENT = 5,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.AWBMode.AWB_MODE_FLASH)
        AWB_MODE_FLASH = 6,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.AWBMode.AWB_MODE_CUSTOM)
        AWB_MODE_CUSTOM = 7,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.AWBMode.AWB_MODE_KELVIN)
        AWB_MODE_KELVIN = 8,
    }

    impl ::protobuf::Enum for AWBMode {
        const NAME: &'static str = "AWBMode";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<AWBMode> {
            match value {
                0 => ::std::option::Option::Some(AWBMode::AWB_MODE_AUTO),
                1 => ::std::option::Option::Some(AWBMode::AWB_MODE_DAYLIGHT),
                2 => ::std::option::Option::Some(AWBMode::AWB_MODE_SHADE),
                3 => ::std::option::Option::Some(AWBMode::AWB_MODE_CLOUDY),
                4 => ::std::option::Option::Some(AWBMode::AWB_MODE_TUNGSTEN),
                5 => ::std::option::Option::Some(AWBMode::AWB_MODE_FLUORESCENT),
                6 => ::std::option::Option::Some(AWBMode::AWB_MODE_FLASH),
                7 => ::std::option::Option::Some(AWBMode::AWB_MODE_CUSTOM),
                8 => ::std::option::Option::Some(AWBMode::AWB_MODE_KELVIN),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<AWBMode> {
            match str {
                "AWB_MODE_AUTO" => ::std::option::Option::Some(AWBMode::AWB_MODE_AUTO),
                "AWB_MODE_DAYLIGHT" => ::std::option::Option::Some(AWBMode::AWB_MODE_DAYLIGHT),
                "AWB_MODE_SHADE" => ::std::option::Option::Some(AWBMode::AWB_MODE_SHADE),
                "AWB_MODE_CLOUDY" => ::std::option::Option::Some(AWBMode::AWB_MODE_CLOUDY),
                "AWB_MODE_TUNGSTEN" => ::std::option::Option::Some(AWBMode::AWB_MODE_TUNGSTEN),
                "AWB_MODE_FLUORESCENT" => ::std::option::Option::Some(AWBMode::AWB_MODE_FLUORESCENT),
                "AWB_MODE_FLASH" => ::std::option::Option::Some(AWBMode::AWB_MODE_FLASH),
                "AWB_MODE_CUSTOM" => ::std::option::Option::Some(AWBMode::AWB_MODE_CUSTOM),
                "AWB_MODE_KELVIN" => ::std::option::Option::Some(AWBMode::AWB_MODE_KELVIN),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [AWBMode] = &[
            AWBMode::AWB_MODE_AUTO,
            AWBMode::AWB_MODE_DAYLIGHT,
            AWBMode::AWB_MODE_SHADE,
            AWBMode::AWB_MODE_CLOUDY,
            AWBMode::AWB_MODE_TUNGSTEN,
            AWBMode::AWB_MODE_FLUORESCENT,
            AWBMode::AWB_MODE_FLASH,
            AWBMode::AWB_MODE_CUSTOM,
            AWBMode::AWB_MODE_KELVIN,
        ];
    }

    impl ::std::default::Default for AWBMode {
        fn default() -> Self {
            AWBMode::AWB_MODE_AUTO
        }
    }


    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.ViewPreferences.Orientation)
    pub enum Orientation {
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.Orientation.ORIENTATION_NORMAL)
        ORIENTATION_NORMAL = 0,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.Orientation.ORIENTATION_ROT90_CW)
        ORIENTATION_ROT90_CW = 1,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.Orientation.ORIENTATION_ROT90_CCW)
        ORIENTATION_ROT90_CCW = 2,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.Orientation.ORIENTATION_ROT90_CW_VFLIP)
        ORIENTATION_ROT90_CW_VFLIP = 3,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.Orientation.ORIENTATION_ROT90_CCW_VFLIP)
        ORIENTATION_ROT90_CCW_VFLIP = 4,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.Orientation.ORIENTATION_VFLIP)
        ORIENTATION_VFLIP = 5,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.Orientation.ORIENTATION_HFLIP)
        ORIENTATION_HFLIP = 6,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.Orientation.ORIENTATION_ROT180)
        ORIENTATION_ROT180 = 7,
    }

    impl ::protobuf::Enum for Orientation {
        const NAME: &'static str = "Orientation";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<Orientation> {
            match value {
                0 => ::std::option::Option::Some(Orientation::ORIENTATION_NORMAL),
                1 => ::std::option::Option::Some(Orientation::ORIENTATION_ROT90_CW),
                2 => ::std::option::Option::Some(Orientation::ORIENTATION_ROT90_CCW),
                3 => ::std::option::Option::Some(Orientation::ORIENTATION_ROT90_CW_VFLIP),
                4 => ::std::option::Option::Some(Orientation::ORIENTATION_ROT90_CCW_VFLIP),
                5 => ::std::option::Option::Some(Orientation::ORIENTATION_VFLIP),
                6 => ::std::option::Option::Some(Orientation::ORIENTATION_HFLIP),
                7 => ::std::option::Option::Some(Orientation::ORIENTATION_ROT180),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<Orientation> {
            match str {
                "ORIENTATION_NORMAL" => ::std::option::Option::Some(Orientation::ORIENTATION_NORMAL),
                "ORIENTATION_ROT90_CW" => ::std::option::Option::Some(Orientation::ORIENTATION_ROT90_CW),
                "ORIENTATION_ROT90_CCW" => ::std::option::Option::Some(Orientation::ORIENTATION_ROT90_CCW),
                "ORIENTATION_ROT90_CW_VFLIP" => ::std::option::Option::Some(Orientation::ORIENTATION_ROT90_CW_VFLIP),
                "ORIENTATION_ROT90_CCW_VFLIP" => ::std::option::Option::Some(Orientation::ORIENTATION_ROT90_CCW_VFLIP),
                "ORIENTATION_VFLIP" => ::std::option::Option::Some(Orientation::ORIENTATION_VFLIP),
                "ORIENTATION_HFLIP" => ::std::option::Option::Some(Orientation::ORIENTATION_HFLIP),
                "ORIENTATION_ROT180" => ::std::option::Option::Some(Orientation::ORIENTATION_ROT180),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [Orientation] = &[
            Orientation::ORIENTATION_NORMAL,
            Orientation::ORIENTATION_ROT90_CW,
            Orientation::ORIENTATION_ROT90_CCW,
            Orientation::ORIENTATION_ROT90_CW_VFLIP,
            Orientation::ORIENTATION_ROT90_CCW_VFLIP,
            Orientation::ORIENTATION_VFLIP,
            Orientation::ORIENTATION_HFLIP,
            Orientation::ORIENTATION_ROT180,
        ];
    }

    impl ::std::default::Default for Orientation {
        fn default() -> Self {
            Orientation::ORIENTATION_NORMAL
        }
    }


    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ltpb.ViewPreferences.AspectRatio)
    pub enum AspectRatio {
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.AspectRatio.ASPECT_RATIO_4_3)
        ASPECT_RATIO_4_3 = 0,
        // @@protoc_insertion_point(enum_value:ltpb.ViewPreferences.AspectRatio.ASPECT_RATIO_16_9)
        ASPECT_RATIO_16_9 = 1,
    }

    impl ::protobuf::Enum for AspectRatio {
        const NAME: &'static str = "AspectRatio";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<AspectRatio> {
            match value {
                0 => ::std::option::Option::Some(AspectRatio::ASPECT_RATIO_4_3),
                1 => ::std::option::Option::Some(AspectRatio::ASPECT_RATIO_16_9),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<AspectRatio> {
            match str {
                "ASPECT_RATIO_4_3" => ::std::option::Option::Some(AspectRatio::ASPECT_RATIO_4_3),
                "ASPECT_RATIO_16_9" => ::std::option::Option::Some(AspectRatio::ASPECT_RATIO_16_9),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [AspectRatio] = &[
            AspectRatio::ASPECT_RATIO_4_3,
            AspectRatio::ASPECT_RATIO_16_9,
        ];
    }

    impl ::std::default::Default for AspectRatio {
        fn default() -> Self {
            AspectRatio::ASPECT_RATIO_4_3
        }
    }

}
