// This file is generated by rust-protobuf 3.6.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `vignetting_characterization.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_6_0;

// @@protoc_insertion_point(message:ltpb.VignettingCharacterization)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct VignettingCharacterization {
    // message fields
    // @@protoc_insertion_point(field:ltpb.VignettingCharacterization.crosstalk)
    pub crosstalk: ::protobuf::MessageField<vignetting_characterization::CrosstalkModel>,
    // @@protoc_insertion_point(field:ltpb.VignettingCharacterization.vignetting)
    pub vignetting: ::std::vec::Vec<vignetting_characterization::MirrorVignettingModel>,
    // @@protoc_insertion_point(field:ltpb.VignettingCharacterization.relative_brightness)
    pub relative_brightness: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:ltpb.VignettingCharacterization.lens_hall_code)
    pub lens_hall_code: ::std::option::Option<i32>,
    // special fields
    // @@protoc_insertion_point(special_field:ltpb.VignettingCharacterization.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a VignettingCharacterization {
    fn default() -> &'a VignettingCharacterization {
        <VignettingCharacterization as ::protobuf::Message>::default_instance()
    }
}

impl VignettingCharacterization {
    pub fn new() -> VignettingCharacterization {
        ::std::default::Default::default()
    }

    // optional float relative_brightness = 3;

    pub fn relative_brightness(&self) -> f32 {
        self.relative_brightness.unwrap_or(0.)
    }

    pub fn clear_relative_brightness(&mut self) {
        self.relative_brightness = ::std::option::Option::None;
    }

    pub fn has_relative_brightness(&self) -> bool {
        self.relative_brightness.is_some()
    }

    // Param is passed by value, moved
    pub fn set_relative_brightness(&mut self, v: f32) {
        self.relative_brightness = ::std::option::Option::Some(v);
    }

    // optional int32 lens_hall_code = 4;

    pub fn lens_hall_code(&self) -> i32 {
        self.lens_hall_code.unwrap_or(0)
    }

    pub fn clear_lens_hall_code(&mut self) {
        self.lens_hall_code = ::std::option::Option::None;
    }

    pub fn has_lens_hall_code(&self) -> bool {
        self.lens_hall_code.is_some()
    }

    // Param is passed by value, moved
    pub fn set_lens_hall_code(&mut self, v: i32) {
        self.lens_hall_code = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for VignettingCharacterization {
    const NAME: &'static str = "VignettingCharacterization";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.crosstalk)?;
                },
                18 => {
                    self.vignetting.push(is.read_message()?);
                },
                29 => {
                    self.relative_brightness = ::std::option::Option::Some(is.read_float()?);
                },
                32 => {
                    self.lens_hall_code = ::std::option::Option::Some(is.read_int32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.crosstalk.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.vignetting {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.relative_brightness {
            my_size += 1 + 4;
        }
        if let Some(v) = self.lens_hall_code {
            my_size += ::protobuf::rt::int32_size(4, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.crosstalk.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        for v in &self.vignetting {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if let Some(v) = self.relative_brightness {
            os.write_float(3, v)?;
        }
        if let Some(v) = self.lens_hall_code {
            os.write_int32(4, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> VignettingCharacterization {
        VignettingCharacterization::new()
    }

    fn clear(&mut self) {
        self.crosstalk.clear();
        self.vignetting.clear();
        self.relative_brightness = ::std::option::Option::None;
        self.lens_hall_code = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static VignettingCharacterization {
        static instance: VignettingCharacterization = VignettingCharacterization {
            crosstalk: ::protobuf::MessageField::none(),
            vignetting: ::std::vec::Vec::new(),
            relative_brightness: ::std::option::Option::None,
            lens_hall_code: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

/// Nested message and enums of message `VignettingCharacterization`
pub mod vignetting_characterization {
    // @@protoc_insertion_point(message:ltpb.VignettingCharacterization.CrosstalkModel)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct CrosstalkModel {
        // message fields
        // @@protoc_insertion_point(field:ltpb.VignettingCharacterization.CrosstalkModel.width)
        pub width: ::std::option::Option<u32>,
        // @@protoc_insertion_point(field:ltpb.VignettingCharacterization.CrosstalkModel.height)
        pub height: ::std::option::Option<u32>,
        // @@protoc_insertion_point(field:ltpb.VignettingCharacterization.CrosstalkModel.data)
        pub data: ::std::vec::Vec<super::super::matrix4x4f::Matrix4x4F>,
        // @@protoc_insertion_point(field:ltpb.VignettingCharacterization.CrosstalkModel.data_packed)
        pub data_packed: ::std::vec::Vec<f32>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.VignettingCharacterization.CrosstalkModel.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a CrosstalkModel {
        fn default() -> &'a CrosstalkModel {
            <CrosstalkModel as ::protobuf::Message>::default_instance()
        }
    }

    impl CrosstalkModel {
        pub fn new() -> CrosstalkModel {
            ::std::default::Default::default()
        }

        // optional uint32 width = 1;

        pub fn width(&self) -> u32 {
            self.width.unwrap_or(0)
        }

        pub fn clear_width(&mut self) {
            self.width = ::std::option::Option::None;
        }

        pub fn has_width(&self) -> bool {
            self.width.is_some()
        }

        // Param is passed by value, moved
        pub fn set_width(&mut self, v: u32) {
            self.width = ::std::option::Option::Some(v);
        }

        // optional uint32 height = 2;

        pub fn height(&self) -> u32 {
            self.height.unwrap_or(0)
        }

        pub fn clear_height(&mut self) {
            self.height = ::std::option::Option::None;
        }

        pub fn has_height(&self) -> bool {
            self.height.is_some()
        }

        // Param is passed by value, moved
        pub fn set_height(&mut self, v: u32) {
            self.height = ::std::option::Option::Some(v);
        }
    }

    impl ::protobuf::Message for CrosstalkModel {
        const NAME: &'static str = "CrosstalkModel";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    8 => {
                        self.width = ::std::option::Option::Some(is.read_uint32()?);
                    },
                    16 => {
                        self.height = ::std::option::Option::Some(is.read_uint32()?);
                    },
                    26 => {
                        self.data.push(is.read_message()?);
                    },
                    34 => {
                        is.read_repeated_packed_float_into(&mut self.data_packed)?;
                    },
                    37 => {
                        self.data_packed.push(is.read_float()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.width {
                my_size += ::protobuf::rt::uint32_size(1, v);
            }
            if let Some(v) = self.height {
                my_size += ::protobuf::rt::uint32_size(2, v);
            }
            for value in &self.data {
                let len = value.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            };
            my_size += ::protobuf::rt::vec_packed_float_size(4, &self.data_packed);
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.width {
                os.write_uint32(1, v)?;
            }
            if let Some(v) = self.height {
                os.write_uint32(2, v)?;
            }
            for v in &self.data {
                ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
            };
            os.write_repeated_packed_float(4, &self.data_packed)?;
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> CrosstalkModel {
            CrosstalkModel::new()
        }

        fn clear(&mut self) {
            self.width = ::std::option::Option::None;
            self.height = ::std::option::Option::None;
            self.data.clear();
            self.data_packed.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static CrosstalkModel {
            static instance: CrosstalkModel = CrosstalkModel {
                width: ::std::option::Option::None,
                height: ::std::option::Option::None,
                data: ::std::vec::Vec::new(),
                data_packed: ::std::vec::Vec::new(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    // @@protoc_insertion_point(message:ltpb.VignettingCharacterization.MirrorVignettingModel)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct MirrorVignettingModel {
        // message fields
        // @@protoc_insertion_point(field:ltpb.VignettingCharacterization.MirrorVignettingModel.hall_code)
        pub hall_code: ::std::option::Option<i32>,
        // @@protoc_insertion_point(field:ltpb.VignettingCharacterization.MirrorVignettingModel.vignetting)
        pub vignetting: ::protobuf::MessageField<VignettingModel>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.VignettingCharacterization.MirrorVignettingModel.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a MirrorVignettingModel {
        fn default() -> &'a MirrorVignettingModel {
            <MirrorVignettingModel as ::protobuf::Message>::default_instance()
        }
    }

    impl MirrorVignettingModel {
        pub fn new() -> MirrorVignettingModel {
            ::std::default::Default::default()
        }

        // optional int32 hall_code = 1;

        pub fn hall_code(&self) -> i32 {
            self.hall_code.unwrap_or(0)
        }

        pub fn clear_hall_code(&mut self) {
            self.hall_code = ::std::option::Option::None;
        }

        pub fn has_hall_code(&self) -> bool {
            self.hall_code.is_some()
        }

        // Param is passed by value, moved
        pub fn set_hall_code(&mut self, v: i32) {
            self.hall_code = ::std::option::Option::Some(v);
        }
    }

    impl ::protobuf::Message for MirrorVignettingModel {
        const NAME: &'static str = "MirrorVignettingModel";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    8 => {
                        self.hall_code = ::std::option::Option::Some(is.read_int32()?);
                    },
                    18 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.vignetting)?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.hall_code {
                my_size += ::protobuf::rt::int32_size(1, v);
            }
            if let Some(v) = self.vignetting.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.hall_code {
                os.write_int32(1, v)?;
            }
            if let Some(v) = self.vignetting.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> MirrorVignettingModel {
            MirrorVignettingModel::new()
        }

        fn clear(&mut self) {
            self.hall_code = ::std::option::Option::None;
            self.vignetting.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static MirrorVignettingModel {
            static instance: MirrorVignettingModel = MirrorVignettingModel {
                hall_code: ::std::option::Option::None,
                vignetting: ::protobuf::MessageField::none(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    // @@protoc_insertion_point(message:ltpb.VignettingCharacterization.VignettingModel)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct VignettingModel {
        // message fields
        // @@protoc_insertion_point(field:ltpb.VignettingCharacterization.VignettingModel.width)
        pub width: ::std::option::Option<u32>,
        // @@protoc_insertion_point(field:ltpb.VignettingCharacterization.VignettingModel.height)
        pub height: ::std::option::Option<u32>,
        // @@protoc_insertion_point(field:ltpb.VignettingCharacterization.VignettingModel.data)
        pub data: ::std::vec::Vec<f32>,
        // special fields
        // @@protoc_insertion_point(special_field:ltpb.VignettingCharacterization.VignettingModel.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a VignettingModel {
        fn default() -> &'a VignettingModel {
            <VignettingModel as ::protobuf::Message>::default_instance()
        }
    }

    impl VignettingModel {
        pub fn new() -> VignettingModel {
            ::std::default::Default::default()
        }

        // optional uint32 width = 1;

        pub fn width(&self) -> u32 {
            self.width.unwrap_or(0)
        }

        pub fn clear_width(&mut self) {
            self.width = ::std::option::Option::None;
        }

        pub fn has_width(&self) -> bool {
            self.width.is_some()
        }

        // Param is passed by value, moved
        pub fn set_width(&mut self, v: u32) {
            self.width = ::std::option::Option::Some(v);
        }

        // optional uint32 height = 2;

        pub fn height(&self) -> u32 {
            self.height.unwrap_or(0)
        }

        pub fn clear_height(&mut self) {
            self.height = ::std::option::Option::None;
        }

        pub fn has_height(&self) -> bool {
            self.height.is_some()
        }

        // Param is passed by value, moved
        pub fn set_height(&mut self, v: u32) {
            self.height = ::std::option::Option::Some(v);
        }
    }

    impl ::protobuf::Message for VignettingModel {
        const NAME: &'static str = "VignettingModel";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    8 => {
                        self.width = ::std::option::Option::Some(is.read_uint32()?);
                    },
                    16 => {
                        self.height = ::std::option::Option::Some(is.read_uint32()?);
                    },
                    26 => {
                        is.read_repeated_packed_float_into(&mut self.data)?;
                    },
                    29 => {
                        self.data.push(is.read_float()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.width {
                my_size += ::protobuf::rt::uint32_size(1, v);
            }
            if let Some(v) = self.height {
                my_size += ::protobuf::rt::uint32_size(2, v);
            }
            my_size += ::protobuf::rt::vec_packed_float_size(3, &self.data);
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.width {
                os.write_uint32(1, v)?;
            }
            if let Some(v) = self.height {
                os.write_uint32(2, v)?;
            }
            os.write_repeated_packed_float(3, &self.data)?;
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> VignettingModel {
            VignettingModel::new()
        }

        fn clear(&mut self) {
            self.width = ::std::option::Option::None;
            self.height = ::std::option::Option::None;
            self.data.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static VignettingModel {
            static instance: VignettingModel = VignettingModel {
                width: ::std::option::Option::None,
                height: ::std::option::Option::None,
                data: ::std::vec::Vec::new(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }
}
